#
# RBS Misc Makefile
#

obj-$(CONFIG_CPM_MISC_GTACC) += cpm_misc_gtacc.o

obj-$(CONFIG_CPM1_MISC_PHACC) += cpm1_misc_phacc.o

obj-$(CONFIG_CPM2_MISC_PHACC) += cpm2_misc_phacc.o

obj-$(CONFIG_CPM1_MISC_SYSTEM_WATCHDOG) += cpm1-wdt.o

obj-$(CONFIG_CPM_MISC_SYSTEM_WATCHDOG) += cpm-wdt.o
