#
# RBS SYS Makefile
#
obj-y += rbs-sys.o
obj-y += rbs-sys-dusx2_sim.o
obj-$(CONFIG_RBS_SYS_TCU03) += rbs-sys-tcu03.o
obj-$(CONFIG_RBS_SYS_TCU04) += rbs-sys-tcu04.o
obj-$(CONFIG_RBS_SYS_DUS32) += rbs-sys-dus32.o
obj-$(CONFIG_RBS_SYS_DUS32_TK) += rbs-sys-dus32_tk.o
obj-$(CONFIG_RBS_SYS_C608) += rbs-sys-c608.o
obj-$(CONFIG_RBS_SYS_DUS52) += rbs-sys-dus52.o
obj-$(CONFIG_RBS_SYS_DUS52_TK) += rbs-sys-dus52_tk.o
obj-$(CONFIG_RBS_SYS_CPM1) += rbs-sys-cpm.o
obj-$(CONFIG_RBS_SYS_CPM2) += rbs-sys-cpm.o
obj-$(CONFIG_RBS_SYS_DUS33) += rbs-sys-dus33.o
obj-$(CONFIG_RBS_SYS_DUS53) += rbs-sys-dus53.o
obj-$(CONFIG_RBS_SYS_MDUSX3) += rbs-sys-mdusx3.o
obj-$(CONFIG_RBS_SYS_PLATFORM) += rbs-sys-platform.o
obj-$(CONFIG_RBS_SYS_LOCKUP_DETECTOR) += rbs-sys-watchdog.o
obj-y += rbs-sys-unknown.o
