#!/usr/bin/env python
import subprocess
from waflib.Configure import conf

APPNAME = 'RCS-CT'
VERSION = '0.0001'
VSN = subprocess.check_output( ['git', 'rev-parse', '--short', 'HEAD'] ).strip()
top = '.'
out = 'build'

def options(opt):
   opt.load('compiler_c')
   opt.load('rcstools', tooldir="../../tools/")


def configure(conf):
   conf.load('compiler_c')
   conf.load('rcstools', tooldir="tools/")

   conf.env.append_value('CFLAGS', ['-Wall', '-g', '-std=gnu99'])
   conf.find_program('erl',      var='ERL')
   conf.define('APPNAME', APPNAME)
   conf.define('VERSION', VERSION)
   conf.write_config_header('config.h')

def build(bld):
   bld.recurse('lib/labb')
   bld.recurse('lib/lib-cli')
   bld.recurse('lib/lib-netconf')
   bld.recurse('lib/lib')
   bld.recurse('lib/rcs-modump')
   bld.recurse('lib/rcs-sftpd')
   bld.recurse('lib/rcs-upinspect')
   bld.recurse('lib/rct-proxy')
   bld.recurse('lib/rct-snmpmgr')
   bld.recurse('lib/rct-jsone')
   bld.recurse('lib/saf-ift')
   bld.recurse('lib/saf-rpc')
   bld.recurse('lib/supp')
