%%% %CCaseCopyrightBegin%
%%% Copyright (c) Ericsson AB 2014 All rights reserved.
%%% 
%%% The information in this document is the property of Ericsson.
%%% 
%%% Except as specifically authorized in writing by Ericsson, the 
%%% receiver of this document shall keep the information contained 
%%% herein confidential and shall protect the same in whole or in 
%%% part from disclosure and dissemination to third parties.
%%% 
%%% Disclosure and disseminations to the receivers employees shall 
%%% only be made on a strict need to know basis.
%%% %CCaseCopyrightEnd%

-define(FORM_TEMPLATE,
[
"<!DOCTYPE html PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN'> ",
"<html> ",
"  <head> ",
"    <meta content='text/html; charset=ISO-8859-1' ",
"      http-equiv='Content-Type'> ",
"    <title>Availability Log interface</title> ",
"  </head> ",
"  <body> ",
"    <h2> Availability Log interface</h2> ",
"    Running on <b>RBS CS</b><br> ",
"    <br> ",
"    <form action='", url, "' method='get'> ",
"      <table bgcolor='#eeffff' border='0' cellpadding='2' ",
"        cellspacing='2'> ",
"        <tbody> ",
"          <tr> ",
"            <td valign='top'><br> ",
"              <input name='req' value='initMem' type='radio'> init ",
"              memory<br> ",
"              <input name='req' value='initSvc' type='radio'> init ",
"              service<br> ",
"              <input name='req' value='freeMem' type='radio'> free ",
"              memory<br> ",
"              <input name='req' value='nodeEvent' type='radio'> write ",
"              node event<br> ",
"              <input name='req' value='piuEvent' type='radio'> write PIU ",
"              event<br> ",
"              <input name='req' value='hwEvent' type='radio'> write HW ",
"              event<br> ",
"              <input name='req' value='svcEvent' type='radio'> write ",
"              service event<br> ",
"              <input name='req' value='pgmEvent' type='radio'> write ",
"              program event<br> ",
"              <input name='req' value='otherEvent' type='radio'> write ",
"              other event<br> ",
"            </td> ",
"            <td valign='top'><br> ",
"              <table border='0' cellpadding='2' cellspacing='2'> ",
"                <tbody> ",
"                  <tr> ",
"                    <td align='right' valign='top'>service status<br> ",
"                    </td> ",
"                    <td valign='top'> ",
"                      <select name='svcStatus' size='1'> ",
"                        <option value='0'>-- please select --</option> ",
"                        <option value='1'>in service</option> ",
"                        <option value='2'>out of service</option> ",
"                        <option value='3'>partially out of service</option> ",
"                      </select> ",
"                    </td> ",
"                  </tr> ",
"                  <tr> ",
"                    <td align='right' valign='top'>reason<br> ",
"                    </td> ",
"                    <td valign='top'> ",
"                      <select name='reason' size='1'> ",
"                        <option value='0'>-- please select --</option> ",
"                        <option value='1'>shutdown command</option> ",
"                        <option value='2'>unoperational</option> ",
"                        <option value='3'>starting</option> ",
"                        <option value='4'>operational</option> ",
"                      </select> ",
"                    </td> ",
"                  </tr> ",
"                  <tr> ",
"                    <td align='right' valign='top'>PIU type<br> ",
"                    </td> ",
"                    <td valign='top'> ",
"                      <select name='piuType' size='1'> ",
"                        <option value='0'>-- please select --</option> ",
"                        <option value='1'>MP</option> ",
"                        <option value='2'>BP</option> ",
"                      </select> ",
"                    </td> ",
"                  </tr> ",
"                  <tr> ",
"                    <td align='right' valign='top'>PIU HW addr<br> ",
"                    </td> ",
"                    <td valign='top'> <input name='piuHwAddr' ",
"                        type='text'> ",
"                      (e&nbsp;g:&nbsp;11,&nbsp;22,&nbsp;33) </td> ",
"                  </tr> ",
"                  <tr> ",
"                    <td align='right' valign='top'>HW PID<br> ",
"                    </td> ",
"                    <td valign='top'> <input name='hwPid' type='text'>&nbsp;(e&nbsp;g: ",
" ",
" ",
" ",
" ",
"                      XYZ22555,&nbsp;R1B, QWERTY, 2012DEC12, 9254) </td> ",
"                  </tr> ",
"                  <tr> ",
"                    <td align='right' valign='top'>HW type<br> ",
"                    </td> ",
"                    <td valign='top'> <input name='hwType' type='text'> ",
"                      (text) </td> ",
"                  </tr> ",
"                  <tr> ",
"                    <td align='right' valign='top'>HW address<br> ",
"                    </td> ",
"                    <td valign='top'> <input name='hwAddress' ",
"                        type='text'> (text) </td> ",
"                  </tr> ",
"                  <tr> ",
"                    <td align='right' valign='top'>service type<br> ",
"                    </td> ",
"                    <td valign='top'> <input name='svcType' type='text'> ",
"                      (text) </td> ",
"                  </tr> ",
"                  <tr> ",
"                    <td align='right' valign='top'>service instance</td> ",
"                    <td valign='top'> <input name='svcInst' type='text'> ",
"                      (text) </td> ",
"                  </tr> ",
"                  <tr> ",
"                    <td align='right' valign='top'>availability info</td> ",
"                    <td valign='top'> <input name='avInfo' type='text'> ",
"                      (text) </td> ",
"                  </tr> ",
"                  <tr> ",
"                    <td align='right' valign='top'>SW PID<br> ",
"                    </td> ",
"                    <td valign='top'> <input name='swPid' type='text'>&nbsp;(e&nbsp;g: ",
" ",
" ",
" ",
" ",
"                      CDE33777, R2C, ASDF, 2012DEC12) </td> ",
"                  </tr> ",
"                  <tr> ",
"                    <td align='right' valign='top'>additional info</td> ",
"                    <td valign='top'> <input name='addInfo' type='text'> ",
"                      (text) </td> ",
"                  </tr> ",
"                  <tr> ",
"                    <td align='right' valign='top'>client ref<br> ",
"                    </td> ",
"                    <td valign='top'> <input name='clientRef' ",
"                        type='text'> (numeric) </td> ",
"                  </tr> ",
"                </tbody> ",
"              </table> ",
"              <br> ",
"            </td> ",
"          </tr> ",
"        </tbody> ",
"      </table> ",
"      <br> ",
"      <input name='submit' value='submit' type='submit'> <input ",
"        name='submit' value='quit' type='submit'> <br> ",
"    </form> ",
"    <br> ",
"    <b>Result: ", result, "</b><br> ",
"    <br> ",
"    <b>", logData, "</b><br> ",
"    <br> ",
"    <hr size='2' width='100%'><br> ",
"    Self: ", self, "<br> ",
"    Current time: ", now, " <br> ",
"    Form data: ", input, "<br> ",
"    <br> ",
"    <br> ",
"  </body> ",
"</html> "
]
).
