#!/usr/bin/env bash

# Make sure that we use a git version that understands "git remote get-url"
source ${MODULESHOME-/app/modules/0}/init/bash
module add git/${GIT_VERSION-2.8.1}

gerrit_mirror="ssh://gerritmirror"
gerrit_central="ssh://gerrit.ericsson.se:"
with_user="ssh://\w\+@"
without_user="ssh://"

# There is no guarantee that the remote to change is called origin, it can be just any name
# So, consider only remotes that contain ":29418/"

for remote in `git remote -vvv | grep ":29418/" | awk '{print $1}' | sort -u` ; do
    # For the found remotes, change the push to gerrit central AND the fetch to Kista local mirror
    ##### echo "remote = $remote"

    origin_push=$( git remote get-url --push ${remote} )

    remote_push=${gerrit_central}${origin_push#ssh://*:}


    if  [[ $origin_push != $remote_push ]]; then
        ##### echo "origin_push = $origin_push"
        ##### echo "remote_push = $remote_push"
        ##### echo "Updating ${remote} push url"
        git remote set-url ${remote} --push ${remote_push}
    fi



    origin_fetch=$( git  remote get-url ${remote} )
    remote_fetch=$( echo $origin_fetch | sed "s,${with_user},${without_user},g" | sed "s,${gerrit_central},ssh://gerritmirror-ha.rnd.ki.sw.ericsson.se:,g")


    if  [[ $origin_fetch != $remote_fetch ]]; then
        ##### echo "origin_fetch = $origin_fetch"
        ##### echo "remote_fetch = $remote_fetch"
        ##### echo "Updating ${remote} fetch url"
        git remote set-url ${remote}        ${remote_fetch}
    fi
done

