%% Automatically generated, do not edit
%% Generated by gpb_compile version 2.0 Src: log.proto@@/main/R2A/2

-ifndef(log).
-define(log, true).

-define(log_gpb_version, "2.0").

-record(safsLogSeverityFlags,
        {saLogSevFlagEmergency,         % = 1, bool
         saLogSevFlagAlert,             % = 2, bool
         saLogSevFlagCritical,          % = 3, bool
         saLogSevFlagError,             % = 4, bool
         saLogSevFlagWarning,           % = 5, bool
         saLogSevFlagNotice,            % = 6, bool
         saLogSevFlagInfo               % = 7, bool
        }).

-record(safsLogNtfLogHeader,
        {notificationId,                % = 1, uint64
         eventType,                     % = 2, {enum,safsNtfEventType}
         notificationObject,            % = 3, string
         notifyingObject,               % = 4, string
         notificationClassId,           % = 5, {msg,safsNtfClassId} (optional)
         eventTime                      % = 6, uint64
        }).

-record(safsLogGenericLogHeader,
        {notificationClassId,           % = 1, {msg,safsNtfClassId} (optional)
         logSvcUsrName,                 % = 2, string
         logSeverity                    % = 3, {enum,safsLogSeverity}
        }).

-record(safsLogHeader,
        {ntfHdr,                        % = 1, {msg,safsLogNtfLogHeader} (optional)
         genericHdr                     % = 2, {msg,safsLogGenericLogHeader} (optional)
        }).

-record(safsLogRecord,
        {logTimeStamp,                  % = 1, uint64
         logHdrType,                    % = 2, {enum,safsLogHeaderType}
         logHeader,                     % = 3, {msg,safsLogHeader}
         logBuffer                      % = 4, string (optional)
        }).

-record(safsLogFileCreateAttributes_2,
        {logFileName,                   % = 1, string
         logFilePathName,               % = 2, string (optional)
         maxLogFileSize,                % = 3, uint64
         maxLogRecordSize,              % = 4, uint32
         haProperty,                    % = 5, bool
         logFileFullAction,             % = 6, {enum,safsLogFileFullAction}
         maxFilesRotated,               % = 7, uint32 (optional)
         logFileFmt                     % = 8, string (optional)
        }).

-record(safsLogCallbacks,
        {saLogFilterSetCallback,        % = 1, bool
         saLogStreamOpenCallback,       % = 2, bool
         saLogWriteLogCallback          % = 3, bool
        }).

-record(safsLogInitialize,
        {callbacks,                     % = 1, {msg,safsLogCallbacks} (optional)
         version                        % = 2, {msg,safsVersion} (optional)
        }).

-record(safsLogFinalize,
        {handle                         % = 1, uint64
        }).

-record(safsLogStreamOpen_2,
        {handle,                        % = 1, uint64
         logStreamName,                 % = 2, string
         logFileCreateAttributes,       % = 3, {msg,safsLogFileCreateAttributes_2} (optional)
         logStreamOpenFlags,            % = 4, {enum,safsLogStreamOpenFlags} (optional)
         timeout                        % = 5, uint64 (optional)
        }).

-record(safsLogStreamOpenAsync_2,
        {handle,                        % = 1, uint64
         logStreamName,                 % = 2, string
         logFileCreateAttributes,       % = 3, {msg,safsLogFileCreateAttributes_2} (optional)
         logStreamOpenFlags,            % = 4, {enum,safsLogStreamOpenFlags} (optional)
         invocation                     % = 5, uint64
        }).

-record(saLogStreamOpenCallback,
        {invocation,                    % = 1, uint64
         logStreamHandle,               % = 2, uint64
         error                          % = 3, {enum,safsAisError}
        }).

-record(safsLogWriteLog,
        {logStreamHandle,               % = 1, uint64
         timeout,                       % = 2, uint64 (optional)
         logRecord                      % = 3, {msg,safsLogRecord}
        }).

-record(safsLogWriteLogAsync,
        {logStreamHandle,               % = 1, uint64
         invocation,                    % = 2, uint64
         ackFlags,                      % = 3, {enum,safsLogAckFlags} (optional)
         logRecord                      % = 4, {msg,safsLogRecord}
        }).

-record(saLogWriteLogCallback,
        {invocation,                    % = 1, uint64
         error                          % = 2, {enum,safsAisError}
        }).

-record(saLogFilterSetCallback,
        {logStreamHandle,               % = 1, uint64
         logSeverity                    % = 2, {msg,safsLogSeverityFlags}
        }).

-record(safsLogStreamClose,
        {logStreamHandle                % = 1, uint64
        }).

-record(safsLogLimitGet,
        {handle,                        % = 1, uint64
         limitId                        % = 2, {enum,safsLogLimitId}
        }).

-record(safsLogCallbacksInitialize,
        {handle                         % = 1, uint64
        }).

-record(safsLogDeleteFiles,
        {handle,                        % = 1, uint64
         logFileName,                   % = 2, string
         logFilePathName                % = 3, string (optional)
        }).

-record(safsLogMessage,
        {initialize,                    % = 1, {msg,safsLogInitialize} (optional)
         finalize,                      % = 2, {msg,safsLogFinalize} (optional)
         logStreamOpen,                 % = 3, {msg,safsLogStreamOpen_2} (optional)
         logStreamOpenAsync,            % = 4, {msg,safsLogStreamOpenAsync_2} (optional)
         logWriteLog,                   % = 5, {msg,safsLogWriteLog} (optional)
         logWriteLogAsync,              % = 6, {msg,safsLogWriteLogAsync} (optional)
         logStreamClose,                % = 7, {msg,safsLogStreamClose} (optional)
         logLimitGet,                   % = 8, {msg,safsLogLimitGet} (optional)
         callbacksInitialize,           % = 9, {msg,safsLogCallbacksInitialize} (optional)
         logDeleteFiles                 % = 10, {msg,safsLogDeleteFiles} (optional)
        }).

-record(saLogCallbacks,
        {logStreamOpenCallback,         % = 1, {msg,saLogStreamOpenCallback} (optional)
         logWriteLogCallback,           % = 2, {msg,saLogWriteLogCallback} (optional)
         logFilterSetCallback           % = 3, {msg,saLogFilterSetCallback} (optional)
        }).

-record(safsLimitValue,
        {uint64Value                    % = 2, uint64
        }).

-record(safsLogInitializeRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         handle,                        % = 2, uint64
         version                        % = 3, {msg,safsVersion}
        }).

-record(safsLogFinalizeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsLogStreamOpen_2Ret,
        {logStreamHandle,               % = 1, uint64 (optional)
         returnVal                      % = 2, {enum,safsAisError}
        }).

-record(safsLogStreamOpenAsync_2Ret,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsLogWriteLogRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsLogWriteLogAsyncRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsLogStreamCloseRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsLogLimitGetRet,
        {limitValue,                    % = 1, {msg,safsLimitValue}
         returnVal                      % = 2, {enum,safsAisError}
        }).

-record(safsLogCallbacksInitializeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(saLogCallbacksRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsLogDeleteFilesRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsAny,
        {bufferSize,                    % = 1, uint64
         bufferAddr                     % = 2, bytes
        }).

-record(safsVersion,
        {releaseCode,                   % = 1, uint32
         majorVersion,                  % = 2, uint32
         minorVersion                   % = 3, uint32
        }).

-record(safsNtfClassId,
        {vendorId,                      % = 1, uint32
         majorId,                       % = 2, uint32
         minorId                        % = 3, uint32
        }).

-record(safsNtfValue,
        {uint8Val,                      % = 1, uint32 (optional)
         int8Val,                       % = 2, int32 (optional)
         uint16Val,                     % = 3, uint32 (optional)
         int16Val,                      % = 4, int32 (optional)
         uint32Val,                     % = 5, uint32 (optional)
         int32Val,                      % = 6, int32 (optional)
         floatVal,                      % = 7, double (optional)
         uint64Val,                     % = 8, uint64 (optional)
         int64Val,                      % = 9, int64 (optional)
         doubleVal,                     % = 10, double (optional)
         variable,                      % = 11, bytes (optional)
         csstruct                       % = 9999, {msg,safsImmCsStruct} (optional)
        }).

-record(safsNtfAdditionalInfo,
        {infoId,                        % = 1, uint32
         infoType,                      % = 2, {enum,safsNtfValueType}
         infoValue                      % = 3, {msg,safsNtfValue}
        }).

-record(safsNtfSpecificProblem,
        {problemId,                     % = 1, uint32
         problemClassId,                % = 2, {msg,safsNtfClassId}
         problemType,                   % = 3, {enum,safsNtfValueType}
         problemValue                   % = 4, {msg,safsNtfValue}
        }).

-record(safsNtfCallbacks,
        {saNtfNotificationCallback,     % = 1, bool
         saNtfNotificationDiscardedCallback % = 2, bool
        }).

-record(safsNtfThresholdInformation,
        {thresholdId,                   % = 1, uint32
         thresholdValueType,            % = 2, {enum,safsNtfValueType}
         thresholdValue,                % = 3, {msg,safsNtfValue}
         thresholdHysteresis,           % = 4, {msg,safsNtfValue}
         observedValue,                 % = 5, {msg,safsNtfValue}
         armTime                        % = 6, int64
        }).

-record(safsNtfProposedRepairAction,
        {actionId,                      % = 1, uint32
         actionValueType,               % = 2, {enum,safsNtfValueType}
         actionValue                    % = 3, {msg,safsNtfValue}
        }).

-record(safsNtfStateChange,
        {stateId,                       % = 1, uint32
         oldState,                      % = 2, uint32 (optional)
         newState                       % = 3, uint32
        }).

-record(safsNtfAttribute,
        {attributeId,                   % = 1, uint32
         attributeType,                 % = 2, {enum,safsNtfValueType}
         attributeValue                 % = 3, {msg,safsNtfValue}
        }).

-record(safsNtfAttributeChange,
        {attributeId,                   % = 1, uint32
         attributeType,                 % = 2, {enum,safsNtfValueType}
         oldAttributeValue,             % = 3, {msg,safsNtfValue} (optional)
         newAttributeValue              % = 4, {msg,safsNtfValue}
        }).

-record(safsNtfServiceUser,
        {valueType,                     % = 1, {enum,safsNtfValueType}
         value                          % = 2, {msg,safsNtfValue}
        }).

-record(safsNtfSecurityAlarmDetector,
        {valueType,                     % = 1, {enum,safsNtfValueType}
         value                          % = 2, {msg,safsNtfValue}
        }).

-record(safsNtfNotificationHeader,
        {eventType,                     % = 1, {enum,safsNtfEventType}
         notificationObject,            % = 2, string
         notifyingObject,               % = 3, string
         notificationClassId,           % = 4, {msg,safsNtfClassId}
         eventTime,                     % = 5, int64
         correlatedNotifications,       % = 6, [uint64]
         additionalText,                % = 7, string (optional)
         additionalInfo                 % = 8, [{msg,safsNtfAdditionalInfo}]
        }).

-record(safsNtfObjectCreateDeleteNotification,
        {notificationHeader,            % = 1, {msg,safsNtfNotificationHeader}
         sourceIndicator,               % = 2, {enum,safsNtfSourceIndicator}
         objectAttributes               % = 3, [{msg,safsNtfAttribute}]
        }).

-record(safsNtfAttributeChangeNotification,
        {notificationHeader,            % = 1, {msg,safsNtfNotificationHeader}
         sourceIndicator,               % = 2, {enum,safsNtfSourceIndicator}
         changedAttributes              % = 3, [{msg,safsNtfAttributeChange}]
        }).

-record(safsNtfStateChangeNotification,
        {notificationHeader,            % = 1, {msg,safsNtfNotificationHeader}
         sourceIndicator,               % = 2, {enum,safsNtfSourceIndicator}
         changedStates                  % = 3, [{msg,safsNtfStateChange}]
        }).

-record(safsNtfAlarmNotification,
        {notificationHeader,            % = 1, {msg,safsNtfNotificationHeader}
         probableCause,                 % = 2, {enum,safsNtfProbableCause}
         specificProblems,              % = 3, [{msg,safsNtfSpecificProblem}]
         perceivedSeverity,             % = 4, {enum,safsNtfSeverity}
         trend,                         % = 5, {enum,safsNtfSeverityTrend}
         thresholdInformation,          % = 6, {msg,safsNtfThresholdInformation} (optional)
         monitoredAttributes,           % = 7, [{msg,safsNtfAttribute}]
         proposedRepairActions          % = 8, [{msg,safsNtfProposedRepairAction}]
        }).

-record(safsNtfSecurityAlarmNotification,
        {notificationHeader,            % = 1, {msg,safsNtfNotificationHeader}
         probableCause,                 % = 2, {enum,safsNtfProbableCause}
         severity,                      % = 3, {enum,safsNtfSeverity}
         securityAlarmDetector,         % = 4, {msg,safsNtfSecurityAlarmDetector}
         serviceUser,                   % = 5, {msg,safsNtfServiceUser}
         serviceProvider                % = 6, {msg,safsNtfServiceUser}
        }).

-record(safsNtfNotificationFilterHeader,
        {eventTypes,                    % = 1, [{enum,safsNtfEventType}]
         notificationObjects,           % = 2, [string]
         notifyingObjects,              % = 3, [string]
         notificationClassIds           % = 4, [{msg,safsNtfClassId}]
        }).

-record(safsNtfObjectCreateDeleteNotificationFilter,
        {notificationFilterHeader,      % = 1, {msg,safsNtfNotificationFilterHeader}
         sourceIndicators               % = 2, [{enum,safsNtfSourceIndicator}]
        }).

-record(safsNtfAttributeChangeNotificationFilter,
        {notificationFilterHeader,      % = 1, {msg,safsNtfNotificationFilterHeader}
         sourceIndicators               % = 2, [{enum,safsNtfSourceIndicator}]
        }).

-record(safsNtfStateChangeNotificationFilter,
        {notificationFilterHeader,      % = 1, {msg,safsNtfNotificationFilterHeader}
         sourceIndicators,              % = 2, [{enum,safsNtfSourceIndicator}]
         changedStates                  % = 3, [{msg,safsNtfStateChange}]
        }).

-record(safsNtfAlarmNotificationFilter,
        {notificationFilterHeader,      % = 1, {msg,safsNtfNotificationFilterHeader}
         probableCauses,                % = 2, [{enum,safsNtfProbableCause}]
         perceivedSeverities,           % = 3, [{enum,safsNtfSeverity}]
         trends                         % = 4, [{enum,safsNtfSeverityTrend}]
        }).

-record(safsNtfSecurityAlarmNotificationFilter,
        {notificationFilterHeader,      % = 1, {msg,safsNtfNotificationFilterHeader}
         probableCauses,                % = 2, [{enum,safsNtfProbableCause}]
         severities,                    % = 3, [{enum,safsNtfSeverity}]
         securityAlarmDetectors,        % = 4, [{msg,safsNtfSecurityAlarmDetector}]
         serviceUsers,                  % = 5, [{msg,safsNtfServiceUser}]
         serviceProviders               % = 6, [{msg,safsNtfServiceUser}]
        }).

-record(safsNtfSearchCriteria,
        {searchMode,                    % = 1, {enum,safsNtfSearchMode}
         eventTime,                     % = 2, int64
         notificationId                 % = 3, uint64
        }).

-record(safsNtfNotificationTypeFilters,
        {objectCreateDeleteNotificationFilter, % = 1, {msg,safsNtfObjectCreateDeleteNotificationFilter} (optional)
         attributeChangeNotificationFilter, % = 2, {msg,safsNtfAttributeChangeNotificationFilter} (optional)
         stateChangeNotificationFilter, % = 3, {msg,safsNtfStateChangeNotificationFilter} (optional)
         alarmNotificationFilter,       % = 4, {msg,safsNtfAlarmNotificationFilter} (optional)
         securityAlarmNotificationFilter % = 5, {msg,safsNtfSecurityAlarmNotificationFilter} (optional)
        }).

-record(safsNtfNotification,
        {objectCreateDeleteNotification, % = 1, {msg,safsNtfObjectCreateDeleteNotification} (optional)
         attributeChangeNotification,   % = 2, {msg,safsNtfAttributeChangeNotification} (optional)
         stateChangeNotification,       % = 3, {msg,safsNtfStateChangeNotification} (optional)
         alarmNotification,             % = 4, {msg,safsNtfAlarmNotification} (optional)
         securityAlarmNotification      % = 5, {msg,safsNtfSecurityAlarmNotification} (optional)
        }).

-record(saNtfNotificationCallback,
        {subscriptionId,                % = 1, uint32
         notification                   % = 2, {msg,safsNtfNotification}
        }).

-record(saNtfNotificationDiscardedCallback,
        {subscriptionId,                % = 1, uint32
         notificationType,              % = 2, {enum,safsNtfNotificationType}
         discardedNotificationIdentifiers % = 3, [uint64]
        }).

-record(safsNtfInitialize,
        {callbacks,                     % = 1, {msg,safsNtfCallbacks} (optional)
         version                        % = 2, {msg,safsVersion} (optional)
        }).

-record(safsNtfFinalize,
        {handle                         % = 1, uint64
        }).

-record(safsNtfNotificationSend,
        {handle,                        % = 1, uint64
         notification                   % = 2, {msg,safsNtfNotification}
        }).

-record(safsNtfNotificationSubscribe,
        {handle,                        % = 1, uint64
         notificationTypeFilters,       % = 2, {msg,safsNtfNotificationTypeFilters}
         subscriptionId                 % = 3, uint32
        }).

-record(safsNtfNotificationUnsubscribe,
        {handle,                        % = 1, uint64
         subscriptionId                 % = 2, uint32
        }).

-record(safsNtfNotificationReadInitialize,
        {handle,                        % = 1, uint64
         searchCriteria,                % = 2, {msg,safsNtfSearchCriteria}
         notificationTypeFilters        % = 3, {msg,safsNtfNotificationTypeFilters}
        }).

-record(safsNtfNotificationReadNext,
        {readHandle,                    % = 1, uint64
         searchDirection                % = 2, {enum,safsNtfSearchDirection}
        }).

-record(safsNtfNotificationReadFinalize,
        {readHandle                     % = 1, uint64
        }).

-record(safsNtfCallbacksInitialize,
        {handle                         % = 1, uint64
        }).

-record(safsNtfMessage,
        {initialize,                    % = 1, {msg,safsNtfInitialize} (optional)
         finalize,                      % = 2, {msg,safsNtfFinalize} (optional)
         notificationSend,              % = 3, {msg,safsNtfNotificationSend} (optional)
         notificationSubscribe,         % = 4, {msg,safsNtfNotificationSubscribe} (optional)
         notificationUnsubscribe,       % = 5, {msg,safsNtfNotificationUnsubscribe} (optional)
         notificationReadInitialize,    % = 6, {msg,safsNtfNotificationReadInitialize} (optional)
         notificationReadNext,          % = 7, {msg,safsNtfNotificationReadNext} (optional)
         notificationReadFinalize,      % = 8, {msg,safsNtfNotificationReadFinalize} (optional)
         callbacksInitialize            % = 9, {msg,safsNtfCallbacksInitialize} (optional)
        }).

-record('SaNtfCallbacks',
        {notificationCallback,          % = 1, {msg,saNtfNotificationCallback} (optional)
         notificationDiscardedCallback  % = 2, {msg,saNtfNotificationDiscardedCallback} (optional)
        }).

-record(safsNtfInitializeRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         handle,                        % = 2, uint64
         version                        % = 3, {msg,safsVersion}
        }).

-record(safsNtfFinalizeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsNtfNotificationSendRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         identifier                     % = 2, uint64 (optional)
        }).

-record(safsNtfNotificationSubscribeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsNtfNotificationUnsubscribeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsNtfNotificationReadInitializeRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         readHandle                     % = 2, uint64 (optional)
        }).

-record(safsNtfNotificationReadNextRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         notification                   % = 2, {msg,safsNtfNotification} (optional)
        }).

-record(safsNtfNotificationReadFinalizeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsNtfCallbacksInitializeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmAttrValue,
        {saint32,                       % = 1, int32 (optional)
         sauint32,                      % = 2, uint32 (optional)
         saint64,                       % = 3, int64 (optional)
         sauint64,                      % = 4, uint64 (optional)
         satime,                        % = 5, uint64 (optional)
         saname,                        % = 6, string (optional)
         safloat,                       % = 7, float (optional)
         sadouble,                      % = 8, double (optional)
         sastring,                      % = 9, string (optional)
         saany,                         % = 10, bytes (optional)
         csstruct                       % = 9999, {msg,safsImmCsStruct} (optional)
        }).

-record(safsImmCsStruct,
        {structName,                    % = 1, string
         structMembers                  % = 2, [{msg,safsImmAttrValues_2}]
        }).

-record(safsImmAttrDefinition_2,
        {attrName,                      % = 1, string
         attrValueType,                 % = 2, {enum,safsImmValueType}
         attrFlags,                     % = 3, uint64
         attrDefaultValue               % = 4, {msg,safsImmAttrValue} (optional)
        }).

-record(safsImmAttrValues_2,
        {attrName,                      % = 1, string
         attrValueType,                 % = 2, {enum,safsImmValueType}
         attrValuesNumber,              % = 3, uint32
         attrValues                     % = 4, [{msg,safsImmAttrValue}]
        }).

-record(safsImmAttrModification_2,
        {modType,                       % = 1, {enum,safsImmAttrModificationType}
         modAttr                        % = 2, {msg,safsImmAttrValues_2}
        }).

-record(safsImmSearchOneAttr_2,
        {attrName,                      % = 1, string
         attrValueType,                 % = 2, {enum,safsImmValueType}
         attrValue                      % = 3, {msg,safsImmAttrValue} (optional)
        }).

-record(safsImmSearchParameters_2,
        {searchOneAttr                  % = 1, {msg,safsImmSearchOneAttr_2}
        }).

-record(safsImmSearchObjects_s2,
        {objectName,                    % = 1, string
         attributes                     % = 2, [{msg,safsImmAttrValues_2}]
        }).

-record(safsImmAdminOperationParams_2,
        {paramName,                     % = 1, string
         paramType,                     % = 2, {enum,safsImmValueType}
         paramBuffer                    % = 3, {msg,safsImmAttrValue}
        }).

-record(safsImmCallbacks,
        {saImmOmAdminOperationInvokeCallback % = 1, bool
        }).

-record(safsImmCallbacks_o2,
        {saImmOmAdminOperationInvokeCallback % = 1, bool
        }).

-record(safsImmOmInitialize,
        {callerPid,                     % = 1, uint64
         callbacks,                     % = 2, {msg,safsImmCallbacks} (optional)
         version                        % = 3, {msg,safsVersion} (optional)
        }).

-record(safsImmOmInitialize_o2,
        {callerPid,                     % = 1, uint64
         callbacks,                     % = 2, {msg,safsImmCallbacks_o2} (optional)
         version                        % = 3, {msg,safsVersion} (optional)
        }).

-record(safsImmOmFinalize,
        {handle                         % = 1, uint64
        }).

-record(safsImmOmClassCreate_2,
        {handle,                        % = 1, uint64
         className,                     % = 2, string
         classCategory,                 % = 3, {enum,safsImmClassCategory}
         attrDefinitions                % = 4, [{msg,safsImmAttrDefinition_2}]
        }).

-record(safsImmOmClassDescriptionGet_2,
        {handle,                        % = 1, uint64
         className                      % = 2, string
        }).

-record(safsImmOmClassDelete,
        {handle,                        % = 1, uint64
         className                      % = 2, string
        }).

-record(safsImmOmSearchInitialize_2,
        {handle,                        % = 1, uint64
         rootName,                      % = 2, string (optional)
         scope,                         % = 3, {enum,safsImmScope}
         searchOptions,                 % = 4, uint64
         searchParam,                   % = 5, {msg,safsImmSearchParameters_2} (optional)
         attributeNames                 % = 6, [string]
        }).

-record(safsImmOmSearchClassInitialize_s2,
        {handle,                        % = 1, uint64
         rootName,                      % = 2, string (optional)
         scope,                         % = 3, {enum,safsImmScope}
         searchOptions,                 % = 4, uint64
         classNames,                    % = 5, [string]
         attributeNames                 % = 6, [string]
        }).

-record(safsImmOmSearchNext_2,
        {searchHandle                   % = 1, uint64
        }).

-record(safsImmOmSearchNextN_s2,
        {searchHandle,                  % = 1, uint64
         numberOfObjects                % = 2, uint32
        }).

-record(safsImmOmSearchFinalize,
        {searchHandle                   % = 1, uint64
        }).

-record(safsImmOmAccessorInitialize,
        {handle                         % = 1, uint64
        }).

-record(safsImmOmAccessorGet_2,
        {accessorHandle,                % = 1, uint64
         objectName,                    % = 2, string
         attributeNames                 % = 3, [string]
        }).

-record(safsImmOmAccessorFinalize,
        {accessorHandle                 % = 1, uint64
        }).

-record(safsImmOmAdminOwnerInitialize,
        {handle,                        % = 1, uint64
         adminOwnerName,                % = 2, string
         releaseOwnershipOnFinalize     % = 3, bool
        }).

-record(safsImmOmAdminOwnerSet,
        {ownerHandle,                   % = 1, uint64
         objectNames,                   % = 2, [string]
         scope                          % = 3, {enum,safsImmScope}
        }).

-record(safsImmOmAdminOwnerRelease,
        {ownerHandle,                   % = 1, uint64
         objectNames,                   % = 2, [string]
         scope                          % = 3, {enum,safsImmScope}
        }).

-record(safsImmOmAdminOwnerFinalize,
        {ownerHandle                    % = 1, uint64
        }).

-record(safsImmOmAdminOwnerClear,
        {handle,                        % = 1, uint64
         objectNames,                   % = 2, [string]
         scope                          % = 3, {enum,safsImmScope}
        }).

-record(safsImmOmCcbInitialize,
        {ownerHandle,                   % = 1, uint64
         ccbFlags                       % = 2, uint64
        }).

-record(safsImmOmCcbObjectCreate_2,
        {handle,                        % = 1, uint64
         className,                     % = 2, string
         parentName,                    % = 3, string (optional)
         attrValues                     % = 4, [{msg,safsImmAttrValues_2}]
        }).

-record(safsImmOmCcbObjectDelete,
        {handle,                        % = 1, uint64
         objectName                     % = 2, string
        }).

-record(safsImmOmCcbObjectModify_2,
        {handle,                        % = 1, uint64
         objectName,                    % = 2, string
         attrMods                       % = 3, [{msg,safsImmAttrModification_2}]
        }).

-record(safsImmOmCcbApply,
        {handle                         % = 1, uint64
        }).

-record(safsImmOmCcbValidate,
        {handle                         % = 1, uint64
        }).

-record(safsImmOmCcbAbort,
        {handle                         % = 1, uint64
        }).

-record(safsImmOmCcbFinalize,
        {handle                         % = 1, uint64
        }).

-record(safsImmOmAdminOperationInvoke_2,
        {ownerHandle,                   % = 1, uint64
         objectName,                    % = 2, string
         continuationId,                % = 3, uint64
         operationId,                   % = 4, uint64
         params,                        % = 5, [{msg,safsImmAdminOperationParams_2}]
         timeout                        % = 6, uint64
        }).

-record(safsImmOmAdminOperationInvoke_o2,
        {ownerHandle,                   % = 1, uint64
         objectName,                    % = 2, string
         continuationId,                % = 3, uint64
         operationId,                   % = 4, uint64
         params,                        % = 5, [{msg,safsImmAdminOperationParams_2}]
         timeout                        % = 6, uint64
        }).

-record(safsImmOmAdminOperationInvokeAsync_2,
        {ownerHandle,                   % = 1, uint64
         invocation,                    % = 2, uint64
         objectName,                    % = 3, string
         continuationId,                % = 4, uint64
         operationId,                   % = 5, uint64
         params                         % = 6, [{msg,safsImmAdminOperationParams_2}]
        }).

-record(safsImmOmAdminOperationContinue,
        {ownerHandle,                   % = 1, uint64
         objectName,                    % = 2, string
         continuationId,                % = 3, uint64
         operationReturnValue           % = 4, {enum,safsAisError} (optional)
        }).

-record(safsImmOmAdminOperationContinueAsync,
        {ownerHandle,                   % = 1, uint64
         objectName,                    % = 2, string
         continuationId,                % = 3, uint64
         operationReturnValue           % = 4, {enum,safsAisError} (optional)
        }).

-record(safsImmOmAdminOperationContinuationClear,
        {ownerHandle,                   % = 1, uint64
         objectName,                    % = 2, string
         continuationId                 % = 3, uint64
        }).

-record(saImmOmAdminOperationInvokeCallback,
        {handle,                        % = 1, uint64
         invocation,                    % = 2, uint64
         operationReturnValue,          % = 3, {enum,safsAisError}
         error                          % = 4, {enum,safsAisError}
        }).

-record(saImmOmAdminOperationInvokeCallback_o2,
        {handle,                        % = 1, uint64
         invocation,                    % = 2, uint64
         operationReturnValue,          % = 3, {enum,safsAisError}
         error,                         % = 4, {enum,safsAisError}
         returnParams                   % = 5, [{msg,safsImmAdminOperationParams_2}]
        }).

-record(saImmOmAdminOperationMemoryFree,
        {ownerHandle,                   % = 1, uint64
         returnParams                   % = 2, [{msg,safsImmAdminOperationParams_2}]
        }).

-record(safsImmOmCallbacksInitialize,
        {handle                         % = 1, uint64
        }).

-record(safsImmOmCcbGetErrorStrings,
        {handle                         % = 1, uint64
        }).

-record(safsImmOmCcbObjectRead,
        {handle,                        % = 1, uint64
         objectName,                    % = 2, string
         attributeNames                 % = 3, [string]
        }).

-record(safsImmOmMessage,
        {initialize,                    % = 1, {msg,safsImmOmInitialize} (optional)
         finalize,                      % = 2, {msg,safsImmOmFinalize} (optional)
         classCreate_2,                 % = 3, {msg,safsImmOmClassCreate_2} (optional)
         classDescriptionGet_2,         % = 4, {msg,safsImmOmClassDescriptionGet_2} (optional)
         classDelete,                   % = 5, {msg,safsImmOmClassDelete} (optional)
         searchInitialize_2,            % = 6, {msg,safsImmOmSearchInitialize_2} (optional)
         searchNext_2,                  % = 7, {msg,safsImmOmSearchNext_2} (optional)
         searchFinalize,                % = 8, {msg,safsImmOmSearchFinalize} (optional)
         accessorInitialize,            % = 9, {msg,safsImmOmAccessorInitialize} (optional)
         accessorGet_2,                 % = 10, {msg,safsImmOmAccessorGet_2} (optional)
         accessorFinalize,              % = 11, {msg,safsImmOmAccessorFinalize} (optional)
         adminOwnerInitialize,          % = 12, {msg,safsImmOmAdminOwnerInitialize} (optional)
         adminOwnerSet,                 % = 13, {msg,safsImmOmAdminOwnerSet} (optional)
         adminOwnerRelease,             % = 14, {msg,safsImmOmAdminOwnerRelease} (optional)
         adminOwnerFinalize,            % = 15, {msg,safsImmOmAdminOwnerFinalize} (optional)
         adminOwnerClear,               % = 16, {msg,safsImmOmAdminOwnerClear} (optional)
         ccbInitialize,                 % = 17, {msg,safsImmOmCcbInitialize} (optional)
         ccbObjectCreate_2,             % = 18, {msg,safsImmOmCcbObjectCreate_2} (optional)
         ccbObjectDelete,               % = 19, {msg,safsImmOmCcbObjectDelete} (optional)
         ccbObjectModify_2,             % = 20, {msg,safsImmOmCcbObjectModify_2} (optional)
         ccbApply,                      % = 21, {msg,safsImmOmCcbApply} (optional)
         ccbFinalize,                   % = 22, {msg,safsImmOmCcbFinalize} (optional)
         adminOperationInvoke_2,        % = 23, {msg,safsImmOmAdminOperationInvoke_2} (optional)
         adminOperationInvokeAsync_2,   % = 24, {msg,safsImmOmAdminOperationInvokeAsync_2} (optional)
         adminOperationContinue,        % = 25, {msg,safsImmOmAdminOperationContinue} (optional)
         adminOperationContinueAsync,   % = 26, {msg,safsImmOmAdminOperationContinueAsync} (optional)
         adminOperationContinuationClear, % = 27, {msg,safsImmOmAdminOperationContinuationClear} (optional)
         callbacksInitialize,           % = 28, {msg,safsImmOmCallbacksInitialize} (optional)
         initialize_o2,                 % = 29, {msg,safsImmOmInitialize_o2} (optional)
         adminOperationInvoke_o2,       % = 30, {msg,safsImmOmAdminOperationInvoke_o2} (optional)
         adminOperationMemoryFree,      % = 31, {msg,saImmOmAdminOperationMemoryFree} (optional)
         ccbGetErrorStrings,            % = 32, {msg,safsImmOmCcbGetErrorStrings} (optional)
         ccbObjectRead,                 % = 34, {msg,safsImmOmCcbObjectRead} (optional)
         ccbValidate,                   % = 35, {msg,safsImmOmCcbValidate} (optional)
         ccbAbort,                      % = 36, {msg,safsImmOmCcbAbort} (optional)
         searchNextN_s2,                % = 37, {msg,safsImmOmSearchNextN_s2} (optional)
         searchClassInitialize_s2       % = 38, {msg,safsImmOmSearchClassInitialize_s2} (optional)
        }).

-record('SaImmCallbacks',
        {adminOperationInvokeCallback,  % = 1, {msg,saImmOmAdminOperationInvokeCallback} (optional)
         adminOperationInvokeCallback_o2 % = 2, {msg,saImmOmAdminOperationInvokeCallback_o2} (optional)
        }).

-record(safsImmOmInitializeRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         handle,                        % = 2, uint64
         version                        % = 3, {msg,safsVersion}
        }).

-record(safsImmOmFinalizeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmClassCreate2Ret,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmClassDescriptionGet2Ret,
        {returnVal,                     % = 1, {enum,safsAisError}
         classCategory,                 % = 2, {enum,safsImmClassCategory} (optional)
         attrDefinitions                % = 3, [{msg,safsImmAttrDefinition_2}]
        }).

-record(safsImmOmClassDeleteRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmSearchInitialize2Ret,
        {returnVal,                     % = 1, {enum,safsAisError}
         handle                         % = 2, uint64
        }).

-record(safsImmOmSearchClassInitializeS2Ret,
        {returnVal,                     % = 1, {enum,safsAisError}
         handle                         % = 2, uint64
        }).

-record(safsImmOmSearchNext2Ret,
        {returnVal,                     % = 1, {enum,safsAisError}
         objectName,                    % = 2, string (optional)
         attributes                     % = 3, [{msg,safsImmAttrValues_2}]
        }).

-record(safsImmOmSearchNextNS2Ret,
        {returnVal,                     % = 1, {enum,safsAisError}
         searchObjects                  % = 2, [{msg,safsImmSearchObjects_s2}]
        }).

-record(safsImmOmSearchFinalizeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAccessorInitializeRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         handle                         % = 2, uint64
        }).

-record(safsImmOmAccessorGet2Ret,
        {returnVal,                     % = 1, {enum,safsAisError}
         attributes                     % = 2, [{msg,safsImmAttrValues_2}]
        }).

-record(safsImmOmAccessorFinalizeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAdminOwnerInitializeRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         handle                         % = 2, uint64
        }).

-record(safsImmOmAdminOwnerSetRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAdminOwnerReleaseRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAdminOwnerFinalizeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAdminOwnerClearRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCcbInitializeRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         handle                         % = 2, uint32
        }).

-record(safsImmOmCcbObjectCreate2Ret,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCcbObjectDeleteRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCcbObjectModify2Ret,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCcbApplyRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCcbValidateRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCcbAbortRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCcbFinalizeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAdminOperationInvoke2Ret,
        {returnVal,                     % = 1, {enum,safsAisError}
         operationReturnValue           % = 2, {enum,safsAisError} (optional)
        }).

-record(safsImmOmAdminOperationInvokeO2Ret,
        {returnVal,                     % = 1, {enum,safsAisError}
         operationReturnValue,          % = 2, {enum,safsAisError} (optional)
         returnParams                   % = 3, [{msg,safsImmAdminOperationParams_2}]
        }).

-record(safsImmOmAdminOperationInvokeAsync2Ret,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAdminOperationContinueRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAdminOperationContinueAsyncRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAdminOperationClearRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCallbacksInitializeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCallbacksRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCcbGetErrorStringsRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         errorStrings                   % = 2, [string]
        }).

-record(safsImmOmCcbObjectReadRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         attributes                     % = 2, [{msg,safsImmAttrValues_2}]
        }).

-endif.
