%% Automatically generated, do not edit
%% Generated by gpb_compile version 2.0 Src: om.proto@@/main/R2A/R4A/R5A/R6A/1

-ifndef(om).
-define(om, true).

-define(om_gpb_version, "2.0").

-record(safsImmAttrValue,
        {saint32,                       % = 1, int32 (optional)
         sauint32,                      % = 2, uint32 (optional)
         saint64,                       % = 3, int64 (optional)
         sauint64,                      % = 4, uint64 (optional)
         satime,                        % = 5, uint64 (optional)
         saname,                        % = 6, string (optional)
         safloat,                       % = 7, float (optional)
         sadouble,                      % = 8, double (optional)
         sastring,                      % = 9, string (optional)
         saany,                         % = 10, bytes (optional)
         csstruct                       % = 9999, {msg,safsImmCsStruct} (optional)
        }).

-record(safsImmCsStruct,
        {structName,                    % = 1, string
         structMembers                  % = 2, [{msg,safsImmAttrValues_2}]
        }).

-record(safsImmAttrDefinition_2,
        {attrName,                      % = 1, string
         attrValueType,                 % = 2, {enum,safsImmValueType}
         attrFlags,                     % = 3, uint64
         attrDefaultValue               % = 4, {msg,safsImmAttrValue} (optional)
        }).

-record(safsImmAttrValues_2,
        {attrName,                      % = 1, string
         attrValueType,                 % = 2, {enum,safsImmValueType}
         attrValuesNumber,              % = 3, uint32
         attrValues                     % = 4, [{msg,safsImmAttrValue}]
        }).

-record(safsImmAttrModification_2,
        {modType,                       % = 1, {enum,safsImmAttrModificationType}
         modAttr                        % = 2, {msg,safsImmAttrValues_2}
        }).

-record(safsImmSearchOneAttr_2,
        {attrName,                      % = 1, string
         attrValueType,                 % = 2, {enum,safsImmValueType}
         attrValue                      % = 3, {msg,safsImmAttrValue} (optional)
        }).

-record(safsImmSearchParameters_2,
        {searchOneAttr                  % = 1, {msg,safsImmSearchOneAttr_2}
        }).

-record(safsImmSearchObjects_s2,
        {objectName,                    % = 1, string
         attributes                     % = 2, [{msg,safsImmAttrValues_2}]
        }).

-record(safsImmAdminOperationParams_2,
        {paramName,                     % = 1, string
         paramType,                     % = 2, {enum,safsImmValueType}
         paramBuffer                    % = 3, {msg,safsImmAttrValue}
        }).

-record(safsImmCallbacks,
        {saImmOmAdminOperationInvokeCallback % = 1, bool
        }).

-record(safsImmCallbacks_o2,
        {saImmOmAdminOperationInvokeCallback % = 1, bool
        }).

-record(safsImmOmInitialize,
        {callerPid,                     % = 1, uint64
         callbacks,                     % = 2, {msg,safsImmCallbacks} (optional)
         version                        % = 3, {msg,safsVersion} (optional)
        }).

-record(safsImmOmInitialize_o2,
        {callerPid,                     % = 1, uint64
         callbacks,                     % = 2, {msg,safsImmCallbacks_o2} (optional)
         version                        % = 3, {msg,safsVersion} (optional)
        }).

-record(safsImmOmFinalize,
        {handle                         % = 1, uint64
        }).

-record(safsImmOmClassCreate_2,
        {handle,                        % = 1, uint64
         className,                     % = 2, string
         classCategory,                 % = 3, {enum,safsImmClassCategory}
         attrDefinitions                % = 4, [{msg,safsImmAttrDefinition_2}]
        }).

-record(safsImmOmClassDescriptionGet_2,
        {handle,                        % = 1, uint64
         className                      % = 2, string
        }).

-record(safsImmOmClassDelete,
        {handle,                        % = 1, uint64
         className                      % = 2, string
        }).

-record(safsImmOmSearchInitialize_2,
        {handle,                        % = 1, uint64
         rootName,                      % = 2, string (optional)
         scope,                         % = 3, {enum,safsImmScope}
         searchOptions,                 % = 4, uint64
         searchParam,                   % = 5, {msg,safsImmSearchParameters_2} (optional)
         attributeNames                 % = 6, [string]
        }).

-record(safsImmOmSearchClassInitialize_s2,
        {handle,                        % = 1, uint64
         rootName,                      % = 2, string (optional)
         scope,                         % = 3, {enum,safsImmScope}
         searchOptions,                 % = 4, uint64
         classNames,                    % = 5, [string]
         attributeNames                 % = 6, [string]
        }).

-record(safsImmOmSearchNext_2,
        {searchHandle                   % = 1, uint64
        }).

-record(safsImmOmSearchNextN_s2,
        {searchHandle,                  % = 1, uint64
         numberOfObjects                % = 2, uint32
        }).

-record(safsImmOmSearchFinalize,
        {searchHandle                   % = 1, uint64
        }).

-record(safsImmOmAccessorInitialize,
        {handle                         % = 1, uint64
        }).

-record(safsImmOmAccessorGet_2,
        {accessorHandle,                % = 1, uint64
         objectName,                    % = 2, string
         attributeNames                 % = 3, [string]
        }).

-record(safsImmOmAccessorFinalize,
        {accessorHandle                 % = 1, uint64
        }).

-record(safsImmOmAdminOwnerInitialize,
        {handle,                        % = 1, uint64
         adminOwnerName,                % = 2, string
         releaseOwnershipOnFinalize     % = 3, bool
        }).

-record(safsImmOmAdminOwnerSet,
        {ownerHandle,                   % = 1, uint64
         objectNames,                   % = 2, [string]
         scope                          % = 3, {enum,safsImmScope}
        }).

-record(safsImmOmAdminOwnerRelease,
        {ownerHandle,                   % = 1, uint64
         objectNames,                   % = 2, [string]
         scope                          % = 3, {enum,safsImmScope}
        }).

-record(safsImmOmAdminOwnerFinalize,
        {ownerHandle                    % = 1, uint64
        }).

-record(safsImmOmAdminOwnerClear,
        {handle,                        % = 1, uint64
         objectNames,                   % = 2, [string]
         scope                          % = 3, {enum,safsImmScope}
        }).

-record(safsImmOmCcbInitialize,
        {ownerHandle,                   % = 1, uint64
         ccbFlags                       % = 2, uint64
        }).

-record(safsImmOmCcbObjectCreate_2,
        {handle,                        % = 1, uint64
         className,                     % = 2, string
         parentName,                    % = 3, string (optional)
         attrValues                     % = 4, [{msg,safsImmAttrValues_2}]
        }).

-record(safsImmOmCcbObjectDelete,
        {handle,                        % = 1, uint64
         objectName                     % = 2, string
        }).

-record(safsImmOmCcbObjectModify_2,
        {handle,                        % = 1, uint64
         objectName,                    % = 2, string
         attrMods                       % = 3, [{msg,safsImmAttrModification_2}]
        }).

-record(safsImmOmCcbApply,
        {handle                         % = 1, uint64
        }).

-record(safsImmOmCcbValidate,
        {handle                         % = 1, uint64
        }).

-record(safsImmOmCcbAbort,
        {handle                         % = 1, uint64
        }).

-record(safsImmOmCcbFinalize,
        {handle                         % = 1, uint64
        }).

-record(safsImmOmAdminOperationInvoke_2,
        {ownerHandle,                   % = 1, uint64
         objectName,                    % = 2, string
         continuationId,                % = 3, uint64
         operationId,                   % = 4, uint64
         params,                        % = 5, [{msg,safsImmAdminOperationParams_2}]
         timeout                        % = 6, uint64
        }).

-record(safsImmOmAdminOperationInvoke_o2,
        {ownerHandle,                   % = 1, uint64
         objectName,                    % = 2, string
         continuationId,                % = 3, uint64
         operationId,                   % = 4, uint64
         params,                        % = 5, [{msg,safsImmAdminOperationParams_2}]
         timeout                        % = 6, uint64
        }).

-record(safsImmOmAdminOperationInvokeAsync_2,
        {ownerHandle,                   % = 1, uint64
         invocation,                    % = 2, uint64
         objectName,                    % = 3, string
         continuationId,                % = 4, uint64
         operationId,                   % = 5, uint64
         params                         % = 6, [{msg,safsImmAdminOperationParams_2}]
        }).

-record(safsImmOmAdminOperationContinue,
        {ownerHandle,                   % = 1, uint64
         objectName,                    % = 2, string
         continuationId,                % = 3, uint64
         operationReturnValue           % = 4, {enum,safsAisError} (optional)
        }).

-record(safsImmOmAdminOperationContinueAsync,
        {ownerHandle,                   % = 1, uint64
         objectName,                    % = 2, string
         continuationId,                % = 3, uint64
         operationReturnValue           % = 4, {enum,safsAisError} (optional)
        }).

-record(safsImmOmAdminOperationContinuationClear,
        {ownerHandle,                   % = 1, uint64
         objectName,                    % = 2, string
         continuationId                 % = 3, uint64
        }).

-record(saImmOmAdminOperationInvokeCallback,
        {handle,                        % = 1, uint64
         invocation,                    % = 2, uint64
         operationReturnValue,          % = 3, {enum,safsAisError}
         error                          % = 4, {enum,safsAisError}
        }).

-record(saImmOmAdminOperationInvokeCallback_o2,
        {handle,                        % = 1, uint64
         invocation,                    % = 2, uint64
         operationReturnValue,          % = 3, {enum,safsAisError}
         error,                         % = 4, {enum,safsAisError}
         returnParams                   % = 5, [{msg,safsImmAdminOperationParams_2}]
        }).

-record(saImmOmAdminOperationMemoryFree,
        {ownerHandle,                   % = 1, uint64
         returnParams                   % = 2, [{msg,safsImmAdminOperationParams_2}]
        }).

-record(safsImmOmCallbacksInitialize,
        {handle                         % = 1, uint64
        }).

-record(safsImmOmCcbGetErrorStrings,
        {handle                         % = 1, uint64
        }).

-record(safsImmOmCcbObjectRead,
        {handle,                        % = 1, uint64
         objectName,                    % = 2, string
         attributeNames                 % = 3, [string]
        }).

-record(safsImmOmMessage,
        {initialize,                    % = 1, {msg,safsImmOmInitialize} (optional)
         finalize,                      % = 2, {msg,safsImmOmFinalize} (optional)
         classCreate_2,                 % = 3, {msg,safsImmOmClassCreate_2} (optional)
         classDescriptionGet_2,         % = 4, {msg,safsImmOmClassDescriptionGet_2} (optional)
         classDelete,                   % = 5, {msg,safsImmOmClassDelete} (optional)
         searchInitialize_2,            % = 6, {msg,safsImmOmSearchInitialize_2} (optional)
         searchNext_2,                  % = 7, {msg,safsImmOmSearchNext_2} (optional)
         searchFinalize,                % = 8, {msg,safsImmOmSearchFinalize} (optional)
         accessorInitialize,            % = 9, {msg,safsImmOmAccessorInitialize} (optional)
         accessorGet_2,                 % = 10, {msg,safsImmOmAccessorGet_2} (optional)
         accessorFinalize,              % = 11, {msg,safsImmOmAccessorFinalize} (optional)
         adminOwnerInitialize,          % = 12, {msg,safsImmOmAdminOwnerInitialize} (optional)
         adminOwnerSet,                 % = 13, {msg,safsImmOmAdminOwnerSet} (optional)
         adminOwnerRelease,             % = 14, {msg,safsImmOmAdminOwnerRelease} (optional)
         adminOwnerFinalize,            % = 15, {msg,safsImmOmAdminOwnerFinalize} (optional)
         adminOwnerClear,               % = 16, {msg,safsImmOmAdminOwnerClear} (optional)
         ccbInitialize,                 % = 17, {msg,safsImmOmCcbInitialize} (optional)
         ccbObjectCreate_2,             % = 18, {msg,safsImmOmCcbObjectCreate_2} (optional)
         ccbObjectDelete,               % = 19, {msg,safsImmOmCcbObjectDelete} (optional)
         ccbObjectModify_2,             % = 20, {msg,safsImmOmCcbObjectModify_2} (optional)
         ccbApply,                      % = 21, {msg,safsImmOmCcbApply} (optional)
         ccbFinalize,                   % = 22, {msg,safsImmOmCcbFinalize} (optional)
         adminOperationInvoke_2,        % = 23, {msg,safsImmOmAdminOperationInvoke_2} (optional)
         adminOperationInvokeAsync_2,   % = 24, {msg,safsImmOmAdminOperationInvokeAsync_2} (optional)
         adminOperationContinue,        % = 25, {msg,safsImmOmAdminOperationContinue} (optional)
         adminOperationContinueAsync,   % = 26, {msg,safsImmOmAdminOperationContinueAsync} (optional)
         adminOperationContinuationClear, % = 27, {msg,safsImmOmAdminOperationContinuationClear} (optional)
         callbacksInitialize,           % = 28, {msg,safsImmOmCallbacksInitialize} (optional)
         initialize_o2,                 % = 29, {msg,safsImmOmInitialize_o2} (optional)
         adminOperationInvoke_o2,       % = 30, {msg,safsImmOmAdminOperationInvoke_o2} (optional)
         adminOperationMemoryFree,      % = 31, {msg,saImmOmAdminOperationMemoryFree} (optional)
         ccbGetErrorStrings,            % = 32, {msg,safsImmOmCcbGetErrorStrings} (optional)
         ccbObjectRead,                 % = 34, {msg,safsImmOmCcbObjectRead} (optional)
         ccbValidate,                   % = 35, {msg,safsImmOmCcbValidate} (optional)
         ccbAbort,                      % = 36, {msg,safsImmOmCcbAbort} (optional)
         searchNextN_s2,                % = 37, {msg,safsImmOmSearchNextN_s2} (optional)
         searchClassInitialize_s2       % = 38, {msg,safsImmOmSearchClassInitialize_s2} (optional)
        }).

-record('SaImmCallbacks',
        {adminOperationInvokeCallback,  % = 1, {msg,saImmOmAdminOperationInvokeCallback} (optional)
         adminOperationInvokeCallback_o2 % = 2, {msg,saImmOmAdminOperationInvokeCallback_o2} (optional)
        }).

-record(safsImmOmInitializeRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         handle,                        % = 2, uint64
         version                        % = 3, {msg,safsVersion}
        }).

-record(safsImmOmFinalizeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmClassCreate2Ret,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmClassDescriptionGet2Ret,
        {returnVal,                     % = 1, {enum,safsAisError}
         classCategory,                 % = 2, {enum,safsImmClassCategory} (optional)
         attrDefinitions                % = 3, [{msg,safsImmAttrDefinition_2}]
        }).

-record(safsImmOmClassDeleteRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmSearchInitialize2Ret,
        {returnVal,                     % = 1, {enum,safsAisError}
         handle                         % = 2, uint64
        }).

-record(safsImmOmSearchClassInitializeS2Ret,
        {returnVal,                     % = 1, {enum,safsAisError}
         handle                         % = 2, uint64
        }).

-record(safsImmOmSearchNext2Ret,
        {returnVal,                     % = 1, {enum,safsAisError}
         objectName,                    % = 2, string (optional)
         attributes                     % = 3, [{msg,safsImmAttrValues_2}]
        }).

-record(safsImmOmSearchNextNS2Ret,
        {returnVal,                     % = 1, {enum,safsAisError}
         searchObjects                  % = 2, [{msg,safsImmSearchObjects_s2}]
        }).

-record(safsImmOmSearchFinalizeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAccessorInitializeRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         handle                         % = 2, uint64
        }).

-record(safsImmOmAccessorGet2Ret,
        {returnVal,                     % = 1, {enum,safsAisError}
         attributes                     % = 2, [{msg,safsImmAttrValues_2}]
        }).

-record(safsImmOmAccessorFinalizeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAdminOwnerInitializeRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         handle                         % = 2, uint64
        }).

-record(safsImmOmAdminOwnerSetRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAdminOwnerReleaseRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAdminOwnerFinalizeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAdminOwnerClearRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCcbInitializeRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         handle                         % = 2, uint32
        }).

-record(safsImmOmCcbObjectCreate2Ret,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCcbObjectDeleteRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCcbObjectModify2Ret,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCcbApplyRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCcbValidateRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCcbAbortRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCcbFinalizeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAdminOperationInvoke2Ret,
        {returnVal,                     % = 1, {enum,safsAisError}
         operationReturnValue           % = 2, {enum,safsAisError} (optional)
        }).

-record(safsImmOmAdminOperationInvokeO2Ret,
        {returnVal,                     % = 1, {enum,safsAisError}
         operationReturnValue,          % = 2, {enum,safsAisError} (optional)
         returnParams                   % = 3, [{msg,safsImmAdminOperationParams_2}]
        }).

-record(safsImmOmAdminOperationInvokeAsync2Ret,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAdminOperationContinueRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAdminOperationContinueAsyncRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmAdminOperationClearRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCallbacksInitializeRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCallbacksRet,
        {returnVal                      % = 1, {enum,safsAisError}
        }).

-record(safsImmOmCcbGetErrorStringsRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         errorStrings                   % = 2, [string]
        }).

-record(safsImmOmCcbObjectReadRet,
        {returnVal,                     % = 1, {enum,safsAisError}
         attributes                     % = 2, [{msg,safsImmAttrValues_2}]
        }).

-record(safsAny,
        {bufferSize,                    % = 1, uint64
         bufferAddr                     % = 2, bytes
        }).

-record(safsVersion,
        {releaseCode,                   % = 1, uint32
         majorVersion,                  % = 2, uint32
         minorVersion                   % = 3, uint32
        }).

-endif.
