%% Automatically generated, do not edit
%% Generated by gpb_compile version 2.0 Src: sa_ais.proto@@/main/R2A/3

-ifndef(sa_ais).
-define(sa_ais, true).

-define(sa_ais_gpb_version, "2.0").

-record(safsAny,
        {bufferSize,                    % = 1, uint64
         bufferAddr                     % = 2, bytes
        }).

-record(safsVersion,
        {releaseCode,                   % = 1, uint32
         majorVersion,                  % = 2, uint32
         minorVersion                   % = 3, uint32
        }).

-endif.
