#!/bin/bash

echo "$0"

## Find out which boardtype
SCRIPTDIR=$(dirname $0);
source $SCRIPTDIR/hwt-util.sh

BOARDTYPE=$(get_boardtype);
echo "$BOARDTYPE";

run_t_cmd(){
        cmd=$1

        echo "------------------------------------------------------------------"
        echo -e "testbox $cmd"
        testbox $cmd
        echo "------------------------------------------------------------------"
}

run_cmd(){
        cmd=$1

        echo "------------------------------------------------------------------"
        echo -e "$cmd"
        $cmd
        echo "------------------------------------------------------------------"
}

prod_test_tcu04()  {

    run_t_cmd "icm_status"
#   run_t_cmd "hw_status"
    run_t_cmd "status"
    run_t_cmd "bpm_pgood_status"
    run_t_cmd "bpm_power_status 0"
    run_t_cmd "icm_load ssp"
    run_t_cmd "i2c_test 7 /dev/i2c-0 1 0x41 2"
    run_t_cmd "icm_load cvp"
    run_t_cmd "i2c_test 7 /dev/i2c-0 1 0x41 2"
    run_t_cmd "icm_rd swri 54"
    run_t_cmd "icm_wr swri 54 0x00"
    run_t_cmd "icm_rd swri 54"
    run_t_cmd "icm_load ssp"
    run_t_cmd "icm_load cvp"
    run_t_cmd "icm_rd swri 54"
    run_t_cmd "icm_status"
    run_t_cmd "npu_load frog"
    run_t_cmd "npucmem_test -C 0 -e 1 -f 1 -m 0 -p 0"
    run_t_cmd "npucmem_test -C 1 -e 1 -f 1 -m 0 -p 0"
    run_t_cmd "npucmem_test -C 0 -e 1 -f 1 -m 0 -p 1"
    run_t_cmd "npucmem_test -C 1 -e 1 -f 1 -m 0 -p 1"

# We do not need to fail if ecc counters != 0
#    run_t_cmd "eccstat --test"
    run_t_cmd "eccstat"

    run_cmd "ncpWrite 0x8.0x9.0x48 0x4"
    run_cmd "ncpWrite 0x8.0x9.0x48 0x5"
    run_cmd "ncpExtMemBist -C 0"
    run_cmd "ncpWrite 0x8.0x9.0x48 0x4"
# Inject ECC double bit error
# Test below should fail (correct behavior)
    run_cmd "ncpWrite 0x8.0x9.0x48 0x7"
    run_cmd "ncpExtMemBist -C 0"
    run_cmd "ncpWrite 0x9.0x9.0x48 0x4"
    run_cmd "ncpWrite 0x9.0x9.0x48 0x5"
    run_cmd "ncpExtMemBist -C 1"
    run_cmd "ncpWrite 0x9.0x9.0x48 0x4"
# Inject ECC double bit error
# Test below should fail (correct behavior)
    run_cmd "ncpWrite 0x9.0x9.0x48 0x7"
    run_cmd "ncpExtMemBist -C 1"

# We do not need to fail if ecc counters != 0
#    run_t_cmd "eccstat --test"
    run_t_cmd "eccstat"
    run_t_cmd "nor_test_rw"
    run_t_cmd "syntamult_read 0x0006"
    run_t_cmd "syntmod_read RBS 0x001"
    run_t_cmd "syntmod_write RBS 0x001 0xf1"
    run_t_cmd "syntmod_read RBS 0x001"
    run_t_cmd "syntmod_write RBS 0x001 0xd"
    run_t_cmd "syntmod_read RBS 0x001"
    run_t_cmd "syntmod_read TN 0x001"
    run_t_cmd "syntmod_write TN 0x001 0xf1"
    run_t_cmd "syntmod_read TN 0x001"
    run_t_cmd "syntmod_write TN 0x001 0xa014"
    run_t_cmd "syntmod_read TN 0x001"
    run_t_cmd "synth_init"
    run_t_cmd "syntaocxo_dump"
    run_t_cmd "syntaocxo_temp_sensor"
    run_t_cmd "syntaocxo_checksum"
    run_t_cmd "generate_freq 9"
    run_t_cmd "--wait --verbose 2 icm_rd tuf 0x0284"
    run_t_cmd "--wait --verbose 2 icm_wr tuf 0x0284 0x0004"
    run_t_cmd "--wait --verbose 2 icm_wr tuf 0x0284 0x00000000"
    run_t_cmd "synth_status"
    run_t_cmd "phy_init"
    run_t_cmd "retimer_init"
    run_t_cmd "led tna on"
    run_t_cmd "led tnb on"
    run_t_cmd "led tnc on"
    run_t_cmd "led tnd on"
    run_t_cmd "led tne on"
    run_t_cmd "led tnf on"
    run_t_cmd "led tng on"
    run_t_cmd "led tnh on"
    run_t_cmd "led tnj on"
    run_t_cmd "led tnk on"
    run_t_cmd "led tnl on"
    run_t_cmd "led tnm on"
    run_t_cmd "led tnn on"
    run_t_cmd "led lmt on"
    run_t_cmd "led eta0 on"
    run_t_cmd "led eta1 on"
    run_t_cmd "led etb0 on"
    run_t_cmd "led etb1 on"
    run_t_cmd "led etc0 on"
    run_t_cmd "led etc1 on"
    run_t_cmd "led etd0 on"
    run_t_cmd "led etd1 on"
    run_t_cmd "led synca on"
    run_t_cmd "led syncb on"
    run_t_cmd "led ec on"
    run_t_cmd "led fault on"
    run_t_cmd "led op on"
    run_t_cmd "led stat on"
    run_t_cmd "led fan on"
    run_t_cmd "led tna off"
    run_t_cmd "led tnb off"
    run_t_cmd "led tnc off"
    run_t_cmd "led tnd off"
    run_t_cmd "led tne off"
    run_t_cmd "led tnf off"
    run_t_cmd "led tng off"
    run_t_cmd "led tnh off"
    run_t_cmd "led tnj off"
    run_t_cmd "led tnk off"
    run_t_cmd "led tnl off"
    run_t_cmd "led tnm off"
    run_t_cmd "led tnn off"
    run_t_cmd "led fan off"
    run_t_cmd "led stat off"
    run_t_cmd "led fault off"
    run_t_cmd "led op off"
    run_t_cmd "led ec off"
    run_t_cmd "led eta0 off"
    run_t_cmd "led eta1 off"
    run_t_cmd "led etb0 off"
    run_t_cmd "led etb1 off"
    run_t_cmd "led etc0 off"
    run_t_cmd "led etc1 off"
    run_t_cmd "led etd0 off"
    run_t_cmd "led etd1 off"
    run_t_cmd "led synca off"
    run_t_cmd "led syncb off"
    run_t_cmd "led lmt off"
    run_t_cmd "phy_rst_test tnk"
    run_t_cmd "phy_rst_test tnl"
    run_t_cmd "phy_rst_test tnm"
    run_t_cmd "phy_rst_test tnn"
    run_t_cmd "phy_ident tnk"
    run_t_cmd "phy_ident tnl"
    run_t_cmd "phy_ident tnm"
    run_t_cmd "phy_ident tnn"
    run_t_cmd "tdm_phy_enable"
    run_t_cmd "tdmphy_write 0 0 0x4e 0x55"
    run_t_cmd "tdmphy_read 0 0 0x4e"
    run_t_cmd "tdmphy_reset 0 0"
    run_t_cmd "tdmphy_read 0 0 0x4e"
    run_t_cmd "tdmphy_write 0 1 0x4e 0x55"
    run_t_cmd "tdmphy_read 0 1 0x4e"
    run_t_cmd "tdmphy_reset 0 1"
    run_t_cmd "tdmphy_read 0 1 0x4e"
    run_t_cmd "tdmphy_write 0 2 0x4e 0x55"
    run_t_cmd "tdmphy_read 0 2 0x4e"
    run_t_cmd "tdmphy_reset 0 2"
    run_t_cmd "tdmphy_read 0 2 0x4e"
    run_t_cmd "tdmphy_write 0 3 0x4e 0x55"
    run_t_cmd "tdmphy_read 0 3 0x4e"
    run_t_cmd "tdmphy_reset 0 3"
    run_t_cmd "tdmphy_read 0 3 0x4e"
    run_t_cmd "tdmphy_write 1 0 0x4e 0x55"
    run_t_cmd "tdmphy_read 1 0 0x4e"
    run_t_cmd "tdmphy_reset 1 0"
    run_t_cmd "tdmphy_read 1 0 0x4e"
    run_t_cmd "tdmphy_write 1 1 0x4e 0x55"
    run_t_cmd "tdmphy_read 1 1 0x4e"
    run_t_cmd "tdmphy_reset 1 1"
    run_t_cmd "tdmphy_read 1 1 0x4e"
    run_t_cmd "tdmphy_write 1 2 0x4e 0x55"
    run_t_cmd "tdmphy_read 1 2 0x4e"
    run_t_cmd "tdmphy_reset 1 2"
    run_t_cmd "tdmphy_read 1 2 0x4e"
    run_t_cmd "tdmphy_write 1 3 0x4e 0x55"
    run_t_cmd "tdmphy_read 1 3 0x4e"
    run_t_cmd "tdmphy_reset 1 3"
    run_t_cmd "tdmphy_read 1 3 0x4e"
    run_t_cmd "tdm_phy_disable"
    run_t_cmd "retimer_read tna 0x000"
    run_t_cmd "retimer_write tna 0x000 0x12"
    run_t_cmd "retimer_read tna 0x000"
    run_t_cmd "retimer_write tna 0x000 0x0"
    run_t_cmd "retimer_read tna 0x000"
    run_t_cmd "retimer_read tnb 0x000"
    run_t_cmd "retimer_write tnb 0x000 0x12"
    run_t_cmd "retimer_read tnb 0x000"
    run_t_cmd "retimer_write tnb 0x000 0x0"
    run_t_cmd "retimer_read tnb 0x000"
    run_t_cmd "retimer_read tnc 0x000"
    run_t_cmd "retimer_write tnc 0x000 0x12"
    run_t_cmd "retimer_read tnc 0x000"
    run_t_cmd "retimer_write tnc 0x000 0x0"
    run_t_cmd "retimer_read tnc 0x000"
    run_t_cmd "retimer_read tnd 0x000"
    run_t_cmd "retimer_write tnd 0x000 0x12"
    run_t_cmd "retimer_read tnd 0x000"
    run_t_cmd "retimer_write tnd 0x000 0x0"
    run_t_cmd "retimer_read tnd 0x000"
    run_t_cmd "retimer_read tne 0x000"
    run_t_cmd "retimer_write tne 0x000 0x12"
    run_t_cmd "retimer_read tne 0x000"
    run_t_cmd "retimer_write tne 0x000 0x0"
    run_t_cmd "retimer_read tne 0x000"
# loop_port not possible to execute without loop plug/cable
#    run_t_cmd "loop_port 9 0x000000a1"
#    run_t_cmd "loop_port 18 0x000000a2"
# do simple verify that command exist...
    run_t_cmd "loop_port -h"
    run_t_cmd "turef_status"
    run_t_cmd "turef_status rbs"
    run_t_cmd "phy_init"
    run_t_cmd "tud_timesync phy"
    run_t_cmd "phy_readhbts tnk"
    run_t_cmd "phy_readhbts tnl"
    run_t_cmd "phy_readhbts tnm"
    run_t_cmd "phy_readhbts tnn"
    run_t_cmd "phy_rdb_read tnk 0xa5a | sed 's/^\(0x\(0\+\|[Ff]\4\ \)\)$/\1 PLL_LOCKED/'"
    run_t_cmd "phy_rdb_read tnk 0xa59 | sed 's/^\(0x\(0*\|[Ff]\3\\ )[0-9a-fA-F]\)$/\1 PLL_LOCKED/'"
    run_t_cmd "phy_rdb_read tnl 0xa5a | sed 's/^\(0x\(0\+\|[Ff]\4\ \)\)$/\1 PLL_LOCKED/'"
    run_t_cmd "phy_rdb_read tnl 0xa59 | sed 's/^\(0x\(0*\|[Ff]\3\\ )[0-9a-fA-F]\)$/\1 PLL_LOCKED/'"
    run_t_cmd "phy_rdb_read tnm 0xa5a | sed 's/^\(0x\(0\+\|[Ff]\4\ \)\)$/\1 PLL_LOCKED/'"
    run_t_cmd "phy_rdb_read tnm 0xa59 | sed 's/^\(0x\(0*\|[Ff]\3\\ )[0-9a-fA-F]\)$/\1 PLL_LOCKED/'"
    run_t_cmd "phy_rdb_read tnn 0xa5a | sed 's/^\(0x\(0\+\|[Ff]\4\ \)\)$/\1 PLL_LOCKED/'"
    run_t_cmd "phy_rdb_read tnn 0xa59 | sed 's/^\(0x\(0*\|[Ff]\3\\ )[0-9a-fA-F]\)$/\1 PLL_LOCKED/'"
    run_t_cmd "phy_readhbts tnk"
    run_t_cmd "phy_readhbts tnl"
    run_t_cmd "phy_readhbts tnm"
    run_t_cmd "phy_readhbts tnn"
    run_t_cmd "tud_timesync phy"
    run_t_cmd "phy_readhbts tnk"
    run_t_cmd "phy_readhbts tnl"
    run_t_cmd "phy_readhbts tnm"
    run_t_cmd "phy_readhbts tnn"
    run_t_cmd "npu_refclksel tna btn"
    run_t_cmd "npu_refclksel tnb btn"
    run_t_cmd "npu_refclksel tnc btn"
    run_t_cmd "npu_refclksel tnd btn"
    run_t_cmd "npu_refclksel tne btn"
    run_t_cmd "npuprbs_set tna tx prbs7"
    run_t_cmd "npuprbs_set tnb tx prbs7"
    run_t_cmd "npuprbs_set tnc tx prbs7"
    run_t_cmd "npuprbs_set tnd tx prbs7"
    run_t_cmd "npuprbs_set tne tx prbs7"
    run_t_cmd "npuprbs_set tna rx prbs7"
    run_t_cmd "npuprbs_set tnb rx prbs7"
    run_t_cmd "npuprbs_set tnc rx prbs7"
    run_t_cmd "npuprbs_set tnd rx prbs7"
    run_t_cmd "npuprbs_set tne rx prbs7"
# we cant read out status since we dont have anything connected on TN ports
#    run_t_cmd "npuprbs_status tna 1"
#    run_t_cmd "npuprbs_status tnb 1"
#    run_t_cmd "npuprbs_status tnc 1"
#    run_t_cmd "npuprbs_status tnd 1"
#    run_t_cmd "npuprbs_status tne 1"
    run_t_cmd "npuprbs_set tna rx off"
    run_t_cmd "npuprbs_set tnb rx off"
    run_t_cmd "npuprbs_set tnc rx off"
    run_t_cmd "npuprbs_set tnd rx off"
    run_t_cmd "npuprbs_set tne rx off"
    run_t_cmd "npuprbs_set tna tx off"
    run_t_cmd "npuprbs_set tnb tx off"
    run_t_cmd "npuprbs_set tnc tx off"
    run_t_cmd "npuprbs_set tnd tx off"
    run_t_cmd "npuprbs_set tne tx off"
    run_t_cmd "npuprbs_set tnf tx prbs7"
    run_t_cmd "npuprbs_set tng tx prbs7"
    run_t_cmd "npuprbs_set tnh tx prbs7"
    run_t_cmd "npuprbs_set tnj tx prbs7"
    run_t_cmd "npuprbs_set tnf rx prbs7"
    run_t_cmd "npuprbs_set tng rx prbs7"
    run_t_cmd "npuprbs_set tnh rx prbs7"
    run_t_cmd "npuprbs_set tnj rx prbs7"
# we cant read out status since we dont have anything connected on TN ports
#    run_t_cmd "npuprbs_status tnf 1"
#    run_t_cmd "npuprbs_status tng 1"
#    run_t_cmd "npuprbs_status tnh 1"
#    run_t_cmd "npuprbs_status tnj 1"
    run_t_cmd "npuprbs_set tnf rx off"
    run_t_cmd "npuprbs_set tng rx off"
    run_t_cmd "npuprbs_set tnh rx off"
    run_t_cmd "npuprbs_set tnj rx off"
    run_t_cmd "npuprbs_set tnf tx off"
    run_t_cmd "npuprbs_set tng tx off"
    run_t_cmd "npuprbs_set tnh tx off"
    run_t_cmd "npuprbs_set tnj tx off"
    run_t_cmd "tnport_setup tnk"
    run_t_cmd "phy_mode tnk copper_loop"
    run_t_cmd "nputrf_rxstart tnk verify"
    run_t_cmd "nputrf_txstart tnk 100 32"
    run_t_cmd "nputrf_stats tnk"
    run_t_cmd "nputrf_txstop tnk"
    run_t_cmd "nputrf_rxstop tnk"
    run_t_cmd "nputrf_stats tnk clear"
    run_t_cmd "phy_mode tnk normal"
    run_t_cmd "tnport_setup tnl"
    run_t_cmd "phy_mode tnl copper_loop"
    run_t_cmd "nputrf_rxstart tnl verify"
    run_t_cmd "nputrf_txstart tnl 100 32"
    run_t_cmd "nputrf_stats tnl"
    run_t_cmd "nputrf_txstop tnl"
    run_t_cmd "nputrf_rxstop tnl"
    run_t_cmd "nputrf_stats tnl clear"
    run_t_cmd "phy_mode tnl normal"
    run_t_cmd "tnport_setup tnm"
    run_t_cmd "phy_mode tnm copper_loop"
    run_t_cmd "nputrf_rxstart tnm verify"
    run_t_cmd "nputrf_txstart tnm 100 32"
    run_t_cmd "nputrf_stats tnm"
    run_t_cmd "nputrf_txstop tnm"
    run_t_cmd "nputrf_rxstop tnm"
    run_t_cmd "nputrf_stats tnm clear"
    run_t_cmd "phy_mode tnm normal"
    run_t_cmd "tnport_setup tnn"
    run_t_cmd "phy_mode tnn copper_loop"
    run_t_cmd "nputrf_rxstart tnn verify"
    run_t_cmd "nputrf_txstart tnn 100 32"
    run_t_cmd "nputrf_stats tnn"
    run_t_cmd "nputrf_txstop tnn"
    run_t_cmd "nputrf_rxstop tnn"
    run_t_cmd "nputrf_stats tnn clear"
    run_t_cmd "phy_mode tnn normal"
    run_t_cmd "tdm_trx_configure normal"
    run_t_cmd "tdm_loopback int_eth"
    run_t_cmd "tdm_open_sc 0 0 1 7"
    run_t_cmd "tdmtrf_rx start 0 0"
    run_t_cmd "tdmtrf_tx start 1 10 250 0 0"
    run_t_cmd "tdmtrf_stats ea sc 0"
    run_t_cmd "tdmtrf_tx stop 0 0"
    run_t_cmd "tdmtrf_rx stop 0 0"
    run_t_cmd "tdm_close_sc 0 0 1 7"
    run_t_cmd "tdm_loopback disable"
    run_t_cmd "tdmtrf_stats ea clear"
    run_t_cmd "tdm_trx_configure normal"
    run_t_cmd "tdm_phy_enable"
    run_t_cmd "tdmphy_configure 0 0 E1"
    run_t_cmd "tdmphy_configure 0 1 E1"
    run_t_cmd "tdmphy_configure 0 2 E1"
    run_t_cmd "tdmphy_configure 0 3 E1"
    run_t_cmd "tdmphy_configure 1 0 E1"
    run_t_cmd "tdmphy_configure 1 1 E1"
    run_t_cmd "tdmphy_configure 1 2 E1"
    run_t_cmd "tdmphy_configure 1 3 E1"
    run_t_cmd "tdmphy_loopback 0 0 off"
    run_t_cmd "tdmphy_loopback 0 1 off"
    run_t_cmd "tdmphy_loopback 0 2 off"
    run_t_cmd "tdmphy_loopback 0 3 off"
    run_t_cmd "tdmphy_loopback 1 0 off"
    run_t_cmd "tdmphy_loopback 1 1 off"
    run_t_cmd "tdmphy_loopback 1 2 off"
    run_t_cmd "tdmphy_loopback 1 3 off"
    run_t_cmd "tdm_open_sc 0 0 1 7"
    run_t_cmd "tdm_open_sc 1 0 1 7"
    run_t_cmd "tdm_open_sc 2 0 1 7"
    run_t_cmd "tdm_open_sc 3 0 1 7"
    run_t_cmd "tdm_open_sc 4 0 1 7"
    run_t_cmd "tdm_open_sc 5 0 1 7"
    run_t_cmd "tdm_open_sc 6 0 1 7"
    run_t_cmd "tdm_open_sc 7 0 1 7"
    run_t_cmd "tdmtrf_rx start 0 0"
    run_t_cmd "tdmtrf_rx start 1 0"
    run_t_cmd "tdmtrf_rx start 2 0"
    run_t_cmd "tdmtrf_rx start 3 0"
    run_t_cmd "tdmtrf_rx start 4 0"
    run_t_cmd "tdmtrf_rx start 5 0"
    run_t_cmd "tdmtrf_rx start 6 0"
    run_t_cmd "tdmtrf_rx start 7 0"
    run_t_cmd "tdmtrf_tx start 1 10 250 0 0"
    run_t_cmd "tdmtrf_tx start 1 10 250 1 0"
    run_t_cmd "tdmtrf_tx start 1 10 250 2 0"
    run_t_cmd "tdmtrf_tx start 1 10 250 3 0"
    run_t_cmd "tdmtrf_tx start 1 10 250 4 0"
    run_t_cmd "tdmtrf_tx start 1 10 250 5 0"
    run_t_cmd "tdmtrf_tx start 1 10 250 6 0"
    run_t_cmd "tdmtrf_tx start 1 10 250 7 0"
    run_t_cmd "tdmtrf_stats ea sc 0"
    run_t_cmd "tdmtrf_stats ea sc 4"
    run_t_cmd "tdmtrf_stats ea sc 8"
    run_t_cmd "tdmtrf_stats ea sc 12"
    run_t_cmd "tdmtrf_stats ea sc 16"
    run_t_cmd "tdmtrf_stats ea sc 20"
    run_t_cmd "tdmtrf_stats ea sc 24"
    run_t_cmd "tdmtrf_stats ea sc 28"
    run_t_cmd "tdmtrf_tx stop"
    run_t_cmd "tdmtrf_rx stop"
    run_t_cmd "tdm_close_sc 0 0 1 7"
    run_t_cmd "tdm_close_sc 1 0 1 7"
    run_t_cmd "tdm_close_sc 2 0 1 7"
    run_t_cmd "tdm_close_sc 3 0 1 7"
    run_t_cmd "tdm_close_sc 4 0 1 7"
    run_t_cmd "tdm_close_sc 5 0 1 7"
    run_t_cmd "tdm_close_sc 6 0 1 7"
    run_t_cmd "tdm_close_sc 7 0 1 7"
    run_t_cmd "sfp_power tna on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tna eeprom"
#    run_t_cmd "sfp_testio tna"
    run_t_cmd "sfp_power tna off"
    run_t_cmd "sfp_power tnb on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tnb eeprom"
#    run_t_cmd "sfp_testio tnb"
    run_t_cmd "sfp_power tnb off"
    run_t_cmd "sfp_power tnc on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tnc eeprom"
#    run_t_cmd "sfp_testio tnc"
    run_t_cmd "sfp_power tnc off"
    run_t_cmd "sfp_power tnd on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tnd eeprom"
#    run_t_cmd "sfp_testio tnd"
    run_t_cmd "sfp_power tnd off"
    run_t_cmd "sfp_power tne on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tne eeprom"
#    run_t_cmd "sfp_testio tne"
    run_t_cmd "sfp_power tne off"
    run_t_cmd "sfp_power tnf on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tnf eeprom"
#    run_t_cmd "sfp_testio tnf"
    run_t_cmd "sfp_power tnf off"
    run_t_cmd "sfp_power tng on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tng eeprom"
#    run_t_cmd "sfp_testio tng"
    run_t_cmd "sfp_power tng off"
    run_t_cmd "sfp_power tnh on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tnh eeprom"
#    run_t_cmd "sfp_testio tnh"
    run_t_cmd "sfp_power tnh off"
    run_t_cmd "sfp_power tnj on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tnj eeprom"
#    run_t_cmd "sfp_testio tnj"
    run_t_cmd "sfp_power tnj off"
    run_t_cmd "tnport_setup tnk"
    run_t_cmd "phy_mode tnk loop"
    run_t_cmd "nputrf_rxstart tnk verify"
    run_t_cmd "nputrf_txstart tnk 100 32"
    run_t_cmd "nputrf_stats tnk"
    run_t_cmd "nputrf_txstop tnk"
    run_t_cmd "nputrf_rxstop tnk"
    run_t_cmd "nputrf_stats tnk clear"
    run_t_cmd "phy_mode tnk normal"
    run_t_cmd "tnport_setup tnl"
    run_t_cmd "phy_mode tnl loop"
    run_t_cmd "nputrf_rxstart tnl verify"
    run_t_cmd "nputrf_txstart tnl 100 32"
    run_t_cmd "nputrf_stats tnl"
    run_t_cmd "nputrf_txstop tnl"
    run_t_cmd "nputrf_rxstop tnl"
    run_t_cmd "nputrf_stats tnl clear"
    run_t_cmd "phy_mode tnl normal"
    run_t_cmd "tnport_setup tnm"
    run_t_cmd "phy_mode tnm loop"
    run_t_cmd "nputrf_rxstart tnm verify"
    run_t_cmd "nputrf_txstart tnm 100 32"
    run_t_cmd "nputrf_stats tnm"
    run_t_cmd "nputrf_txstop tnm"
    run_t_cmd "nputrf_rxstop tnm"
    run_t_cmd "nputrf_stats tnm clear"
    run_t_cmd "phy_mode tnm normal"
    run_t_cmd "tnport_setup tnn"
    run_t_cmd "phy_mode tnn loop"
    run_t_cmd "nputrf_rxstart tnn verify"
    run_t_cmd "nputrf_txstart tnn 100 32"
    run_t_cmd "nputrf_stats tnn"
    run_t_cmd "nputrf_txstop tnn"
    run_t_cmd "nputrf_rxstop tnn"
    run_t_cmd "nputrf_stats tnn clear"
    run_t_cmd "phy_mode tnn normal"
    run_t_cmd "phy_write tnk 0x17 0x0f7e"
    run_t_cmd "phy_write tnk 0x15 0"
    run_t_cmd "phy_write tnk 0x1e 0x083c"
    run_t_cmd "phy_write tnk 0x1f 0x0090"
    run_t_cmd "phy_write tnk 0x1e 0x083c"
    run_t_cmd "phy_read tnk 0x1f"
    run_t_cmd "mux_ptc tuf 5"
    run_t_cmd "phy_write tnk 0x1e 0x083c"
    run_t_cmd "phy_write tnk 0x1f 0x0098"
    run_t_cmd "phy_write tnk 0x1e 0x083c"
    run_t_cmd "phy_read tnk 0x1f"
    run_t_cmd "phy_write tnl 0x17 0x0f7e"
    run_t_cmd "phy_write tnl 0x15 0"
    run_t_cmd "phy_write tnl 0x1e 0x083c"
    run_t_cmd "phy_write tnl 0x1f 0x0090"
    run_t_cmd "phy_write tnl 0x1e 0x083c"
    run_t_cmd "phy_read tnl 0x1f"
    run_t_cmd "mux_ptc tuf 6"
    run_t_cmd "phy_write tnl 0x1e 0x083c"
    run_t_cmd "phy_write tnl 0x1f 0x0098"
    run_t_cmd "phy_write tnl 0x1e 0x083c"
    run_t_cmd "phy_read tnl 0x1f"
    run_t_cmd "phy_write tnm 0x17 0x0f7e"
    run_t_cmd "phy_write tnm 0x15 0"
    run_t_cmd "phy_write tnm 0x1e 0x083c"
    run_t_cmd "phy_write tnm 0x1f 0x0090"
    run_t_cmd "phy_write tnm 0x1e 0x083c"
    run_t_cmd "phy_read tnm 0x1f"
    run_t_cmd "mux_ptc tuf 7"
    run_t_cmd "phy_write tnm 0x1e 0x083c"
    run_t_cmd "phy_write tnm 0x1f 0x0098"
    run_t_cmd "phy_write tnm 0x1e 0x083c"
    run_t_cmd "phy_read tnm 0x1f"
    run_t_cmd "phy_write tnn 0x17 0x0f7e"
    run_t_cmd "phy_write tnn 0x15 0"
    run_t_cmd "phy_write tnn 0x1e 0x083c"
    run_t_cmd "phy_write tnn 0x1f 0x0090"
    run_t_cmd "phy_write tnn 0x1e 0x083c"
    run_t_cmd "phy_read tnn 0x1f"
    run_t_cmd "mux_ptc tuf 14"
    run_t_cmd "phy_write tnn 0x1e 0x083c"
    run_t_cmd "phy_write tnn 0x1f 0x0098"
    run_t_cmd "phy_write tnn 0x1e 0x083c"
    run_t_cmd "phy_read tnn 0x1f"
    run_t_cmd "mux_ptc ccr 2"
    run_t_cmd "mux_ptc ccr 0"
    run_t_cmd "mux_ptc ccr 1"
    run_t_cmd "mux_ptc ccr 8"
    run_t_cmd "mux_ptc tuf 0"
    run_t_cmd "mux_ptc tuf 1"
    run_t_cmd "syntaocxo_temp_sensor"
# loop_port not possible to execute without loop plug/cable
#    run_t_cmd "loop_port 4 0x000000a2"
#    run_t_cmd "loop_port 12 0x000000a3"
#    run_t_cmd "loop_port 0 0x000000a1"
    run_t_cmd "ecb_addr_pins"
    run_t_cmd "ecb_addr_pins"
    run_t_cmd "npuprbs_set tna tx prbs7"
    run_t_cmd "npuprbs_set tnb tx prbs7"
    run_t_cmd "npuprbs_set tnc tx prbs7"
    run_t_cmd "npuprbs_set tnd tx prbs7"
    run_t_cmd "npuprbs_set tne tx prbs7"
    run_t_cmd "npusynce_select tna 0"
    run_t_cmd "mux_ptc tuf 3"
    run_t_cmd "npusynce_select tnb 1"
    run_t_cmd "mux_ptc tuf 4"
    run_t_cmd "npusynce_select tnc 0"
    run_t_cmd "mux_ptc tuf 3"
    run_t_cmd "npusynce_select tnd 1"
    run_t_cmd "mux_ptc tuf 4"
    run_t_cmd "npusynce_select tne 0"
    run_t_cmd "mux_ptc tuf 3"
    run_t_cmd "npuprbs_set tna tx off"
    run_t_cmd "npuprbs_set tnb tx off"
    run_t_cmd "npuprbs_set tnc tx off"
    run_t_cmd "npuprbs_set tnd tx off"
    run_t_cmd "npuprbs_set tne tx off"
    run_t_cmd "npuprbs_set tnf tx prbs7"
    run_t_cmd "npuprbs_set tng tx prbs7"
    run_t_cmd "npuprbs_set tnh tx prbs7"
    run_t_cmd "npuprbs_set tnj tx prbs7"
    run_t_cmd "npusynce_select tnf 0"
    run_t_cmd "mux_ptc tuf 3"
    run_t_cmd "npusynce_select tng 1"
    run_t_cmd "mux_ptc tuf 4"
    run_t_cmd "npusynce_select tnh 0"
    run_t_cmd "mux_ptc tuf 3"
    run_t_cmd "npusynce_select tnj 1"
    run_t_cmd "mux_ptc tuf 4"
    run_t_cmd "npuprbs_set tnf tx off"
    run_t_cmd "npuprbs_set tng tx off"
    run_t_cmd "npuprbs_set tnh tx off"
    run_t_cmd "npuprbs_set tnj tx off"
    run_t_cmd "nputrf_txstart tnk 100 32"
    run_t_cmd "nputrf_txstart tnl 100 32"
    run_t_cmd "nputrf_txstart tnm 100 32"
    run_t_cmd "nputrf_txstart tnn 100 32"
    run_t_cmd "npusynce_select tnk 0"
    run_t_cmd "mux_ptc tuf 3"
    run_t_cmd "npusynce_select tnl 1"
    run_t_cmd "mux_ptc tuf 4"
    run_t_cmd "npusynce_select tnm 0"
    run_t_cmd "mux_ptc tuf 3"
    run_t_cmd "npusynce_select tnn 1"
    run_t_cmd "mux_ptc tuf 4"
    run_t_cmd "nputrf_txstop tnk"
    run_t_cmd "nputrf_txstop tnl"
    run_t_cmd "nputrf_txstop tnm"
    run_t_cmd "nputrf_txstop tnn"
    run_t_cmd "temp_read npu"
    run_t_cmd "temp_read board"
    run_t_cmd "icm_wr fan 0x20 0xf"
    run_t_cmd "get_fan_status"
    run_t_cmd "get_fan_status"
    run_t_cmd "set_fan_speed 20"
    run_t_cmd "set_fan_speed 50"
    run_t_cmd "set_fan_speed 20"

# Not possible to execute since nobody can push the button
#    run_t_cmd "button_mmi_chk"
#    run_t_cmd "button_factrestore_chk"

    run_t_cmd "--wait bscan -o=rm:4vt:1rf:/var/volatile/T605_MTC_ROA_P1B.txt -s /home/sirpa/T605_MTC_ROA_P1B.svf -c"
    run_t_cmd "--wait bscan -o=rm:4vt:0rf:/var/volatile/MTC_INTERCONNECT_T605_BOM_D_DIXON3.txt -s /home/sirpa/MTC_INTERCONNECT_T605_BOM_D_DIXON3.svf - c"
}


if [ "$BOARDTYPE" == "TCU0401" ]
then
    run_t_cmd "--clear all"
    prod_test_tcu04;
    run_t_cmd "--status"
fi
