#!/bin/bash

SCRIPTDIR=$(dirname $0);
source $SCRIPTDIR/hwt-util.sh

BOARDTYPE=$(get_boardtype);
echo "$BOARDTYPE";

ICMTYPE=$(get_icmtype);
echo "$ICMTYPE";

run_cmd(){
	cmd=$1
	echo "-----------------------------------------------------------------"
	echo -e "testbox $cmd"
	testbox $cmd
	echo "-----------------------------------------------------------------"
}

LOOP_IN_FPGA="enable"

conn1() {
	run_cmd "icmioexp_rst_test"
	run_cmd "turef_status"
	run_cmd "turef_status rbs"
	run_cmd "icm_wr tuf 0x0078 0x0004"
	run_cmd "icm_rd tuf 0x0078"
	run_cmd "generate_freq 9"
	run_cmd "icm_wr tuf 0x0078 0x0000"
	run_cmd "icm_rd tuf 0x0078"
	## This is not needed, if this doesn't work the icm_status will return FAIL
	#run_cmd "icm_load ssp"
	#run_cmd "i2c_test 7 /dev/i2c-0 1 0x41 2"
	#run_cmd "icm_load cvp"
	#run_cmd "i2c_test 7 /dev/i2c-0 1 0x41 2"
	#run_cmd "icm_rd swri 54"
	#run_cmd "icm_wr swri 54 0x00"
	#run_cmd "icm_rd swri 54"
	#run_cmd "icm_load ssp"
	#run_cmd "icm_load cvp"
	#run_cmd "icm_rd swri 54"
	## Until here
	run_cmd "icm_status"
	run_cmd "syntamult_read 0x0006"
	run_cmd "syntmod_read RBS 0x001"
	run_cmd "syntmod_write RBS 0x001 0xf1"
	run_cmd "syntmod_read RBS 0x001"
	run_cmd "syntmod_write RBS 0x001 0xd"
	run_cmd "syntmod_read RBS 0x001"
	run_cmd "syntfpll_read RBS 0x0000"
	run_cmd "syntfpll_write RBS 0x0000 0xf1"
	run_cmd "syntfpll_read RBS 0x0000"
	run_cmd "syntfpll_write RBS 0x0000 0x600d001"
	run_cmd "syntfpll_read RBS 0x0000"
	run_cmd "syntmod_read TN 0x001"
	run_cmd "syntmod_write TN 0x001 0xf1"
	run_cmd "syntmod_read TN 0x001"
	run_cmd "syntmod_write TN 0x001 0xa014"
	run_cmd "syntmod_read TN 0x001"
	run_cmd "syntfpll_read TN 0x0000"
	run_cmd "syntfpll_write TN 0x0000 0xf1"
	run_cmd "syntfpll_read TN 0x0000"
	run_cmd "syntfpll_write TN 0x0000 0x6010001"
	run_cmd "syntfpll_read TN 0x0000"
	run_cmd "synth_init"
	run_cmd "synth_status"
	run_cmd "npu_load frog"
	run_cmd "npucmem_test -C 0 -e 1 -f 1 -m 0 -p 0"
	run_cmd "npucmem_test -C 1 -e 1 -f 1 -m 0 -p 0"
	run_cmd "npucmem_test -C 0 -e 1 -f 1 -m 0 -p 1"
	run_cmd "npucmem_test -C 1 -e 1 -f 1 -m 0 -p 1"
	run_cmd "emca_power on"
	run_cmd "emca_reset 1"
	run_cmd "emca_reset 0"
	run_cmd "emca_init"
	run_cmd "emca_ethinit emca1"
	run_cmd "emca_ethinit emca4"
	run_cmd "emca_ethinit emca2"
	run_cmd "emca_ethinit emca3"
	## What it this, If it's something for ddrtest, you can remove it!
	run_cmd "emca_rb emca1 0x9c 0x86 0x00 0x00 0x00 w"
	run_cmd "emca_rb emca4 0x9c 0x86 0x00 0x00 0x00 w"
	run_cmd "emca_rb emca2 0x9c 0x86 0x00 0x00 0x00 w"
	run_cmd "emca_rb emca3 0x9c 0x86 0x00 0x00 0x00 w"
	run_cmd "emca_ddrtest emca1"
	run_cmd "icm_rd tuf 0x0180"
	run_cmd "icm_rd tuf 0x0184"
	run_cmd "icm_rd tuf 0x0188"
	run_cmd "syntaocxo_dump"
	run_cmd "syntaocxo_temp_sensor"
	run_cmd "syntaocxo_checksum"
	run_cmd "emca_ddrtest emca2"
	run_cmd "emca_ddrtest emca3"
	run_cmd "emca_ddrtest emca4"
	##run_cmd "bpm_raw 8 0x12 0x00 0x01 0x29 0x00 0x01 0x02 0x00 <bpm_raw 8 0x12 0x00 0x01 0x29 0x00 0x01 0x02 0x00 0                         \'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08x00 0x00 0x00 0x00"
	##run_cmd "bpm_raw 8 0x12 0x00 0x01 0x2a 0x00 0x01 0x02 0x00 <bpm_raw 8 0x12 0x00 0x01 0x2a 0x00 0x01 0x02 0x00 0                         \'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08x00 0x00 0x00 0x00"
	##run_cmd "bpm_raw 8 0x12 0x00 0x01 0x2f 0x00 0x01 0x02 0x00 <bpm_raw 8 0x12 0x00 0x01 0x2f 0x00 0x01 0x02 0x00 0                         \'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08x00 0x00 0x00 0x00"
	##run_cmd "bpm_raw 8 0x12 0x00 0x01 0x2c 0x00 0x01 0x02 0x00 <bpm_raw 8 0x12 0x00 0x01 0x2c 0x00 0x01 0x02 0x00 0                         \'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08\'08x00 0x00 0x00 0x00"
	run_cmd "npuprbs_set bbm0 tx prbs7"
	run_cmd "emcaprbs_set emca1 et9 tx prbs7"
	run_cmd "emcaprbs_set emca1 et8 tx prbs7"
	run_cmd "npuprbs_set bbm1 tx prbs7"
	run_cmd "emcaprbs_set emca1 et9 rx prbs7"
	run_cmd "npuprbs_set bbm1 rx prbs7"
	run_cmd "emcaprbs_set emca2 et7 tx prbs7"
	run_cmd "npuprbs_set bbm2 tx prbs7"
	run_cmd "emcaprbs_set emca3 et8 tx prbs7"
	run_cmd "emcaprbs_set emca2 et6 tx prbs7"
	run_cmd "npuprbs_set bbm4 tx prbs7"
	run_cmd "emcaprbs_set emca3 et8 rx prbs7"
	run_cmd "emcaprbs_set emca2 et6 rx prbs7"
	run_cmd "emcaprbs_set emca1 et8 rx prbs7"
	run_cmd "npuprbs_set bbm3 tx prbs7"
	run_cmd "emcaprbs_set emca2 et7 rx prbs7"
	run_cmd "npuprbs_set bbm0 rx prbs7"
	run_cmd "npuprbs_set bbm2 rx prbs7"
	run_cmd "npuprbs_set bbm4 rx prbs7"
	run_cmd "npuprbs_set bbm3 rx prbs7"
	run_cmd "emcaprbs_stats emca2 et6 1"
	run_cmd "emcaprbs_set emca2 et6 rx off"
	run_cmd "npuprbs_status bbm2"
	run_cmd "npuprbs_status bbm4"
	run_cmd "npuprbs_status bbm0"
	run_cmd "npuprbs_set bbm0 rx off"
	run_cmd "npuprbs_status bbm1"
	run_cmd "emcaprbs_stats emca1 et8 1"
	run_cmd "emcaprbs_stats emca1 et9 1"
	run_cmd "npuprbs_set bbm2 rx off"
	run_cmd "emcaprbs_stats emca3 et8 1"
	run_cmd "npuprbs_status bbm3"
	run_cmd "emcaprbs_stats emca2 et7 1"
	run_cmd "npuprbs_set bbm4 rx off"
	run_cmd "npuprbs_set bbm2 tx off"
	run_cmd "emcaprbs_set emca1 et8 tx off"
	run_cmd "emcaprbs_set emca1 et8 rx off"
	run_cmd "npuprbs_set bbm3 rx off"
	run_cmd "emcaprbs_set emca2 et7 tx off"
	run_cmd "emcaprbs_set emca2 et7 rx off"
	run_cmd "npuprbs_set bbm3 tx off"
	run_cmd "npuprbs_set bbm0 tx off"
	run_cmd "npuprbs_set bbm1 rx off"
	run_cmd "emcaprbs_set emca3 et8 rx off"
	run_cmd "emcaprbs_set emca1 et9 tx off"
	run_cmd "npuprbs_set bbm4 tx off"
	run_cmd "emcaprbs_set emca1 et9 rx off"
	run_cmd "emcaprbs_set emca2 et6 tx off"
	run_cmd "emcaprbs_set emca3 et8 tx off"
	run_cmd "npuprbs_set bbm1 tx off"
	run_cmd "npuprbs_set bbm5 tx prbs7"
	run_cmd "emcaprbs_set emca3 et9 rx prbs7"
	run_cmd "emcaprbs_stats emca3 et9 1"
	run_cmd "emcaprbs_set emca3 et9 rx off"
	run_cmd "npuprbs_set bbm5 tx off"
	run_cmd "emcaprbs_set emca3 et9 tx prbs7"
	run_cmd "npuprbs_set bbm5 rx prbs7"
	run_cmd "npuprbs_status bbm5"
	run_cmd "npuprbs_set bbm5 rx off"
	run_cmd "emcaprbs_set emca3 et9 tx off"
	run_cmd "npuprbs_set bbm6 tx prbs7"
	run_cmd "emcaprbs_set emca4 et8 rx prbs7"
	run_cmd "emcaprbs_set emca4 et9 tx prbs7"
	run_cmd "npuprbs_set bbm7 tx prbs7"
	run_cmd "emcaprbs_set emca4 et9 rx prbs7"
	run_cmd "npuprbs_set bbm7 rx prbs7"
	run_cmd "emcaprbs_set emca4 et8 tx prbs7"
	run_cmd "npuprbs_set bbm6 rx prbs7"
	run_cmd "emcaprbs_stats emca4 et8 1"
	run_cmd "emcaprbs_set emca4 et8 rx off"
	run_cmd "npuprbs_status bbm6"
	run_cmd "npuprbs_set bbm6 tx off"
	run_cmd "npuprbs_set bbm6 rx off"
	run_cmd "emcaprbs_stats emca4 et9 1"
	run_cmd "emcaprbs_set emca4 et8 tx off"
	run_cmd "emcaprbs_set emca4 et9 rx off"
	run_cmd "npuprbs_status bbm7"
	run_cmd "npuprbs_set bbm7 tx off"
	run_cmd "npuprbs_set bbm7 rx off"
	run_cmd "emcaprbs_set emca4 et9 tx off"
	run_cmd "phy_read tna 0x00"
	run_cmd "phy_write tna 0x00 0x1000"
	run_cmd "phy_read tna 0x00"
	run_cmd "icm_wr tn 0x0010 0x0"
	run_cmd "icm_wr tn 0x0010 0x1"
	run_cmd "phy_read tna 0x00"
	if [ "$ICMTYPE" == "STRATIX" ]
	then
		run_cmd "retimer_read ri0 0x000"
		run_cmd "retimer_write ri0 0x000 0x12"
		run_cmd "retimer_read ri0 0x000"
		run_cmd "retimer_write ri0 0x000 0x0"
		run_cmd "retimer_read ri0 0x000"
		run_cmd "retimer_read tnc 0x000"
		run_cmd "retimer_write tnc 0x000 0x12"
		run_cmd "retimer_read tnc 0x000"
		run_cmd "retimer_write tnc 0x000 0x0"
		run_cmd "retimer_read tnc 0x000"
		run_cmd "retimer_read ri1 0x000"
		run_cmd "retimer_write ri1 0x000 0x12"
		run_cmd "retimer_read ri1 0x000"
		run_cmd "retimer_write ri1 0x000 0x0"
		run_cmd "retimer_read ri1 0x000"
		run_cmd "retimer_read tnb 0x000"
		run_cmd "retimer_write tnb 0x000 0x12"
		run_cmd "retimer_read tnb 0x000"
		run_cmd "retimer_write tnb 0x000 0x0"
		run_cmd "retimer_read tnb 0x000"
		run_cmd "retimer_read ri2 0x000"
		run_cmd "retimer_write ri2 0x000 0x12"
		run_cmd "retimer_read ri2 0x000"
		run_cmd "retimer_write ri2 0x000 0x0"
		run_cmd "retimer_read ri2 0x000"
		run_cmd "retimer_read ri5 0x000"
		run_cmd "retimer_write ri5 0x000 0x12"
		run_cmd "retimer_read ri5 0x000"
		run_cmd "retimer_write ri5 0x000 0x0"
		run_cmd "retimer_read ri5 0x000"
		run_cmd "retimer_read ri3 0x000"
		run_cmd "retimer_write ri3 0x000 0x12"
		run_cmd "retimer_read ri3 0x000"
		run_cmd "retimer_write ri3 0x000 0x0"
		run_cmd "retimer_read ri3 0x000"
		run_cmd "retimer_read ri4 0x000"
		run_cmd "retimer_write ri4 0x000 0x12"
		run_cmd "retimer_read ri4 0x000"
		run_cmd "retimer_write ri4 0x000 0x0"
		run_cmd "retimer_read ri4 0x000"
		run_cmd "retimer_write ri0 0x15 0x53"
		run_cmd "retimer_write ri1 0x15 0x53"
		run_cmd "retimer_write ri2 0x15 0x53"
		run_cmd "retimer_write ri3 0x15 0x53"
		run_cmd "retimer_write ri4 0x15 0x53"
		run_cmd "retimer_write ri5 0x15 0x53"
		run_cmd "retimer_write tnb 0x15 0x53"
		run_cmd "retimer_write tnc 0x15 0x53"
	fi
	if [[ $LOOP_IN_FPGA == "enable" ]]
	then
		run_cmd "icmtrx_mode ri0 serial"
	fi
	run_cmd "icmtrx_prbsgen ri0 1 1 7"
	run_cmd "icmtrx_prbsver ri0 1 1 7"
	run_cmd "icmtrx_prbsstatus ri0 1"
	run_cmd "icmtrx_prbsver ri0 0 1 7"
	run_cmd "icmtrx_prbsgen ri0 0 1 7"
	run_cmd "tud_timesync phy"
	run_cmd "phy_readhbts tna"
	#run_cmd "phy_rdb_read tna 0xa5a"
	#run_cmd "phy_rdb_read tna 0xa5a"
	#run_cmd "phy_rdb_read tna 0xa59"
	#run_cmd "phy_rdb_read tna 0xa59"
	run_cmd "phy_readhbts tna"
	run_cmd "tud_timesync phy"
	run_cmd "phy_readhbts tna"
	run_cmd "sfp_power ri0 on"
	##run_cmd "sfp_dump ri0 eeprom"
	##run_cmd "sfp_testio ri0"
	run_cmd "sfp_power ri0 off"
	run_cmd "phy_write tna 0x17 0x0f7e"
	run_cmd "phy_write tna 0x15 0"
	run_cmd "phy_write tna 0x1e 0x083c"
	run_cmd "phy_write tna 0x1f 0x0090"
	run_cmd "phy_write tna 0x1e 0x083c"
	run_cmd "phy_read tna 0x1f"
	run_cmd "turef_status tna"
	run_cmd "mux_ptc tuf 5"
	run_cmd "phy_write tna 0x1e 0x083c"
	run_cmd "phy_write tna 0x1f 0x0098"
	run_cmd "phy_write tna 0x1e 0x083c"
	run_cmd "phy_read tna 0x1f"
}

conn2() {
	run_cmd "mux_ptc ccr 6"
	run_cmd "mux_ptc ccr 0"
	run_cmd "mux_ptc ccr 1"
	run_cmd "mux_ptc ccr 2"
	run_cmd "mux_ptc ccr 5"
	run_cmd "mux_ptc ccr 4"
	run_cmd "mux_ptc ccr 3"
	run_cmd "mux_ptc ccr 8"
	run_cmd "mux_ptc ccr 10"
	run_cmd "mux_ptc tuf 0"
	run_cmd "mux_ptc tuf 1"
	run_cmd "emcaprbs_set emca1 et0 tx prbs7"
	run_cmd "emcaprbs_set emca2 et3 tx prbs7"
	run_cmd "emcaprbs_set emca2 et2 tx prbs7"
	run_cmd "emcaprbs_set emca4 et0 tx prbs7"
	run_cmd "emcaprbs_set emca2 et8 tx prbs7"
	run_cmd "emcaprbs_set emca4 et4 tx prbs7"
	run_cmd "emcaprbs_set emca4 et2 tx prbs7"
	run_cmd "emcaprbs_set emca3 et3 tx prbs7"
	run_cmd "emcaprbs_set emca2 et1 tx prbs7"
	run_cmd "emcaprbs_set emca4 et5 tx prbs7"
	run_cmd "emcaprbs_set emca4 et3 tx prbs7"
	run_cmd "emcaprbs_set emca2 et0 rx prbs7"
	run_cmd "emcaprbs_set emca1 et7 rx prbs7"
	run_cmd "emcaprbs_set emca1 et5 rx prbs7"
	run_cmd "emcaprbs_set emca2 et1 rx prbs7"
	run_cmd "emcaprbs_set emca1 et4 rx prbs7"
	run_cmd "emcaprbs_set emca4 et4 rx prbs7"
	run_cmd "emcaprbs_set emca3 et2 rx prbs7"
	run_cmd "emcaprbs_set emca4 et2 rx prbs7"
	run_cmd "emcaprbs_set emca3 et5 rx prbs7"
	run_cmd "emcaprbs_set emca2 et0 tx prbs7"
	run_cmd "emcaprbs_set emca4 et3 rx prbs7"
	run_cmd "emcaprbs_set emca1 et5 tx prbs7"
	run_cmd "emcaprbs_set emca2 et2 rx prbs7"
	run_cmd "emcaprbs_stats emca1 et5 1"
	run_cmd "emcaprbs_set emca3 et2 tx prbs7"
	run_cmd "emcaprbs_set emca3 et1 rx prbs7"
	run_cmd "emcaprbs_set emca3 et4 tx prbs7"
	run_cmd "emcaprbs_set emca3 et1 tx prbs7"
	run_cmd "emcaprbs_set emca2 et9 tx prbs7"
	run_cmd "emcaprbs_set emca1 et1 tx prbs7"
	run_cmd "emcaprbs_set emca3 et5 tx prbs7"
	run_cmd "emcaprbs_set emca3 et0 tx prbs7"
	run_cmd "emcaprbs_set emca1 et7 tx prbs7"
	run_cmd "emcaprbs_set emca1 et4 tx prbs7"
	run_cmd "emcaprbs_set emca4 et1 tx prbs7"
	run_cmd "emcaprbs_set emca1 et6 tx prbs7"
	run_cmd "emcaprbs_stats emca2 et0 1"
	run_cmd "emcaprbs_stats emca1 et7 1"
	run_cmd "emcaprbs_set emca3 et3 rx prbs7"
	run_cmd "emcaprbs_set emca4 et1 rx prbs7"
	run_cmd "emcaprbs_set emca3 et0 rx prbs7"
	run_cmd "emcaprbs_stats emca3 et5 1"
	run_cmd "emcaprbs_set emca3 et5 rx off"
	run_cmd "emcaprbs_set emca1 et5 rx off"
	run_cmd "emcaprbs_set emca2 et8 tx off"
	run_cmd "emcaprbs_stats emca3 et2 1"
	run_cmd "emcaprbs_set emca2 et2 tx off"
	run_cmd "emcaprbs_set emca3 et2 rx off"
	run_cmd "emcaprbs_set emca1 et7 rx off"
	run_cmd "emcaprbs_set emca4 et0 tx off"
	run_cmd "emcaprbs_set emca4 et5 tx off"
	run_cmd "emcaprbs_set emca2 et3 rx prbs7"
	run_cmd "emcaprbs_set emca2 et0 rx off"
	run_cmd "emcaprbs_stats emca1 et4 1"
	run_cmd "emcaprbs_stats emca2 et2 1"
	run_cmd "emcaprbs_stats emca2 et1 1"
	run_cmd "emcaprbs_set emca2 et9 rx prbs7"
	run_cmd "emcaprbs_stats emca4 et2 1"
	run_cmd "emcaprbs_set emca4 et0 rx prbs7"
	run_cmd "emcaprbs_set emca1 et0 rx prbs7"
	run_cmd "emcaprbs_set emca3 et4 rx prbs7"
	run_cmd "emcaprbs_set emca1 et1 rx prbs7"
	run_cmd "emcaprbs_set emca4 et5 rx prbs7"
	run_cmd "emcaprbs_stats emca4 et3 1"
	run_cmd "emcaprbs_set emca1 et6 rx prbs7"
	run_cmd "emcaprbs_stats emca4 et4 1"
	run_cmd "emcaprbs_set emca2 et8 rx prbs7"
	run_cmd "emcaprbs_set emca4 et3 tx off"
	run_cmd "emcaprbs_stats emca4 et1 1"
	run_cmd "emcaprbs_set emca4 et1 rx off"
	run_cmd "emcaprbs_set emca1 et6 tx off"
	run_cmd "emcaprbs_stats emca3 et0 1"
	run_cmd "emcaprbs_stats emca3 et1 1"
	run_cmd "emcaprbs_set emca3 et0 rx off"
	run_cmd "emcaprbs_set emca2 et2 rx off"
	run_cmd "emcaprbs_set emca1 et4 rx off"
	run_cmd "emcaprbs_set emca2 et1 rx off"
	run_cmd "emcaprbs_set emca4 et4 rx off"
	run_cmd "emcaprbs_set emca4 et2 rx off"
	run_cmd "emcaprbs_set emca4 et3 rx off"
	run_cmd "emcaprbs_stats emca3 et3 1"
	run_cmd "emcaprbs_set emca2 et3 tx off"
	run_cmd "emcaprbs_set emca2 et0 tx off"
	run_cmd "emcaprbs_set emca3 et3 rx off"
	run_cmd "emcaprbs_set emca4 et4 tx off"
	run_cmd "emcaprbs_stats emca3 et4 1"
	run_cmd "emcaprbs_set emca3 et4 rx off"
	run_cmd "emcaprbs_set emca2 et1 tx off"
	run_cmd "emcaprbs_set emca2 et9 tx off"
	run_cmd "emcaprbs_stats emca2 et8 1"
	run_cmd "emcaprbs_set emca2 et8 rx off"
	run_cmd "emcaprbs_stats emca1 et6 1"
	run_cmd "emcaprbs_set emca1 et6 rx off"
	run_cmd "emcaprbs_set emca3 et5 tx off"
	run_cmd "emcaprbs_set emca1 et5 tx off"
	run_cmd "emcaprbs_set emca1 et1 tx off"
	run_cmd "emcaprbs_stats emca1 et1 1"
	run_cmd "emcaprbs_set emca3 et3 tx off"
	run_cmd "emcaprbs_set emca4 et2 tx off"
	run_cmd "emcaprbs_stats emca1 et0 1"
	run_cmd "emcaprbs_stats emca2 et3 1"
	run_cmd "emcaprbs_stats emca4 et0 1"
	run_cmd "emcaprbs_stats emca2 et9 1"
	run_cmd "emcaprbs_stats emca4 et5 1"
	run_cmd "emcaprbs_set emca3 et1 rx off"
	run_cmd "emcaprbs_set emca4 et1 tx off"
	run_cmd "emcaprbs_set emca1 et0 rx off"
	run_cmd "emcaprbs_set emca1 et1 rx off"
	run_cmd "emcaprbs_set emca3 et1 tx off"
	run_cmd "emcaprbs_set emca3 et0 tx off"
	run_cmd "emcaprbs_set emca2 et3 rx off"
	run_cmd "emcaprbs_set emca1 et0 tx off"
	run_cmd "emcaprbs_set emca1 et4 tx off"
	run_cmd "emcaprbs_set emca2 et9 rx off"
	run_cmd "emcaprbs_set emca3 et4 tx off"
	run_cmd "emcaprbs_set emca4 et5 rx off"
	run_cmd "emcaprbs_set emca3 et2 tx off"
	run_cmd "emcaprbs_set emca4 et0 rx off"
	run_cmd "emcaprbs_set emca1 et7 tx off"
	run_cmd "icm_rd swri b08"
	run_cmd "icmtrx_mode axma postcdr"
	run_cmd "npuprbs_set tna tx prbs15"
	run_cmd "npuprbs_set tna rx prbs15"
	run_cmd "npuprbs_status tna"
	run_cmd "npuprbs_set tna rx off"
	run_cmd "npuprbs_set tna tx off"
	run_cmd "icmtrx_mode axma normal"
	if [[ $LOOP_IN_FPGA == "enable" ]]
	then
		run_cmd "icmtrx_mode ri1 serial"
	fi
	run_cmd "icmtrx_prbsgen ri1 1 1 7"
	run_cmd "icmtrx_prbsver ri1 1 1 7"
	run_cmd "icmtrx_prbsstatus ri1 1"
	run_cmd "icmtrx_prbsver ri1 0 1 7"
	run_cmd "icmtrx_prbsgen ri1 0 1 7"
	run_cmd "sfp_power ri1 on"
	##run_cmd "sfp_dump ri1 eeprom"
	##run_cmd "sfp_testio ri1"
	run_cmd "sfp_power ri1 off"
	##run_cmd "axm_read_temp" -> npu_temp
	run_cmd "hotspot_temp"
}

conn3() {

	run_cmd "gpio get 4"
	run_cmd "gpio get 5"
	run_cmd "gpio get 6"
	run_cmd "gpio get 12"
	run_cmd "gpio get 13"
	run_cmd "gpio get 14"
	run_cmd "gpio get 15"
	run_cmd "gpio get 23"
	run_cmd "gpio get 26"
	run_cmd "gpio get 27"
	run_cmd "gpio get 28"
	run_cmd "gpio get 29"
	run_cmd "gpio get 31"
	run_cmd "gpio set 4 out_high"
	run_cmd "gpio set 5 out_high"
	run_cmd "gpio set 6 out_high"
	run_cmd "gpio set 12 out_high"
	run_cmd "gpio set 13 out_high"
	run_cmd "gpio set 14 out_high"
	run_cmd "gpio set 15 out_high"
	run_cmd "gpio set 23 out_high"
	run_cmd "gpio set 26 out_high"
	run_cmd "gpio set 27 out_high"
	run_cmd "gpio set 28 out_high"
	run_cmd "gpio set 29 out_high"
	run_cmd "gpio set 31 out_high"
	run_cmd "gpio set 4 out_low"
	run_cmd "gpio set 5 out_low"
	run_cmd "gpio set 6 out_low"
	run_cmd "gpio set 12 out_low"
	run_cmd "gpio set 13 out_low"
	run_cmd "gpio set 14 out_low"
	run_cmd "gpio set 15 out_low"
	run_cmd "gpio set 23 out_low"
	run_cmd "gpio set 26 out_low"
	run_cmd "gpio set 27 out_low"
	run_cmd "gpio set 28 out_low"
	run_cmd "gpio set 29 out_low"
	run_cmd "gpio set 31 out_low"
	run_cmd "emcaprbs_set emca1 xtx4 tx prbs7"
	run_cmd "emcaprbs_set emca1 xtx7 tx prbs7"
	run_cmd "emcaprbs_set emca1 xtx9 tx prbs7"
	run_cmd "emcaprbs_set emca2 xrx6 rx prbs7"
	run_cmd "emcaprbs_set emca2 xrx4 rx prbs7"
	run_cmd "emcaprbs_set emca1 xtx6 tx prbs7"
	run_cmd "emcaprbs_set emca1 xtx8 tx prbs7"
	run_cmd "emcaprbs_set emca2 xrx7 rx prbs7"
	run_cmd "emcaprbs_stats emca2 xrx4 1"
	run_cmd "emcaprbs_set emca2 xrx4 rx off"
	run_cmd "emcaprbs_stats emca2 xrx6 1"
	run_cmd "emcaprbs_set emca2 xrx6 rx off"
	run_cmd "emcaprbs_set emca1 xtx7 tx off"
	run_cmd "emcaprbs_set emca1 xtx9 tx off"
	run_cmd "emcaprbs_set emca2 xrx5 rx prbs7"
	run_cmd "emcaprbs_stats emca2 xrx7 1"
	run_cmd "emcaprbs_set emca2 xrx7 rx off"
	run_cmd "emcaprbs_set emca2 xrx9 rx prbs7"
	run_cmd "emcaprbs_stats emca2 xrx5 1"
	run_cmd "emcaprbs_set emca2 xrx5 rx off"
	run_cmd "emcaprbs_set emca1 xtx6 tx off"
	run_cmd "emcaprbs_set emca1 xtx8 tx off"
	run_cmd "emcaprbs_stats emca2 xrx9 1"
	run_cmd "emcaprbs_set emca2 xrx9 rx off"
	run_cmd "emcaprbs_set emca1 xtx5 tx prbs7"
	run_cmd "emcaprbs_set emca2 xrx8 rx prbs7"
	run_cmd "emcaprbs_set emca1 xtx4 tx off"
	run_cmd "emcaprbs_stats emca2 xrx8 1"
	run_cmd "emcaprbs_set emca2 xrx8 rx off"
	run_cmd "emcaprbs_set emca1 xtx5 tx off"
	run_cmd "phy_init"
	run_cmd "icmtrx_prbsinvert axmb rx invert"
	run_cmd "npuprbs_set tnb tx prbs7"
	run_cmd "icmtrx_prbsinvert axmb tx invert"
	run_cmd "icmtrx_prbsgen axmb 1 1 7"
	run_cmd "icmtrx_prbsinvert axmc rx invert"
	run_cmd "npuprbs_set tnb rx prbs7"
	run_cmd "icmtrx_prbsver axmb 1 1 7"
	run_cmd "icmtrx_prbsinvert axmc tx invert"
	run_cmd "icmtrx_prbsgen axmc 1 1 7"
	run_cmd "npuprbs_set tnc rx prbs7"
	run_cmd "npuprbs_set tnc tx prbs7"
	run_cmd "icmtrx_prbsver axmc 1 1 7"
	run_cmd "npuprbs_status tnc"
	run_cmd "icmtrx_prbsstatus axmb 1"
	run_cmd "npuprbs_set tnc rx off"
	run_cmd "icmtrx_prbsgen axmc 0 1 7"
	run_cmd "icmtrx_prbsstatus axmc 1"
	run_cmd "icmtrx_prbsver axmc 0 1 7"
	run_cmd "icmtrx_prbsver axmb 0 1 7"
	run_cmd "npuprbs_set tnb tx off"
	run_cmd "npuprbs_set tnc tx off"
	run_cmd "npuprbs_status tnb"
	run_cmd "icmtrx_prbsinvert axmc tx normal"
	run_cmd "icmtrx_prbsinvert axmb rx normal"
	run_cmd "npuprbs_set tnb rx off"
	run_cmd "icmtrx_prbsinvert axmc rx normal"
	run_cmd "icmtrx_prbsgen axmb 0 1 7"
	run_cmd "icmtrx_prbsinvert axmb tx normal"
	if [[ $LOOP_IN_FPGA == "enable" ]]
	then
		run_cmd "icmtrx_mode ri2 serial"
	fi
	run_cmd "icmtrx_prbsgen ri2 1 1 7"
	run_cmd "icmtrx_prbsver ri2 1 1 7"
	run_cmd "icmtrx_prbsstatus ri2 1"
	run_cmd "icmtrx_prbsver ri2 0 1 7"
	run_cmd "icmtrx_prbsgen ri2 0 1 7"
	if [[ $LOOP_IN_FPGA == "enable" ]]
	then
		run_cmd "icmtrx_mode tnb serial"
	fi
	run_cmd "icmtrx_prbsgen tnb 1 1 7"
	run_cmd "icmtrx_prbsver tnb 1 1 7"
	run_cmd "icmtrx_prbsstatus tnb 1"
	run_cmd "icmtrx_prbsver tnb 0 1 7"
	run_cmd "icmtrx_prbsgen tnb 0 1 7"
	run_cmd "sfp_power ri2 on"
	##run_cmd "sfp_dump ri2 eeprom"
	##run_cmd "sfp_testio ri2"
	run_cmd "sfp_power ri2 off"
	run_cmd "icm_wr SWRI 0x4c8 0x00000000"
	run_cmd "icm_wr SWRI 0x4c8 0xE000000D"
	run_cmd "icm_rd SWRI 0x4c8"
	run_cmd "icm_wr SWRI 0x4c8 0x00000000"
	run_cmd "icm_rd SWRI 0x500"
	run_cmd "icm_wr SWRI 0x4cc 0x00000001"
	run_cmd "icm_wr SWRI 0x4c8 0xE0000005"
	run_cmd "icm_rd SWRI 0x4c8"
	run_cmd "icm_wr SWRI 0x4c8 0x00000000"
	run_cmd "icm_wr SWRI 0x4c8 0xE000000D"
	run_cmd "icm_wr SWRI 0x4c8 0x00000000"
	run_cmd "icm_rd SWRI 0x500"
	run_cmd "icm_wr swri 0xb04 0x20"
	run_cmd "icm_wr swri 0xb04 0x00"
	run_cmd "icm_wr SWRI 0x4c8 0xE000000D"
	run_cmd "icm_wr SWRI 0x4c8 0x00000000"
	run_cmd "icm_rd SWRI 0x500"
	run_cmd "icm_wr swri 0xb04 0x20"
	run_cmd "icm_wr swri 0xb04 0x00"
	## Remove this, not needed anymore!!
	#run_cmd "initlevel 3"
	## Can't test this
	#run_cmd "mmibutton"

}

conn4() {
	run_cmd "bpm_led_adc"
	run_cmd "led fault on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led fault off"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led op on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led op off"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led maint off"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led maint on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led stat on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led stat off"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led ec on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led ec off"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led lmt off"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led lmt on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led idla on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led idla off"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led idlb on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led idlb off"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led a on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led a off"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led b on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led b off"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led c on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led c off"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led d on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led d off"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led e on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led e off"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led f on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led f off"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led tnb on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led tnb off"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led tnc on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led tnc off"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led sync on"
	run_cmd "bpm_led_adc"
	run_cmd "bpm_led_adc"
	run_cmd "led sync off"
	run_cmd "bpm_led_adc"
	run_cmd "emcaprbs_set emca1 xtx0 tx prbs7"
	run_cmd "emcaprbs_set emca1 xtx2 tx prbs7"
	run_cmd "icmtrx_prbsver xrx2 1 1 7"
	run_cmd "icmtrx_prbsgen xtx22 1 1 7"
	run_cmd "emcaprbs_set emca4 xrx2 rx prbs7"
	run_cmd "icmtrx_prbsgen xtx13 1 1 7"
	run_cmd "icmtrx_prbsgen xtx12 1 1 7"
	run_cmd "emcaprbs_set emca2 xrx2 rx prbs7"
	run_cmd "icmtrx_prbsgen xtx11 1 1 7"
	run_cmd "emcaprbs_set emca2 xrx1 rx prbs7"
	run_cmd "emcaprbs_set emca2 xrx3 rx prbs7"
	run_cmd "icmtrx_prbsgen xtx21 1 1 7"
	run_cmd "emcaprbs_stats emca4 xrx2 1"
	run_cmd "icmtrx_prbsgen xtx18 1 1 7"
	run_cmd "emcaprbs_set emca4 xrx1 rx prbs7"
	run_cmd "emcaprbs_set emca3 xrx4 rx prbs7"
	run_cmd "icmtrx_prbsgen xtx10 1 1 7"
	run_cmd "emcaprbs_set emca4 xrx2 rx off"
	run_cmd "icmtrx_prbsgen xtx9 1 1 7"
	run_cmd "icmtrx_prbsgen xtx17 1 1 7"
	run_cmd "icmtrx_prbsgen xtx8 1 1 7"
	run_cmd "icmtrx_prbsgen xtx15 1 1 7"
	run_cmd "emcaprbs_set emca3 xrx1 rx prbs7"
	run_cmd "emcaprbs_stats emca3 xrx4 1"
	run_cmd "emcaprbs_set emca1 xrx8 rx prbs7"
	run_cmd "emcaprbs_stats emca3 xrx1 1"
	run_cmd "emcaprbs_set emca3 xrx1 rx off"
	run_cmd "icmtrx_prbsgen xtx15 0 1 7"
	run_cmd "emcaprbs_stats emca4 xrx1 1"
	run_cmd "emcaprbs_set emca4 xrx1 rx off"
	run_cmd "icmtrx_prbsgen xtx21 0 1 7"
	run_cmd "emcaprbs_stats emca1 xrx8 1"
	run_cmd "emcaprbs_set emca1 xrx8 rx off"
	run_cmd "icmtrx_prbsgen xtx8 0 1 7"
	run_cmd "emcaprbs_set emca2 xrx0 rx prbs7"
	run_cmd "emcaprbs_set emca3 xrx3 rx prbs7"
	run_cmd "emcaprbs_set emca1 xrx9 rx prbs7"
	run_cmd "icmtrx_prbsgen xtx1 1 1 7"
	run_cmd "emcaprbs_stats emca2 xrx1 1"
	run_cmd "emcaprbs_set emca3 xrx4 rx off"
	run_cmd "icmtrx_prbsgen xtx18 0 1 7"
	run_cmd "emcaprbs_stats emca3 xrx3 1"
	run_cmd "emcaprbs_set emca1 xrx1 rx prbs7"
	run_cmd "emcaprbs_set emca1 xtx1 tx prbs7"
	run_cmd "emcaprbs_set emca3 xrx3 rx off"
	run_cmd "icmtrx_prbsver xrx1 1 1 7"
	run_cmd "emcaprbs_set emca2 xrx1 rx off"
	run_cmd "icmtrx_prbsver xrx0 1 1 7"
	run_cmd "icmtrx_prbsgen xtx7 1 1 7"
	run_cmd "emcaprbs_set emca1 xtx3 tx prbs7"
	run_cmd "icmtrx_prbsgen xtx6 1 1 7"
	run_cmd "emcaprbs_set emca2 xtx0 tx prbs7"
	run_cmd "icmtrx_prbsver xrx3 1 1 7"
	run_cmd "emcaprbs_set emca2 xtx1 tx prbs7"
	run_cmd "icmtrx_prbsgen xtx5 1 1 7"
	run_cmd "icmtrx_prbsver xrx5 1 1 7"
	run_cmd "icmtrx_prbsgen xtx4 1 1 7"
	run_cmd "icmtrx_prbsver xrx4 1 1 7"
	run_cmd "emcaprbs_set emca1 xrx4 rx prbs7"
	run_cmd "emcaprbs_set emca2 xtx3 tx prbs7"
	run_cmd "emcaprbs_set emca2 xtx2 tx prbs7"
	run_cmd "emcaprbs_set emca3 xtx0 tx prbs7"
	run_cmd "emcaprbs_set emca1 xrx5 rx prbs7"
	run_cmd "icmtrx_prbsver xrx7 1 1 7"
	run_cmd "icmtrx_prbsstatus xrx5 1"
	run_cmd "icmtrx_prbsver xrx5 0 1 7"
	run_cmd "icmtrx_prbsver xrx8 1 1 7"
	run_cmd "emcaprbs_set emca2 xtx1 tx off"
	run_cmd "icmtrx_prbsstatus xrx0 1"
	run_cmd "icmtrx_prbsstatus xrx1 1"
	run_cmd "emcaprbs_set emca3 xtx1 tx prbs7"
	run_cmd "icmtrx_prbsstatus xrx4 1"
	run_cmd "icmtrx_prbsver xrx4 0 1 7"
	run_cmd "icmtrx_prbsstatus xrx3 1"
	run_cmd "icmtrx_prbsver xrx3 0 1 7"
	run_cmd "emcaprbs_set emca1 xtx3 tx off"
	run_cmd "emcaprbs_set emca3 xtx2 tx prbs7"
	run_cmd "emcaprbs_set emca3 xtx3 tx prbs7"
	run_cmd "icmtrx_prbsstatus xrx7 1"
	run_cmd "emcaprbs_set emca3 xtx4 tx prbs7"
	run_cmd "icmtrx_prbsver xrx1 0 1 7"
	run_cmd "emcaprbs_set emca3 xtx5 tx prbs7"
	run_cmd "icmtrx_prbsver xrx13 1 1 7"
	run_cmd "icmtrx_prbsver xrx10 1 1 7"
	run_cmd "icmtrx_prbsstatus xrx8 1"
	run_cmd "icmtrx_prbsver xrx8 0 1 7"
	run_cmd "icmtrx_prbsver xrx0 0 1 7"
	run_cmd "emcaprbs_set emca3 xtx0 tx off"
	run_cmd "icmtrx_prbsver xrx12 1 1 7"
	run_cmd "emcaprbs_set emca3 xtx6 tx prbs7"
	run_cmd "icmtrx_prbsver xrx7 0 1 7"
	run_cmd "emcaprbs_set emca3 xtx7 tx prbs7"
	run_cmd "emcaprbs_set emca1 xtx1 tx off"
	run_cmd "emcaprbs_set emca3 xtx8 tx prbs7"
	run_cmd "icmtrx_prbsver xrx11 1 1 7"
	run_cmd "emcaprbs_set emca3 xtx9 tx prbs7"
	run_cmd "emcaprbs_set emca2 xtx0 tx off"
	run_cmd "emcaprbs_set emca2 xtx3 tx off"
	run_cmd "icmtrx_prbsver xrx16 1 1 7"
	run_cmd "icmtrx_prbsstatus xrx10 1"
	run_cmd "emcaprbs_set emca4 xtx0 tx prbs7"
	run_cmd "icmtrx_prbsver xrx18 1 1 7"
	run_cmd "icmtrx_prbsver xrx10 0 1 7"
	run_cmd "icmtrx_prbsver xrx17 1 1 7"
	run_cmd "emcaprbs_stats emca1 xrx4 1"
	run_cmd "icmtrx_prbsver xrx14 1 1 7"
	run_cmd "icmtrx_prbsgen xtx3 1 1 7"
	run_cmd "emcaprbs_set emca4 xtx1 tx prbs7"
	run_cmd "icmtrx_prbsgen xtx2 1 1 7"
	run_cmd "emcaprbs_set emca4 xtx2 tx prbs7"
	run_cmd "icmtrx_prbsgen xtx0 1 1 7"
	run_cmd "emcaprbs_set emca4 xtx3 tx prbs7"
	run_cmd "icmtrx_prbsver xrx21 1 1 7"
	run_cmd "icmtrx_prbsstatus xrx11 1"
	run_cmd "icmtrx_prbsstatus xrx16 1"
	run_cmd "emcaprbs_set emca4 xtx4 tx prbs7"
	run_cmd "icmtrx_prbsstatus xrx12 1"
	run_cmd "icmtrx_prbsver xrx20 1 1 7"
	run_cmd "emcaprbs_set emca3 xtx2 tx off"
	run_cmd "icmtrx_prbsver xrx19 1 1 7"
	run_cmd "emcaprbs_set emca1 xrx4 rx off"
	run_cmd "icmtrx_prbsver xrx15 1 1 7"
	run_cmd "emcaprbs_set emca1 xrx0 rx prbs7"
	run_cmd "icmtrx_prbsstatus xrx13 1"
	run_cmd "emcaprbs_set emca1 xrx2 rx prbs7"
	run_cmd "emcaprbs_set emca1 xtx0 tx off"
	run_cmd "icmtrx_prbsstatus xrx17 1"
	run_cmd "icmtrx_prbsver xrx13 0 1 7"
	run_cmd "icmtrx_prbsstatus xrx14 1"
	run_cmd "emcaprbs_stats emca1 xrx1 1"
	run_cmd "icmtrx_prbsstatus xrx21 1"
	run_cmd "icmtrx_prbsstatus xrx2 1"
	run_cmd "icmtrx_prbsver xrx2 0 1 7"
	run_cmd "icmtrx_prbsver xrx14 0 1 7"
	run_cmd "emcaprbs_set emca3 xtx5 tx off"
	run_cmd "emcaprbs_set emca3 xtx6 tx off"
	run_cmd "emcaprbs_stats emca1 xrx0 1"
	run_cmd "icmtrx_prbsstatus xrx19 1"
	run_cmd "icmtrx_prbsver xrx21 0 1 7"
	run_cmd "emcaprbs_stats emca1 xrx2 1"
	run_cmd "icmtrx_prbsver xrx12 0 1 7"
	run_cmd "emcaprbs_set emca1 xtx2 tx off"
	run_cmd "icmtrx_prbsstatus xrx15 1"
	run_cmd "icmtrx_prbsgen xtx23 1 1 7"
	run_cmd "icmtrx_prbsstatus xrx20 1"
	run_cmd "icmtrx_prbsgen xtx14 1 1 7"
	run_cmd "emcaprbs_set emca1 xrx1 rx off"
	run_cmd "icmtrx_prbsgen xtx16 1 1 7"
	run_cmd "icmtrx_prbsver xrx19 0 1 7"
	run_cmd "emcaprbs_set emca4 xtx1 tx off"
	run_cmd "icmtrx_prbsgen xtx1 0 1 7"
	run_cmd "emcaprbs_set emca3 xtx4 tx off"
	run_cmd "icmtrx_prbsver xrx20 0 1 7"
	run_cmd "emcaprbs_set emca4 xrx3 rx prbs7"
	run_cmd "emcaprbs_set emca1 xrx0 rx off"
	run_cmd "emcaprbs_set emca3 xrx0 rx prbs7"
	run_cmd "icmtrx_prbsver xrx17 0 1 7"
	run_cmd "icmtrx_prbsgen xtx0 0 1 7"
	run_cmd "icmtrx_prbsstatus xrx18 1"
	run_cmd "emcaprbs_set emca1 xrx2 rx off"
	run_cmd "icmtrx_prbsgen xtx2 0 1 7"
	run_cmd "emcaprbs_set emca3 xtx9 tx off"
	run_cmd "emcaprbs_set emca4 xtx2 tx off"
	run_cmd "icmtrx_prbsver xrx15 0 1 7"
	run_cmd "icmtrx_prbsver xrx18 0 1 7"
	run_cmd "emcaprbs_set emca3 xtx7 tx off"
	run_cmd "emcaprbs_set emca4 xtx0 tx off"
	run_cmd "icmtrx_prbsver xrx16 0 1 7"
	run_cmd "icmtrx_prbsver xrx11 0 1 7"
	run_cmd "emcaprbs_set emca3 xtx3 tx off"
	run_cmd "icmtrx_prbsver xrx22 1 1 7"
	run_cmd "emcaprbs_set emca3 xtx8 tx off"
	run_cmd "icmtrx_prbsgen xtx4 0 1 7"
	run_cmd "emcaprbs_set emca3 xrx2 rx prbs7"
	run_cmd "emcaprbs_set emca1 xrx3 rx prbs7"
	run_cmd "emcaprbs_set emca4 xtx3 tx off"
	run_cmd "icmtrx_prbsver xrx9 1 1 7"
	run_cmd "icmtrx_prbsgen xtx19 1 1 7"
	run_cmd "emcaprbs_stats emca1 xrx5 1"
	run_cmd "icmtrx_prbsgen xtx20 1 1 7"
	run_cmd "icmtrx_prbsver xrx6 1 1 7"
	run_cmd "emcaprbs_stats emca2 xrx2 1"
	run_cmd "emcaprbs_set emca1 xrx6 rx prbs7"
	run_cmd "emcaprbs_stats emca2 xrx3 1"
	run_cmd "emcaprbs_set emca1 xrx7 rx prbs7"
	run_cmd "icmtrx_prbsgen xtx22 0 1 7"
	run_cmd "emcaprbs_stats emca4 xrx3 1"
	run_cmd "emcaprbs_set emca3 xrx5 rx prbs7"
	run_cmd "emcaprbs_set emca4 xrx3 rx off"
	run_cmd "icmtrx_prbsgen xtx23 0 1 7"
	run_cmd "emcaprbs_set emca2 xrx3 rx off"
	run_cmd "emcaprbs_set emca2 xrx2 rx off"
	run_cmd "icmtrx_prbsgen xtx12 0 1 7"
	run_cmd "icmtrx_prbsgen xtx13 0 1 7"
	run_cmd "emcaprbs_set emca4 xrx0 rx prbs7"
	run_cmd "emcaprbs_stats emca3 xrx2 1"
	run_cmd "emcaprbs_stats emca3 xrx0 1"
	run_cmd "icmtrx_prbsstatus xrx22 1"
	run_cmd "emcaprbs_set emca1 xrx5 rx off"
	run_cmd "emcaprbs_stats emca1 xrx9 1"
	run_cmd "icmtrx_prbsgen xtx11 0 1 7"
	run_cmd "emcaprbs_stats emca2 xrx0 1"
	run_cmd "icmtrx_prbsgen xtx17 0 1 7"
	run_cmd "icmtrx_prbsver xrx22 0 1 7"
	run_cmd "emcaprbs_stats emca1 xrx6 1"
	run_cmd "emcaprbs_set emca4 xtx4 tx off"
	run_cmd "emcaprbs_set emca1 xrx6 rx off"
	run_cmd "icmtrx_prbsstatus xrx9 1"
	run_cmd "icmtrx_prbsver xrx9 0 1 7"
	run_cmd "emcaprbs_set emca3 xtx1 tx off"
	run_cmd "emcaprbs_stats emca1 xrx7 1"
	run_cmd "emcaprbs_stats emca3 xrx5 1"
	run_cmd "icmtrx_prbsgen xtx6 0 1 7"
	run_cmd "emcaprbs_stats emca1 xrx3 1"
	run_cmd "emcaprbs_set emca3 xrx2 rx off"
	run_cmd "icmtrx_prbsgen xtx5 0 1 7"
	run_cmd "emcaprbs_set emca3 xrx0 rx off"
	run_cmd "emcaprbs_set emca1 xrx9 rx off"
	run_cmd "emcaprbs_stats emca4 xrx0 1"
	run_cmd "emcaprbs_set emca4 xrx0 rx off"
	run_cmd "icmtrx_prbsgen xtx20 0 1 7"
	run_cmd "icmtrx_prbsgen xtx9 0 1 7"
	run_cmd "icmtrx_prbsstatus xrx6 1"
	run_cmd "icmtrx_prbsgen xtx14 0 1 7"
	run_cmd "icmtrx_prbsver xrx6 0 1 7"
	run_cmd "icmtrx_prbsgen xtx16 0 1 7"
	run_cmd "emcaprbs_set emca2 xtx2 tx off"
	run_cmd "emcaprbs_set emca1 xrx7 rx off"
	run_cmd "icmtrx_prbsgen xtx7 0 1 7"
	run_cmd "emcaprbs_set emca2 xrx0 rx off"
	run_cmd "emcaprbs_set emca1 xrx3 rx off"
	run_cmd "icmtrx_prbsgen xtx10 0 1 7"
	run_cmd "emcaprbs_set emca3 xrx5 rx off"
	run_cmd "icmtrx_prbsgen xtx3 0 1 7"
	run_cmd "icmtrx_prbsgen xtx19 0 1 7"
	run_cmd "phy_read tna 0x03"
	if [[ $LOOP_IN_FPGA == "enable" ]]
	then
		run_cmd "icmtrx_mode ri3 serial"
	fi
	run_cmd "icmtrx_prbsgen ri3 1 1 7"
	run_cmd "icmtrx_prbsver ri3 1 1 7"
	run_cmd "icmtrx_prbsstatus ri3 1"
	run_cmd "icmtrx_prbsver ri3 0 1 7"
	run_cmd "icmtrx_prbsgen ri3 0 1 7"
	if [[ $LOOP_IN_FPGA == "enable" ]]
	then
		run_cmd "icmtrx_mode tnc serial"
	fi
	run_cmd "icmtrx_prbsgen tnc 1 1 7"
	run_cmd "icmtrx_prbsver tnc 1 1 7"
	run_cmd "icmtrx_prbsstatus tnc 1"
	run_cmd "icmtrx_prbsver tnc 0 1 7"
	run_cmd "icmtrx_prbsgen tnc 0 1 7"
	run_cmd "sfp_power ri3 on"
	##run_cmd "sfp_dump ri3 eeprom"
	##run_cmd "sfp_testio ri3"
	run_cmd "sfp_power ri3 off"
	run_cmd "npuprbs_set idl0 tx prbs7"
	run_cmd "npuprbs_set idl2 tx prbs7"
	run_cmd "npuprbs_set idl0 rx prbs7"
	run_cmd "npuprbs_set idl2 rx prbs7"
	##run_cmd "npuprbs_status idl0"
	##run_cmd "npuprbs_status idl2"
	run_cmd "npuprbs_set idl0 rx off"
	run_cmd "npuprbs_set idl2 rx off"
	run_cmd "npuprbs_set idl0 tx off"
	run_cmd "npuprbs_set idl2 tx off"
	if [[ $LOOP_IN_FPGA == "enable" ]]
	then
		run_cmd "icmtrx_mode ri6 serial"
	fi
	if [[ $LOOP_IN_FPGA == "enable" ]]
	then
		run_cmd "icmtrx_mode ri7 serial"
	fi
	run_cmd "icmtrx_prbsgen ri6 1 1 7"
	run_cmd "icmtrx_prbsgen ri7 1 1 7"
	run_cmd "icmtrx_prbsver ri6 1 1 7"
	run_cmd "icmtrx_prbsver ri7 1 1 7"
	run_cmd "icmtrx_prbsstatus ri6 1"
	run_cmd "icmtrx_prbsstatus ri7 1"
	run_cmd "icmtrx_prbsver ri6 0 1 7"
	run_cmd "icmtrx_prbsver ri7 0 1 7"
	run_cmd "icmtrx_prbsgen ri6 0 1 7"
	run_cmd "icmtrx_prbsgen ri7 0 1 7"
	##run_cmd "idle_i2cwrite A 0xA2 0x0000 0xCAFE 0xBEEF"
	##run_cmd "idle_i2cread A 0xA2 0x0000 2"
	##run_cmd "idle_i2cwrite A 0xA2 0x0414 0x0002 0x0000 0x00FF"
	##run_cmd "idle_i2cread a 0xA2 0x0406"
	##run_cmd "idle_i2cwrite A 0xA2 0x040E 0x0190"
	##run_cmd "idle_i2cread a 0xA2 0x0406"
	run_cmd "idle_gpio_get A pwr_fail"
	##run_cmd "idle_i2cwrite A 0xA2 0x040E 0x0000"
	run_cmd "idle_gpio_set A present 1"
	run_cmd "idle_gpio_set A sda 1"
	run_cmd "idle_gpio_set A scl 1"
	run_cmd "idle_gpio_get A present"
	run_cmd "idle_gpio_get A sda"
	run_cmd "idle_gpio_get A scl"
	##run_cmd "idle_i2cwrite A 0xA2 0x0410 0x0001 0x03E8"
	run_cmd "idle_gpio_get A present"
	##run_cmd "idle_i2cwrite A 0xA2 0x0410 0x0000"
	run_cmd "idle_gpio_set A led 1"
	run_cmd "idle_gpio_get A led"
	run_cmd "idle_gpio_set A led 0"
	run_cmd "idle_gpio_get A led"
}

conn5() {
	run_cmd "icmtrx_power et0 1 q"
	run_cmd "icmtrx_power et1 1 q"
	run_cmd "icmtrx_power et2 1 q"
	run_cmd "icmtrx_power et3 1 q"
	run_cmd "icmtrx_power et4 1 q"
	run_cmd "icmtrx_power et5 1 q"
	run_cmd "icmtrx_power et6 1 q"
	run_cmd "icmtrx_power et7 1 q"
	run_cmd "icmtrx_prbsinvert et0 tx invert"
	run_cmd "icmtrx_prbsinvert et2 tx invert"
	run_cmd "icmtrx_prbsinvert et7 rx invert"
	run_cmd "icmtrx_prbsinvert et1 rx invert"
	run_cmd "icmtrx_prbsinvert et7 tx invert"
	run_cmd "icmtrx_prbsinvert et1 tx invert"
	run_cmd "icmtrx_prbsinvert et6 rx invert"
	run_cmd "icmtrx_prbsinvert et0 rx invert"
	run_cmd "emcaprbs_set emca4 et6 tx prbs7"
	run_cmd "icmtrx_prbsgen et0 1 1 7"
	run_cmd "icmtrx_prbsinvert et5 rx invert"
	run_cmd "icmtrx_prbsinvert et2 rx invert"
	run_cmd "emcaprbs_set emca2 et4 tx prbs7"
	run_cmd "icmtrx_prbsinvert et3 tx invert"
	run_cmd "icmtrx_prbsver et2 1 1 7"
	run_cmd "icmtrx_prbsgen et3 1 1 7"
	run_cmd "emcaprbs_set emca1 et2 rx prbs7"
	run_cmd "emcaprbs_set emca2 et5 rx prbs7"
	run_cmd "icmtrx_prbsver et6 1 1 7"
	run_cmd "emcaprbs_set emca3 et7 tx prbs7"
	run_cmd "emcaprbs_set emca1 et3 tx prbs7"
	run_cmd "icmtrx_prbsinvert et3 rx invert"
	run_cmd "icmtrx_prbsgen et7 1 1 7"
	run_cmd "icmtrx_prbsinvert et4 tx invert"
	run_cmd "icmtrx_prbsgen et2 1 1 7"
	run_cmd "icmtrx_prbsinvert et4 rx invert"
	run_cmd "emcaprbs_set emca1 et2 tx prbs7"
	run_cmd "icmtrx_prbsinvert et5 tx invert"
	run_cmd "icmtrx_prbsinvert et6 tx invert"
	run_cmd "icmtrx_prbsgen et6 1 1 7"
	run_cmd "emcaprbs_set emca4 et6 rx prbs7"
	run_cmd "emcaprbs_set emca4 et7 rx prbs7"
	run_cmd "emcaprbs_set emca2 et4 rx prbs7"
	run_cmd "icmtrx_prbsgen et5 1 1 7"
	run_cmd "emcaprbs_set emca3 et7 rx prbs7"
	run_cmd "icmtrx_prbsgen et4 1 1 7"
	run_cmd "icmtrx_prbsver et1 1 1 7"
	run_cmd "icmtrx_prbsstatus et6 1"
	run_cmd "emcaprbs_set emca3 et6 tx prbs7"
	run_cmd "icmtrx_prbsver et0 1 1 7"
	run_cmd "icmtrx_prbsstatus et2 1"
	run_cmd "emcaprbs_set emca2 et5 tx prbs7"
	run_cmd "emcaprbs_stats emca2 et5 1"
	run_cmd "icmtrx_prbsver et5 1 1 7"
	run_cmd "emcaprbs_stats emca1 et2 1"
	run_cmd "icmtrx_prbsgen et1 1 1 7"
	run_cmd "emcaprbs_set emca4 et7 tx prbs7"
	run_cmd "emcaprbs_set emca3 et6 rx prbs7"
	run_cmd "emcaprbs_stats emca4 et7 1"
	run_cmd "emcaprbs_set emca1 et2 rx off"
	run_cmd "icmtrx_prbsgen et0 0 1 7"
	run_cmd "emcaprbs_set emca4 et7 rx off"
	run_cmd "icmtrx_prbsgen et7 0 1 7"
	run_cmd "icmtrx_prbsinvert et0 tx normal"
	run_cmd "icmtrx_prbsinvert et7 tx normal"
	run_cmd "icmtrx_prbsver et3 1 1 7"
	run_cmd "emcaprbs_set emca2 et5 rx off"
	run_cmd "icmtrx_prbsver et2 0 1 7"
	run_cmd "icmtrx_prbsgen et3 0 1 7"
	run_cmd "icmtrx_prbsver et4 1 1 7"
	run_cmd "icmtrx_prbsver et7 1 1 7"
	run_cmd "icmtrx_prbsver et6 0 1 7"
	run_cmd "emcaprbs_set emca1 et3 rx prbs7"
	run_cmd "emcaprbs_stats emca4 et6 1"
	run_cmd "emcaprbs_stats emca2 et4 1"
	run_cmd "emcaprbs_set emca2 et4 tx off"
	run_cmd "icmtrx_prbsinvert et2 rx normal"
	run_cmd "emcaprbs_stats emca3 et6 1"
	run_cmd "emcaprbs_stats emca3 et7 1"
	run_cmd "emcaprbs_set emca3 et6 rx off"
	run_cmd "emcaprbs_set emca3 et7 rx off"
	run_cmd "icmtrx_prbsgen et4 0 1 7"
	run_cmd "icmtrx_prbsgen et5 0 1 7"
	run_cmd "icmtrx_prbsstatus et3 1"
	run_cmd "icmtrx_prbsinvert et3 tx normal"
	run_cmd "emcaprbs_set emca2 et4 rx off"
	run_cmd "icmtrx_prbsstatus et0 1"
	run_cmd "emcaprbs_set emca4 et6 tx off"
	run_cmd "emcaprbs_set emca4 et6 rx off"
	run_cmd "icmtrx_prbsstatus et1 1"
	run_cmd "icmtrx_prbsstatus et5 1"
	run_cmd "icmtrx_prbsinvert et4 tx normal"
	run_cmd "icmtrx_prbsgen et2 0 1 7"
	run_cmd "icmtrx_prbsinvert et2 tx normal"
	run_cmd "icmtrx_prbsver et1 0 1 7"
	run_cmd "icmtrx_prbsgen et6 0 1 7"
	run_cmd "emcaprbs_set emca1 et3 tx off"
	run_cmd "icmtrx_prbsinvert et6 tx normal"
	run_cmd "icmtrx_prbsinvert et1 rx normal"
	run_cmd "icmtrx_prbsinvert et6 rx normal"
	run_cmd "emcaprbs_stats emca1 et3 1"
	run_cmd "icmtrx_prbsstatus et7 1"
	run_cmd "emcaprbs_set emca1 et3 rx off"
	run_cmd "icmtrx_prbsver et7 0 1 7"
	run_cmd "icmtrx_prbsgen et1 0 1 7"
	run_cmd "icmtrx_prbsstatus et4 1"
	run_cmd "icmtrx_prbsver et0 0 1 7"
	run_cmd "icmtrx_prbsver et5 0 1 7"
	run_cmd "icmtrx_prbsver et3 0 1 7"
	run_cmd "icmtrx_prbsinvert et5 tx normal"
	run_cmd "icmtrx_prbsinvert et1 tx normal"
	run_cmd "emcaprbs_set emca1 et2 tx off"
	run_cmd "emcaprbs_set emca4 et7 tx off"
	run_cmd "icmtrx_prbsinvert et0 rx normal"
	run_cmd "icmtrx_prbsinvert et7 rx normal"
	run_cmd "emcaprbs_set emca2 et5 tx off"
	run_cmd "icmtrx_prbsver et4 0 1 7"
	run_cmd "icmtrx_prbsinvert et3 rx normal"
	run_cmd "emcaprbs_set emca3 et6 tx off"
	run_cmd "emcaprbs_set emca3 et7 tx off"
	run_cmd "icmtrx_prbsinvert et4 rx normal"
	run_cmd "icmtrx_prbsinvert et5 rx normal"
	##run_cmd "loop_port 9 0x000000a1"
	##run_cmd "loop_port 20 0x000000a2"
	##run_cmd "loop_port 22 0x000000a3"
	run_cmd "ecb_addr_pins"
	run_cmd "ecb_addr_pins"
	if [[ $LOOP_IN_FPGA == "enable" ]]
	then
		run_cmd "icmtrx_mode ri4 serial"
	fi
	run_cmd "icmtrx_prbsgen ri4 1 1 7"
	run_cmd "icmtrx_prbsinvert ea tx invert"
	run_cmd "icmtrx_prbsver ri4 1 1 7"
	run_cmd "icmtrx_prbsgen ea 1 1 7"
	run_cmd "npuprbs_set ea rx prbs7"
	run_cmd "icmtrx_prbsinvert ea rx invert"
	run_cmd "icmtrx_prbsstatus ri4 1"
	run_cmd "npuprbs_set ea tx prbs7"
	run_cmd "icmtrx_prbsver ri4 0 1 7"
	run_cmd "icmtrx_prbsver ea 1 1 7"
	run_cmd "icmtrx_prbsgen ri4 0 1 7"
	run_cmd "npuprbs_status ea"
	run_cmd "npuprbs_set ea rx off"
	run_cmd "icmtrx_prbsgen ea 0 1 7"
	run_cmd "icmtrx_prbsinvert ea tx normal"
	run_cmd "icmtrx_prbsstatus ea 1"
	run_cmd "icmtrx_prbsver ea 0 1 7"
	run_cmd "npuprbs_set ea tx off"
	run_cmd "icmtrx_prbsinvert ea rx normal"
	run_cmd "sfp_power ri4 on"
	##run_cmd "sfp_dump ri4 eeprom"
	##run_cmd "sfp_testio ri4"
	run_cmd "sfp_power ri4 off"
	run_cmd "npuprbs_set idl1 tx prbs7"
	run_cmd "npuprbs_set idl3 tx prbs7"
	run_cmd "npuprbs_set idl1 rx prbs7"
	run_cmd "npuprbs_set idl3 rx prbs7"
	##run_cmd "npuprbs_status idl1"
	##run_cmd "npuprbs_status idl3"
	run_cmd "npuprbs_set idl1 rx off"
	run_cmd "npuprbs_set idl3 rx off"
	run_cmd "npuprbs_set idl1 tx off"
	run_cmd "npuprbs_set idl3 tx off"
	if [[ $LOOP_IN_FPGA == "enable" ]]
	then
		run_cmd "icmtrx_mode ri8 serial"
	fi
	if [[ $LOOP_IN_FPGA == "enable" ]]
	then
		run_cmd "icmtrx_mode ri9 serial"
	fi
	run_cmd "icmtrx_prbsgen ri8 1 1 7"
	run_cmd "icmtrx_prbsgen ri9 1 1 7"
	run_cmd "icmtrx_prbsver ri8 1 1 7"
	run_cmd "icmtrx_prbsver ri9 1 1 7"
	run_cmd "icmtrx_prbsstatus ri8 1"
	run_cmd "icmtrx_prbsstatus ri9 1"
	run_cmd "icmtrx_prbsver ri8 0 1 7"
	run_cmd "icmtrx_prbsver ri9 0 1 7"
	run_cmd "icmtrx_prbsgen ri8 0 1 7"
	run_cmd "icmtrx_prbsgen ri9 0 1 7"
	##run_cmd "idle_i2cwrite B 0xA2 0x0000 0xCAFE 0xBEEF"
	##run_cmd "idle_i2cread B 0xA2 0x0000 2"
	##run_cmd "idle_i2cwrite B 0xA2 0x0414 0x0002 0x0000 0x00FF"
	##run_cmd "idle_i2cread a 0xA2 0x0406"
	##run_cmd "idle_i2cwrite B 0xA2 0x040E 0x0190"
	##run_cmd "idle_i2cread a 0xA2 0x0406"
	run_cmd "idle_gpio_get B pwr_fail"
	##run_cmd "idle_i2cwrite B 0xA2 0x040E 0x0000"
	run_cmd "idle_gpio_set B present 1"
	run_cmd "idle_gpio_set B sda 1"
	run_cmd "idle_gpio_set B scl 1"
	run_cmd "idle_gpio_get B present"
	run_cmd "idle_gpio_get B sda"
	run_cmd "idle_gpio_get B scl"
	##run_cmd "idle_i2cwrite B 0xA2 0x0410 0x0001 0x03E8"
	run_cmd "idle_gpio_get B present"
	##run_cmd "idle_i2cwrite B 0xA2 0x0410 0x0000"
	run_cmd "idle_gpio_set B led 1"
	run_cmd "idle_gpio_get B led"
	run_cmd "idle_gpio_set B led 0"
	run_cmd "idle_gpio_get B led"
}

conn6() {
	if [[ $LOOP_IN_FPGA == "enable" ]]
	then
		run_cmd "icmtrx_mode ri5 serial"
	fi
	run_cmd "icmtrx_prbsgen ri5 1 1 7"
	run_cmd "icmtrx_prbsver ri5 1 1 7"
	run_cmd "icmtrx_prbsstatus ri5 1"
	run_cmd "icmtrx_prbsver ri5 0 1 7"
	run_cmd "icmtrx_prbsgen ri5 0 1 7"
	run_cmd "sfp_power ri5 on"
	##run_cmd "sfp_dump ri5 eeprom"
	##run_cmd "sfp_testio ri5"
	run_cmd "sfp_power ri5 off"
}


conn7() {

	run_cmd "sfp_power tnb on"
	##run_cmd "sfp_dump tnb eeprom"
	##run_cmd "sfp_testio tnb"
	run_cmd "sfp_power tnb off"

}


conn8() {

	run_cmd "sfp_power tnc on"
	##run_cmd "sfp_dump tnc eeprom"
	##run_cmd "sfp_testio tnc"
	run_cmd "sfp_power tnc off"
}

serial() {
	run_cmd "tnport_setup tna"
	run_cmd "phy_mode tna copper_loop"
	run_cmd "npu_refclksel tna btn"
	run_cmd "nputrf_rxstart tna verify"
	run_cmd "nputrf_txstart tna 100 32"
	run_cmd "nputrf_stats tna"
	run_cmd "nputrf_txstop tna"
	run_cmd "nputrf_rxstop tna"
	run_cmd "nputrf_stats tna clear"
	run_cmd "npu_refclksel tna brbs"
	run_cmd "nputrf_rxstart tna verify"
	run_cmd "nputrf_txstart tna 100 32"
	run_cmd "nputrf_stats tna"
	run_cmd "nputrf_txstop tna"
	run_cmd "nputrf_rxstop tna"
	run_cmd "nputrf_stats tna clear"
	run_cmd "phy_mode tna normal"
	if [ "$ICMTYPE" == "STRATIX" ]
	then
		run_cmd "--wait bscan -o=rm:4vt:1rf:/var/volatile/DUS52_ROA_1_R5C. txt -s /home/sirpa/DUS52_ROA_1_R5C.svf -c"
	fi
	

}

# TODO
# Script not working on dus32, need to be updated....
#if [ "$BOARDTYPE" == "DUS5201" -o "$BOARDTYPE" == "DUS3201" ]
if [ "$BOARDTYPE" == "DUS5201" ]
then
    run_cmd "--clear all"
    serial
    conn1
    conn2
    conn3
    conn4
    conn5
    conn6
    conn7
    conn8
    run_cmd "--status"
fi
if [ "$BOARDTYPE" == "DUS3201" ]
then
   echo "Need to implement for dus32 board"
   echo "Making it pass by default :: TESTBOX_PASS"
fi

