#!/bin/bash

echo "$0"

## Find out which boardtype
SCRIPTDIR=$(dirname $0);
source $SCRIPTDIR/hwt-util.sh

BOARDTYPE=$(get_boardtype);
echo "$BOARDTYPE";

run_t_cmd(){
        cmd=$1

        echo "-----------------------------------------------------------------"
        echo -e "testbox $cmd"
        testbox $cmd
        echo "-----------------------------------------------------------------"
}

run_cmd(){
        cmd=$1

        echo "-----------------------------------------------------------------"
        echo -e "$cmd"
        $cmd
        echo "-----------------------------------------------------------------"
}

prod_test_tcu03()  {

    run_t_cmd "icm_status"
#    run_t_cmd "hw_status"
    run_t_cmd "status"

    run_t_cmd "bpm_pgood_status"
    run_t_cmd "bpm_power_status 0"
    run_t_cmd "icm_load ssp"
    run_t_cmd "i2c_test 7 /dev/i2c-0 1 0x41 2"
    run_t_cmd "icm_load cvp"
    run_t_cmd "i2c_test 7 /dev/i2c-0 1 0x41 2"
    run_t_cmd "icm_rd swri 54"
    run_t_cmd "icm_wr swri 54 0x00"
    run_t_cmd "icm_rd swri 54"
    run_t_cmd "icm_load ssp"
    run_t_cmd "icm_load cvp"
    run_t_cmd "icm_rd swri 54"
    run_t_cmd "icm_status"
    run_t_cmd "npu_load frog"
    run_t_cmd "npucmem_test -C 0 -e 1 -f 1 -m 0 -p 0"
    run_t_cmd "npucmem_test -C 1 -e 1 -f 1 -m 0 -p 0"
    run_t_cmd "npucmem_test -C 0 -e 1 -f 1 -m 0 -p 1"
    run_t_cmd "npucmem_test -C 1 -e 1 -f 1 -m 0 -p 1"

# We do not need to fail if ecc counters != 0
#    run_t_cmd "eccstat --test"
    run_t_cmd "eccstat"

    run_cmd "ncpWrite 0x8.0x9.0x48 0x4"
    run_cmd "ncpWrite 0x8.0x9.0x48 0x5"
    run_cmd "ncpExtMemBist -C 0"
    run_cmd "ncpWrite 0x8.0x9.0x48 0x4"
# Inject ECC double bit error
# Test below should fail (correct behavior)
    run_cmd "ncpWrite 0x8.0x9.0x48 0x7"
    run_cmd "ncpExtMemBist -C 0"
    run_cmd "ncpWrite 0x9.0x9.0x48 0x4"
    run_cmd "ncpWrite 0x9.0x9.0x48 0x5"
    run_cmd "ncpExtMemBist -C 1"
    run_cmd "ncpWrite 0x9.0x9.0x48 0x4"
# Inject ECC double bit error
# Test below should fail (correct behavior)
    run_cmd "ncpWrite 0x9.0x9.0x48 0x7"
    run_cmd "ncpExtMemBist -C 1"

# We do not need to fail if ecc counters != 0
#    run_t_cmd "eccstat --test"
    run_t_cmd "eccstat"

    run_t_cmd "gpio get 4"
    run_t_cmd "gpio get 5"
    run_t_cmd "gpio get 6"
    run_t_cmd "gpio get 12"
    run_t_cmd "gpio get 13"
    run_t_cmd "gpio get 14"
    run_t_cmd "gpio get 15"
    run_t_cmd "gpio get 23"
    run_t_cmd "gpio get 26"
    run_t_cmd "gpio get 27"
    run_t_cmd "gpio get 28"
    run_t_cmd "gpio get 29"
    run_t_cmd "gpio get 31"
    run_t_cmd "gpio set 4 out_high"
    run_t_cmd "gpio set 5 out_high"
    run_t_cmd "gpio set 6 out_high"
    run_t_cmd "gpio set 12 out_high"
    run_t_cmd "gpio set 13 out_high"
    run_t_cmd "gpio set 14 out_high"
    run_t_cmd "gpio set 15 out_high"
    run_t_cmd "gpio set 23 out_high"
    run_t_cmd "gpio set 26 out_high"
    run_t_cmd "gpio set 27 out_high"
    run_t_cmd "gpio set 28 out_high"
    run_t_cmd "gpio set 29 out_high"
    run_t_cmd "gpio set 31 out_high"
    run_t_cmd "gpio set 4 out_low"
    run_t_cmd "gpio set 5 out_low"
    run_t_cmd "gpio set 6 out_low"
    run_t_cmd "gpio set 12 out_low"
    run_t_cmd "gpio set 13 out_low"
    run_t_cmd "gpio set 14 out_low"
    run_t_cmd "gpio set 15 out_low"
    run_t_cmd "gpio set 23 out_low"
    run_t_cmd "gpio set 26 out_low"
    run_t_cmd "gpio set 27 out_low"
    run_t_cmd "gpio set 28 out_low"
    run_t_cmd "gpio set 29 out_low"
    run_t_cmd "gpio set 31 out_low"
    run_t_cmd "nor_test_rw"

    run_t_cmd "syntamult_read 0x0006"
    run_t_cmd "syntmod_read RBS 0x001"
    run_t_cmd "syntmod_write RBS 0x001 0xf1"
    run_t_cmd "syntmod_read RBS 0x001"
    run_t_cmd "syntmod_write RBS 0x001 0xa014"
    run_t_cmd "syntmod_read RBS 0x001"
    run_t_cmd "syntfpll_read RBS 0x0000"
    run_t_cmd "syntfpll_write RBS 0x0000 0xf1"
    run_t_cmd "syntfpll_read RBS 0x0000"
    run_t_cmd "syntfpll_write RBS 0x0000 0x6010001"
    run_t_cmd "syntfpll_read RBS 0x0000"
    run_t_cmd "syntmod_read TN 0x001"
    run_t_cmd "syntmod_write TN 0x001 0xf1"
    run_t_cmd "syntmod_read TN 0x001"
    run_t_cmd "syntmod_write TN 0x001 0xa014"
    run_t_cmd "syntmod_read TN 0x001"
    run_t_cmd "syntfpll_read TN 0x0000"
    run_t_cmd "syntfpll_write TN 0x0000 0xf1"
    run_t_cmd "syntfpll_read TN 0x0000"
    run_t_cmd "syntfpll_write TN 0x0000 0x6010001"
    run_t_cmd "syntfpll_read TN 0x0000"
    run_t_cmd "synth_init"
    run_t_cmd "syntaocxo_dump"
    run_t_cmd "syntaocxo_temp_sensor"
    run_t_cmd "syntaocxo_checksum"

#  not possible to execute with no external sync source
#    run_t_cmd "turef_status sync"
#    run_t_cmd "turef_status sync"

    run_t_cmd "generate_freq 9"
    run_t_cmd "synth_status"
    run_t_cmd "icm_rd swri b08"

    run_t_cmd "turef_status"
    run_t_cmd "turef_status rbs"

    run_t_cmd "phy_init"
    run_t_cmd "retimer_init"

    run_t_cmd "phy_read tnj 0x00"
    run_t_cmd "phy_write tnj 0x00 0x1000"
    run_t_cmd "phy_read tnj 0x00"
    run_t_cmd "icm_wr tn 0x0410 0x0"
    run_t_cmd "icm_wr tn 0x0410 0x1"
    run_t_cmd "phy_read tnj 0x00"
    run_t_cmd "phy_read tnk 0x00"
    run_t_cmd "phy_write tnk 0x00 0x1000"
    run_t_cmd "phy_read tnk 0x00"
    run_t_cmd "icm_wr tn 0x0510 0x0"
    run_t_cmd "icm_wr tn 0x0510 0x1"
    run_t_cmd "phy_read tnk 0x00"
    run_t_cmd "phy_read tnl 0x00"
    run_t_cmd "phy_write tnl 0x00 0x1000"
    run_t_cmd "phy_read tnl 0x00"
    run_t_cmd "icm_wr tn 0x0610 0x0"
    run_t_cmd "icm_wr tn 0x0610 0x1"
    run_t_cmd "phy_read tnl 0x00"
    run_t_cmd "phy_read tnj 0x03"
    run_t_cmd "phy_read tnk 0x03"
    run_t_cmd "phy_read tnl 0x03"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "gpio set 12 out_high"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "gpio set 12 out_low"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "gpio set 13 out_high"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "gpio set 13 out_low"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "gpio set 14 out_high"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "gpio set 14 out_low"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "gpio set 15 out_high"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "gpio set 15 out_low"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 1"
    run_t_cmd "bpm_led_adc 1"
    run_t_cmd "bpm_led_adc 1"
    run_t_cmd "bpm_led_adc 1"
    run_t_cmd "bpm_led_adc 1"
    run_t_cmd "bpm_led_adc 1"
    run_t_cmd "bpm_led_adc 1"
    run_t_cmd "bpm_led_adc 1"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "icm_wr SWRI 0x90c 1"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "icm_wr SWRI 0x90c 0"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "led lmt off"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "led lmt on"

# Change to general 'testbox led' command later on.
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "icm_wr SWRI 0x90c 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "icm_wr SWRI 0x90c 0"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "sfp_led tna on"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "sfp_led tna off"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "sfp_led tnb on"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "sfp_led tnb off"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "sfp_led tnc on"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "sfp_led tnc off"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "sfp_led tnd on"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "sfp_led tnd off"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "sfp_led tne on"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "sfp_led tne off"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "sfp_led tnf on"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "sfp_led tnf off"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "sfp_led tng on"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "sfp_led tng off"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "sfp_led tnh on"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "sfp_led tnh off"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "phy_led tnj on"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "phy_led tnj off"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "phy_led tnk on"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "phy_led tnk off"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "phy_led tnl on"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "bpm_led_adc 2"
    run_t_cmd "phy_led tnl off"
    run_t_cmd "bpm_led_adc 2"

    run_t_cmd "led sync on"
    run_t_cmd "led ec on"
    run_t_cmd "led fault on"
    run_t_cmd "led op on"
    run_t_cmd "led maint on"
    run_t_cmd "led stat on"
    run_t_cmd "led stat off"
    run_t_cmd "led maint off"
    run_t_cmd "led fault off"
    run_t_cmd "led op off"
    run_t_cmd "led ec off"
    run_t_cmd "led sync off"

    run_t_cmd "phy_rst_test tnk"
    run_t_cmd "phy_rst_test tnl"
    run_t_cmd "phy_ident tnk"
    run_t_cmd "phy_ident tnl"
    run_t_cmd "retimer_read tna 0x000"
    run_t_cmd "retimer_write tna 0x000 0x12"
    run_t_cmd "retimer_read tna 0x000"
    run_t_cmd "retimer_write tna 0x000 0x0"
    run_t_cmd "retimer_read tna 0x000"
    run_t_cmd "retimer_read tnb 0x000"
    run_t_cmd "retimer_write tnb 0x000 0x12"
    run_t_cmd "retimer_read tnb 0x000"
    run_t_cmd "retimer_write tnb 0x000 0x0"
    run_t_cmd "retimer_read tnb 0x000"
    run_t_cmd "retimer_read tnc 0x000"
    run_t_cmd "retimer_write tnc 0x000 0x12"
    run_t_cmd "retimer_read tnc 0x000"
    run_t_cmd "retimer_write tnc 0x000 0x0"
    run_t_cmd "retimer_read tnc 0x000"
    run_t_cmd "retimer_read tnd 0x000"
    run_t_cmd "retimer_write tnd 0x000 0x12"
    run_t_cmd "retimer_read tnd 0x000"
    run_t_cmd "retimer_write tnd 0x000 0x0"
    run_t_cmd "retimer_read tnd 0x000"
    run_t_cmd "retimer_read tne 0x000"
    run_t_cmd "retimer_write tne 0x000 0x12"
    run_t_cmd "retimer_read tne 0x000"
    run_t_cmd "retimer_write tne 0x000 0x0"
    run_t_cmd "retimer_read tne 0x000"

    run_cmd "rm -f /var/volatile/TCU03_ROA_1_R3D.txt"
    run_t_cmd "--wait bscan -o=rm:4vt:1rf:/var/volatile/TCU03_ROA_1_R3D.txt -s /home/sirpa/TCU03_ROA_1_R3D.svf -c"
    run_cmd "cat /var/volatile/TCU03_ROA_1_R3D.txt"

# loop_port not possible to execute without loop plug/cable
#    run_t_cmd "loop_port 9 0x000000a1"
#    run_t_cmd "loop_port 18 0x000000a2"
# do simple verify that command exist...
    run_t_cmd "loop_port -h"

    run_t_cmd "ecb_addr_pins"
    run_t_cmd "ecb_addr_pins"
    run_t_cmd "icmtrx_prbsinvert axme rx invert"
    run_t_cmd "npuprbs_set tne tx prbs7"
    run_t_cmd "icmtrx_prbsver axme 1 1 7"
    run_t_cmd "icmtrx_prbsstatus axme 1"
    run_t_cmd "icmtrx_prbsver axme 0 1 7"
    run_t_cmd "npuprbs_set tne tx off"
    run_t_cmd "icmtrx_prbsinvert axme rx normal"
    run_t_cmd "icmtrx_prbsinvert axme tx invert"
    run_t_cmd "icmtrx_prbsgen axme 1 1 7"
    run_t_cmd "npuprbs_set tne rx prbs7"
    run_t_cmd "npuprbs_status tne 1"
    run_t_cmd "npuprbs_set tne rx off"
    run_t_cmd "icmtrx_prbsgen axme 0 1 7"
    run_t_cmd "icmtrx_prbsinvert axme tx normal"
    run_t_cmd "npuprbs_set tnf tx prbs15"
    run_t_cmd "npuprbs_set tng tx prbs15"
    run_t_cmd "npuprbs_set tnh tx prbs15"
    run_t_cmd "npuprbs_set tnj tx prbs15"
    run_t_cmd "npuprbs_set tnk tx prbs15"
    run_t_cmd "npuprbs_set tnl tx prbs15"
    run_t_cmd "icmtrx_prbsgen axmf 1 1 15"
    run_t_cmd "icmtrx_prbsgen axmg 1 1 15"
    run_t_cmd "icmtrx_prbsgen axmh 1 1 15"
    run_t_cmd "icmtrx_prbsgen axmj 1 1 15"
    run_t_cmd "icmtrx_prbsgen axmk 1 1 15"
    run_t_cmd "icmtrx_prbsgen axml 1 1 15"
    run_t_cmd "icmtrx_prbsver axmf 1 1 15"
    run_t_cmd "icmtrx_prbsver axmg 1 1 15"
    run_t_cmd "icmtrx_prbsver axmh 1 1 15"
    run_t_cmd "icmtrx_prbsver axmj 1 1 15"
    run_t_cmd "icmtrx_prbsver axmk 1 1 15"
    run_t_cmd "icmtrx_prbsver axml 1 1 15"
    run_t_cmd "npuprbs_set tnf rx prbs15"
    run_t_cmd "npuprbs_set tng rx prbs15"
    run_t_cmd "npuprbs_set tnh rx prbs15"
    run_t_cmd "npuprbs_set tnj rx prbs15"
    run_t_cmd "npuprbs_set tnk rx prbs15"
    run_t_cmd "npuprbs_set tnl rx prbs15"
    run_t_cmd "icmtrx_prbsstatus axmf 1"
    run_t_cmd "icmtrx_prbsstatus axmg 1"
    run_t_cmd "icmtrx_prbsstatus axmh 1"
    run_t_cmd "icmtrx_prbsstatus axmj 1"
    run_t_cmd "icmtrx_prbsstatus axmk 1"
    run_t_cmd "icmtrx_prbsstatus axml 1"
    run_t_cmd "npuprbs_status tnf 1"
    run_t_cmd "npuprbs_status tng 1"
    run_t_cmd "npuprbs_status tnh 1"
    run_t_cmd "npuprbs_status tnj 1"
    run_t_cmd "npuprbs_status tnk 1"
    run_t_cmd "npuprbs_status tnl 1"
    run_t_cmd "icmtrx_prbsver axmf 0 1 15"
    run_t_cmd "icmtrx_prbsver axmg 0 1 15"
    run_t_cmd "icmtrx_prbsver axmh 0 1 15"
    run_t_cmd "icmtrx_prbsver axmj 0 1 15"
    run_t_cmd "icmtrx_prbsver axmk 0 1 15"
    run_t_cmd "icmtrx_prbsver axml 0 1 15"
    run_t_cmd "npuprbs_set tnf rx off"
    run_t_cmd "npuprbs_set tng rx off"
    run_t_cmd "npuprbs_set tnh rx off"
    run_t_cmd "npuprbs_set tnj rx off"
    run_t_cmd "npuprbs_set tnk rx off"
    run_t_cmd "npuprbs_set tnl rx off"
    run_t_cmd "npuprbs_set tnf tx off"
    run_t_cmd "npuprbs_set tng tx off"
    run_t_cmd "npuprbs_set tnh tx off"
    run_t_cmd "npuprbs_set tnj tx off"
    run_t_cmd "npuprbs_set tnk tx off"
    run_t_cmd "npuprbs_set tnl tx off"
    run_t_cmd "icmtrx_prbsgen axmf 0 1 15"
    run_t_cmd "icmtrx_prbsgen axmg 0 1 15"
    run_t_cmd "icmtrx_prbsgen axmh 0 1 15"
    run_t_cmd "icmtrx_prbsgen axmj 0 1 15"
    run_t_cmd "icmtrx_prbsgen axmk 0 1 15"
    run_t_cmd "icmtrx_prbsgen axml 0 1 15"

    run_t_cmd "phy_init"
    run_t_cmd "tud_timesync phy"
    run_t_cmd "phy_readhbts tnj"
    run_t_cmd "phy_readhbts tnk"
    run_t_cmd "phy_readhbts tnl"
    run_t_cmd "phy_rdb_read tnj 0xa5a | sed 's/^\\(0x\\(0\\+\\|[Ff]\\4\\ \\)\\)$/\\1 PLL_LOCKED/'"
    run_t_cmd "phy_rdb_read tnj 0xa59 | sed 's/^\\(0x\\(0*\\|[Ff]\\3\\\\ )[0-9a-fA-F]\\)$/\\1 PLL_LOCKED/'"
    run_t_cmd "phy_rdb_read tnk 0xa5a | sed 's/^\\(0x\\(0\\+\\|[Ff]\\4\\ \\)\\)$/\\1 PLL_LOCKED/'"
    run_t_cmd "phy_rdb_read tnk 0xa59 | sed 's/^\\(0x\\(0*\\|[Ff]\\3\\\\ )[0-9a-fA-F]\\)$/\\1 PLL_LOCKED/'"
    run_t_cmd "phy_rdb_read tnl 0xa5a | sed 's/^\\(0x\\(0\\+\\|[Ff]\\4\\ \\)\\)$/\\1 PLL_LOCKED/'"
    run_t_cmd "phy_rdb_read tnl 0xa59 | sed 's/^\\(0x\\(0*\\|[Ff]\\3\\\\ )[0-9a-fA-F]\\)$/\\1 PLL_LOCKED/'"
    run_t_cmd "phy_readhbts tnj"
    run_t_cmd "phy_readhbts tnk"
    run_t_cmd "phy_readhbts tnl"
    run_t_cmd "tud_timesync phy"
    run_t_cmd "phy_readhbts tnj"
    run_t_cmd "phy_readhbts tnk"
    run_t_cmd "phy_readhbts tnl"
    run_t_cmd "npu_refclksel tna btn"
    run_t_cmd "npu_refclksel tnd btn"
    run_t_cmd "npuprbs_set tna tx prbs7"
    run_t_cmd "npuprbs_set tnb tx prbs7"
    run_t_cmd "npuprbs_set tnc tx prbs7"
    run_t_cmd "npuprbs_set tnd tx prbs7"
    run_t_cmd "npuprbs_set tna rx prbs7"
    run_t_cmd "npuprbs_set tnb rx prbs7"
    run_t_cmd "npuprbs_set tnc rx prbs7"
    run_t_cmd "npuprbs_set tnd rx prbs7"
## we cant read out status since we dont have anything connected on TN ports
#    run_t_cmd "npuprbs_status tna 1"
#    run_t_cmd "npuprbs_status tnb 1"
#    run_t_cmd "npuprbs_status tnc 1"
#    run_t_cmd "npuprbs_status tnd 1"
    run_t_cmd "npuprbs_set tna rx off"
    run_t_cmd "npuprbs_set tnb rx off"
    run_t_cmd "npuprbs_set tnc rx off"
    run_t_cmd "npuprbs_set tnd rx off"
    run_t_cmd "npuprbs_set tna tx off"
    run_t_cmd "npuprbs_set tnb tx off"
    run_t_cmd "npuprbs_set tnc tx off"
    run_t_cmd "npuprbs_set tnd tx off"
    run_t_cmd "npu_refclksel tna brbs"
    run_t_cmd "npuprbs_set tna tx prbs7"
    run_t_cmd "npuprbs_set tnb tx prbs7"
    run_t_cmd "npuprbs_set tnc tx prbs7"
    run_t_cmd "npuprbs_set tna rx prbs7"
    run_t_cmd "npuprbs_set tnb rx prbs7"
    run_t_cmd "npuprbs_set tnc rx prbs7"
## we cant read out status since we dont have anything connected on TN ports
#    run_t_cmd "npuprbs_status tna 1"
#    run_t_cmd "npuprbs_status tnb 1"
#    run_t_cmd "npuprbs_status tnc 1"
    run_t_cmd "npuprbs_set tna rx off"
    run_t_cmd "npuprbs_set tnb rx off"
    run_t_cmd "npuprbs_set tnc rx off"
    run_t_cmd "npuprbs_set tna tx off"
    run_t_cmd "npuprbs_set tnb tx off"
    run_t_cmd "npuprbs_set tnc tx off"
    run_t_cmd "npu_refclksel tna brbs"
    run_t_cmd "npuprbs_set tnd tx prbs7"
    run_t_cmd "npuprbs_set tnd rx prbs7"
## we cant read out status since we dont have anything connected on TN ports
#    run_t_cmd "npuprbs_status tnd 1"
    run_t_cmd "npuprbs_set tnd rx off"
    run_t_cmd "npuprbs_set tnd tx off"
    run_t_cmd "icmtrx_setclk tne tn"
    run_t_cmd "icmtrx_setspeed tne 10GbE"
    run_t_cmd "icmtrx_prbsgen tne 1 1 7"
    run_t_cmd "icmtrx_prbsver tne 1 1 7"
## we cant read out status since we dont have anything connected on TN ports
#    run_t_cmd "icmtrx_prbsstatus tne 1"
    run_t_cmd "icmtrx_prbsver tne 0 1 7"
    run_t_cmd "icmtrx_prbsgen tne 0 1 7"
    run_t_cmd "icmtrx_setspeed tne 1GbE"
    run_t_cmd "icmtrx_prbsgen tne 1 1 10"
    run_t_cmd "icmtrx_prbsver tne 1 1 10"
## we cant read out status since we dont have anything connected on TN ports
#    run_t_cmd "icmtrx_prbsstatus tne 1"
    run_t_cmd "icmtrx_prbsver tne 0 1 7"
    run_t_cmd "icmtrx_prbsgen tne 0 1 7"
    run_t_cmd "icmtrx_setspeed tne 10GbE"
    run_t_cmd "icmtrx_prbsgen tnf 1 1 10"
    run_t_cmd "icmtrx_prbsgen tng 1 1 10"
    run_t_cmd "icmtrx_prbsgen tnh 1 1 10"
    run_t_cmd "icmtrx_prbsver tnf 1 1 10"
    run_t_cmd "icmtrx_prbsver tng 1 1 10"
    run_t_cmd "icmtrx_prbsver tnh 1 1 10"
## we cant read out status since we dont have anything connected on TN ports
#    run_t_cmd "icmtrx_prbsstatus tnf 1"
#    run_t_cmd "icmtrx_prbsstatus tng 1"
#    run_t_cmd "icmtrx_prbsstatus tnh 1"
    run_t_cmd "icmtrx_prbsver tnf 0 1 10"
    run_t_cmd "icmtrx_prbsver tng 0 1 10"
    run_t_cmd "icmtrx_prbsver tnh 0 1 10"
    run_t_cmd "icmtrx_prbsgen tnf 0 1 10"
    run_t_cmd "icmtrx_prbsgen tng 0 1 10"
    run_t_cmd "icmtrx_prbsgen tnh 0 1 10"
    run_t_cmd "tnport_setup tnj"
    run_t_cmd "phy_mode tnj copper_loop"
    run_t_cmd "nputrf_rxstart tnj verify"
    run_t_cmd "nputrf_txstart tnj 100 32"
    run_t_cmd "nputrf_stats tnj"
    run_t_cmd "nputrf_txstop tnj"
    run_t_cmd "nputrf_rxstop tnj"
    run_t_cmd "nputrf_stats tnj clear"
    run_t_cmd "phy_mode tnj normal"
    run_t_cmd "tnport_setup tnk"
    run_t_cmd "phy_mode tnk copper_loop"
    run_t_cmd "nputrf_rxstart tnk verify"
    run_t_cmd "nputrf_txstart tnk 100 32"
    run_t_cmd "nputrf_stats tnk"
    run_t_cmd "nputrf_txstop tnk"
    run_t_cmd "nputrf_rxstop tnk"
    run_t_cmd "nputrf_stats tnk clear"
    run_t_cmd "phy_mode tnk normal"
    run_t_cmd "tnport_setup tnl"
    run_t_cmd "phy_mode tnl copper_loop"
    run_t_cmd "nputrf_rxstart tnl verify"
    run_t_cmd "nputrf_txstart tnl 100 32"
    run_t_cmd "nputrf_stats tnl"
    run_t_cmd "nputrf_txstop tnl"
    run_t_cmd "nputrf_rxstop tnl"
    run_t_cmd "nputrf_stats tnl clear"
    run_t_cmd "phy_mode tnl normal"
    run_t_cmd "tnport_setup tnj"
    run_t_cmd "phy_mode tnj loop"
    run_t_cmd "nputrf_rxstart tnj verify"
    run_t_cmd "nputrf_txstart tnj 100 32"
    run_t_cmd "nputrf_stats tnj"
    run_t_cmd "nputrf_txstop tnj"
    run_t_cmd "nputrf_rxstop tnj"
    run_t_cmd "nputrf_stats tnj clear"
    run_t_cmd "phy_mode tnj normal"
    run_t_cmd "tnport_setup tnk"
    run_t_cmd "phy_mode tnk loop"
    run_t_cmd "nputrf_rxstart tnk verify"
    run_t_cmd "nputrf_txstart tnk 100 32"
    run_t_cmd "nputrf_stats tnk"
    run_t_cmd "nputrf_txstop tnk"
    run_t_cmd "nputrf_rxstop tnk"
    run_t_cmd "nputrf_stats tnk clear"
    run_t_cmd "phy_mode tnk normal"
    run_t_cmd "tnport_setup tnl"
    run_t_cmd "phy_mode tnl loop"
    run_t_cmd "nputrf_rxstart tnl verify"
    run_t_cmd "nputrf_txstart tnl 100 32"
    run_t_cmd "nputrf_stats tnl"
    run_t_cmd "nputrf_txstop tnl"
    run_t_cmd "nputrf_rxstop tnl"
    run_t_cmd "nputrf_stats tnl clear"
    run_t_cmd "phy_mode tnl normal"

    run_t_cmd "sfp_power tna on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tna eeprom"
#    run_t_cmd "sfp_testio tna"
    run_t_cmd "sfp_power tna off"
    run_t_cmd "sfp_power tnb on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tnb eeprom"
#    run_t_cmd "sfp_testio tnb"
    run_t_cmd "sfp_power tnb off"
    run_t_cmd "sfp_power tnc on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tnc eeprom"
#    run_t_cmd "sfp_testio tnc"
    run_t_cmd "sfp_power tnc off"
    run_t_cmd "sfp_power tnd on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tnd eeprom"
#    run_t_cmd "sfp_testio tnd"
    run_t_cmd "sfp_power tnd off"
    run_t_cmd "sfp_power tne on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tne eeprom"
#    run_t_cmd "sfp_testio tne"
    run_t_cmd "sfp_power tne off"
    run_t_cmd "sfp_power tnf on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tnf eeprom"
#    run_t_cmd "sfp_testio tnf"
    run_t_cmd "sfp_power tnf off"
    run_t_cmd "sfp_power tng on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tng eeprom"
#    run_t_cmd "sfp_testio tng"
    run_t_cmd "sfp_power tng off"
    run_t_cmd "sfp_power tnh on"
# we cant read out anything from sfp since no sfp's are connected
#    run_t_cmd "sfp_dump tnh eeprom"
#    run_t_cmd "sfp_testio tnh"
    run_t_cmd "sfp_power tnh off"
    run_t_cmd "tnport_setup tnk"
    run_t_cmd "phy_mode tnk loop"
    run_t_cmd "nputrf_rxstart tnk verify"
    run_t_cmd "nputrf_txstart tnk 100 32"
    run_t_cmd "nputrf_stats tnk"
    run_t_cmd "nputrf_txstop tnk"
    run_t_cmd "nputrf_rxstop tnk"
    run_t_cmd "nputrf_stats tnk clear"
    run_t_cmd "phy_mode tnk normal"
    run_t_cmd "tnport_setup tnl"
    run_t_cmd "phy_mode tnl loop"
    run_t_cmd "nputrf_rxstart tnl verify"
    run_t_cmd "nputrf_txstart tnl 100 32"
    run_t_cmd "nputrf_stats tnl"
    run_t_cmd "nputrf_txstop tnl"
    run_t_cmd "nputrf_rxstop tnl"
    run_t_cmd "nputrf_stats tnl clear"
    run_t_cmd "phy_mode tnl normal"
    run_t_cmd "phy_write tnj 0x17 0x0f7e"
    run_t_cmd "phy_write tnj 0x15 0"
    run_t_cmd "phy_write tnj 0x1e 0x083c"
    run_t_cmd "phy_write tnj 0x1f 0x0090"
    run_t_cmd "phy_write tnj 0x1e 0x083c"
    run_t_cmd "phy_read tnj 0x1f"
    run_t_cmd "turef_status tnj"
    run_t_cmd "mux_ptc tuf 5"
    run_t_cmd "phy_write tnj 0x1e 0x083c"
    run_t_cmd "phy_write tnj 0x1f 0x0098"
    run_t_cmd "phy_write tnj 0x1e 0x083c"
    run_t_cmd "phy_read tnj 0x1f"
    run_t_cmd "phy_write tnk 0x17 0x0f7e"
    run_t_cmd "phy_write tnk 0x15 0"
    run_t_cmd "phy_write tnk 0x1e 0x083c"
    run_t_cmd "phy_write tnk 0x1f 0x0090"
    run_t_cmd "phy_write tnk 0x1e 0x083c"
    run_t_cmd "phy_read tnk 0x1f"
    run_t_cmd "turef_status tnk"
    run_t_cmd "mux_ptc tuf 6"
    run_t_cmd "phy_write tnk 0x1e 0x083c"
    run_t_cmd "phy_write tnk 0x1f 0x0098"
    run_t_cmd "phy_write tnk 0x1e 0x083c"
    run_t_cmd "phy_read tnk 0x1f"
    run_t_cmd "phy_write tnl 0x17 0x0f7e"
    run_t_cmd "phy_write tnl 0x15 0"
    run_t_cmd "phy_write tnl 0x1e 0x083c"
    run_t_cmd "phy_write tnl 0x1f 0x0090"
    run_t_cmd "phy_write tnl 0x1e 0x083c"
    run_t_cmd "phy_read tnl 0x1f"
    run_t_cmd "turef_status tnl"
    run_t_cmd "mux_ptc tuf 7"
    run_t_cmd "phy_write tnl 0x1e 0x083c"
    run_t_cmd "phy_write tnl 0x1f 0x0098"
    run_t_cmd "phy_write tnl 0x1e 0x083c"
    run_t_cmd "phy_read tnl 0x1f"
    run_t_cmd "mux_ptc ccr 0"
    run_t_cmd "mux_ptc ccr 1"
    run_t_cmd "mux_ptc ccr 2"
    run_t_cmd "mux_ptc ccr 3"
    run_t_cmd "mux_ptc tuf 0"
    run_t_cmd "mux_ptc tuf 1"

    run_t_cmd "npuprbs_set tna tx prbs7"
    run_t_cmd "npuprbs_set tnb tx prbs7"
    run_t_cmd "npuprbs_set tnc tx prbs7"
    run_t_cmd "npuprbs_set tnd tx prbs7"
    run_t_cmd "npuprbs_set tne tx prbs7"
    run_t_cmd "npusynce_select tna 0"
    run_t_cmd "mux_ptc tuf 3"
    run_t_cmd "npusynce_select tnb 1"
    run_t_cmd "mux_ptc tuf 4"
    run_t_cmd "npusynce_select tnc 0"
    run_t_cmd "mux_ptc tuf 3"
    run_t_cmd "npusynce_select tnd 1"
    run_t_cmd "mux_ptc tuf 4"
    run_t_cmd "npusynce_select tne 0"
    run_t_cmd "mux_ptc tuf 3"
    run_t_cmd "npuprbs_set tna tx off"
    run_t_cmd "npuprbs_set tnb tx off"
    run_t_cmd "npuprbs_set tnc tx off"
    run_t_cmd "npuprbs_set tnd tx off"
    run_t_cmd "npuprbs_set tne tx off"
    run_t_cmd "npuprbs_set tnf tx prbs7"
    run_t_cmd "npuprbs_set tng tx prbs7"
    run_t_cmd "npuprbs_set tnh tx prbs7"
    run_t_cmd "npuprbs_set tnj tx prbs7"
    run_t_cmd "npusynce_select tnf 0"
    run_t_cmd "mux_ptc tuf 3"
    run_t_cmd "npusynce_select tng 1"
    run_t_cmd "mux_ptc tuf 4"
    run_t_cmd "npusynce_select tnh 0"
    run_t_cmd "mux_ptc tuf 3"
    run_t_cmd "npusynce_select tnj 1"
    run_t_cmd "mux_ptc tuf 4"
    run_t_cmd "npuprbs_set tnf tx off"
    run_t_cmd "npuprbs_set tng tx off"
    run_t_cmd "npuprbs_set tnh tx off"
    run_t_cmd "npuprbs_set tnj tx off"
    run_t_cmd "nputrf_txstart tnk 100 32"
    run_t_cmd "nputrf_txstart tnl 100 32"
    run_t_cmd "npusynce_select tnk 0"
    run_t_cmd "mux_ptc tuf 3"
    run_t_cmd "npusynce_select tnl 1"
    run_t_cmd "mux_ptc tuf 4"
    run_t_cmd "nputrf_txstop tnk"
    run_t_cmd "nputrf_txstop tnl"


    run_t_cmd "temp_read npu"
    run_t_cmd "temp_read board"

    run_t_cmd "maxload_calc -n 20 -t sec 60"

# Not possible to execute since nobody can push the button
#    run_t_cmd "button_mmi_chk"

}


if [ "$BOARDTYPE" == "TCU0301" ]
then
    run_t_cmd "--clear all"
    prod_test_tcu03;
    run_t_cmd "--status"
fi
