#!/bin/sh
# ----------------------------------------------------------------------
# **********************************************************************
#
# %CCaseCopyrightBegin%
# Copyright (c) Ericsson AB 2012 All rights reserved.
#
# The information in this document is the property of Ericsson.
#
# Except as specifically authorized in writing by Ericsson, the
# receiver of this document shall keep the information contained
# herein confidential and shall protect the same in whole or in
# part from disclosure and dissemination to third parties.
#
# Disclosure and disseminations to the receivers employees shall
# only be made on a strict need to know basis.
# %CCaseCopyrightEnd%
#
# **********************************************************************
##
#----------------------------------------------------------------------
# #1.    REVISION LOG
#----------------------------------------------------------------------
# Rev      Date         Name        What
# -----    ----------   --------    -------------------------------------
# R1A/1    20120222    etxarnu      Copied from SBG
#######################################################################

ROOTDIR=${OTP_ROOT:-/OTP/0}
BINDIR=`ls -d1 $ROOTDIR/erts-*/bin | head -n 1`
beam=`ls $BINDIR/beam* | head -n 1`
EMU=beam
PROGNAME=`echo $0 | sed 's/.*\///'`
PATH=$BINDIR:$ROOTDIR/bin:$PATH
export PATH
export EMU
export ROOTDIR
export BINDIR
export PROGNAME
exec $BINDIR/erlexec ${1+"$@"}
