#! /bin/sh
## Copyright Ericsson AB 2012. All Rights Reserved.
##
## The contents of this file are subject to the Erlang Public License,
## Version 1.1, (the "License"); you may not use this file except in
## compliance with the License. You should have received a copy of the
## Erlang Public License along with this software. If not, it can be
## retrieved online at http://www.erlang.org/.
##
## Software distributed under the License is distributed on an "AS IS"
## basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
## the License for the specific language governing rights and limitations
## under the License.
##
## Wrapper script; print pid, redirect stdout and stderr to /dev/null
## then exec target.
##
## $Author: Raimo Niskanen, Erlang/OTP$
##
#
: ${1:?Missing argument - target executable}
echo $$
[ -x "$1" ] || { echo "Not executable: $1" 1>&2; exit 1; }
exec 1>/dev/null 2>&1
exec "$@"
