%% Generated by the Erlang ASN.1 compiler version:4.0.4
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module PKCS-8



-ifndef(_PKCS_8_HRL_).
-define(_PKCS_8_HRL_, true).

-record('AlgorithmIdentifier',{
algorithm, parameters = asn1_NOVALUE}).

-record('PKAttribute',{
type, values, valuesWithContext = asn1_NOVALUE}).

-record('PKAttribute_valuesWithContext_SETOF',{
value, contextList}).

-record('PrivateKeyInfo',{
version, privateKeyAlgorithm, privateKey, attributes = asn1_NOVALUE}).

-record('PrivateKeyInfo_privateKeyAlgorithm',{
algorithm, parameters = asn1_NOVALUE}).

-record('Attributes_SETOF',{
type, values, valuesWithContext = asn1_NOVALUE}).

-record('Attributes_SETOF_valuesWithContext_SETOF',{
value, contextList}).

-record('EncryptedPrivateKeyInfo',{
encryptionAlgorithm, encryptedData}).

-record('EncryptedPrivateKeyInfo_encryptionAlgorithm',{
algorithm, parameters = asn1_NOVALUE}).

-record('Context',{
contextType, contextValues, fallback = asn1_DEFAULT}).

-endif. %% _PKCS_8_HRL_
