%% Generated by the Erlang ASN.1 compiler version:4.0.4
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module PKIXCMP



-ifndef(_PKIXCMP_HRL_).
-define(_PKIXCMP_HRL_, true).

-record('PKIMessage',{
header, body, protection = asn1_NOVALUE, extraCerts = asn1_NOVALUE}).

-record('PKIHeader',{
pvno, sender, recipient, messageTime = asn1_NOVALUE, protectionAlg = asn1_NOVALUE, senderKID = asn1_NOVALUE, recipKID = asn1_NOVALUE, transactionID = asn1_NOVALUE, senderNonce = asn1_NOVALUE, recipNonce = asn1_NOVALUE, freeText = asn1_NOVALUE, generalInfo = asn1_NOVALUE}).

-record('ProtectedPart',{
header, body}).

-record('PBMParameter',{
salt, owf, iterationCount, mac}).

-record('DHBMParameter',{
owf, mac}).

-record('PKIStatusInfo',{
status, statusString = asn1_NOVALUE, failInfo = asn1_NOVALUE}).

-record('OOBCertHash',{
hashAlg = asn1_NOVALUE, certId = asn1_NOVALUE, hashVal}).

-record('Challenge',{
owf = asn1_NOVALUE, witness, challenge}).

-record('CertRepMessage',{
caPubs = asn1_NOVALUE, response}).

-record('CertResponse',{
certReqId, status, certifiedKeyPair = asn1_NOVALUE, rspInfo = asn1_NOVALUE}).

-record('CertifiedKeyPair',{
certOrEncCert, privateKey = asn1_NOVALUE, publicationInfo = asn1_NOVALUE}).

-record('RevDetails',{
certDetails, crlEntryDetails = asn1_NOVALUE}).

-record('CertStatus',{
certHash, certReqId, statusInfo = asn1_NOVALUE}).

-record('InfoTypeAndValue',{
infoType, infoValue = asn1_NOVALUE}).

-record('ErrorMsgContent',{
pKIStatusInfo, errorCode = asn1_NOVALUE, errorDetails = asn1_NOVALUE}).

-record('PollReqContent_SEQOF',{
certReqId}).

-record('PollRepContent_SEQOF',{
certReqId, checkAfter, reason = asn1_NOVALUE}).

-define('id-PasswordBasedMac', {1,2,840,113533,7,66,13}).
-define('id-DHBasedMac', {1,2,840,113533,7,66,30}).
-endif. %% _PKIXCMP_HRL_
