%% Generated by the Erlang ASN.1 compiler version:4.0.4
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module PKIXCRMF-2005



-ifndef(_PKIXCRMF_2005_HRL_).
-define(_PKIXCRMF_2005_HRL_, true).

-record('CertReqMsg',{
certReq, popo = asn1_NOVALUE, regInfo = asn1_NOVALUE}).

-record('CertRequest',{
certReqId, certTemplate, controls = asn1_NOVALUE}).

-record('CertTemplate',{
version = asn1_NOVALUE, serialNumber = asn1_NOVALUE, signingAlg = asn1_NOVALUE, issuer = asn1_NOVALUE, validity = asn1_NOVALUE, subject = asn1_NOVALUE, publicKey = asn1_NOVALUE, issuerUID = asn1_NOVALUE, subjectUID = asn1_NOVALUE, extensions = asn1_NOVALUE}).

-record('OptionalValidity',{
notBefore = asn1_NOVALUE, notAfter = asn1_NOVALUE}).

-record('POPOSigningKey',{
poposkInput = asn1_NOVALUE, algorithmIdentifier, signature}).

-record('POPOSigningKeyInput',{
authInfo, publicKey}).

-record('PKMACValue',{
algId, value}).

-record('PKIPublicationInfo',{
action, pubInfos = asn1_NOVALUE}).

-record('SinglePubInfo',{
pubMethod, pubLocation = asn1_NOVALUE}).

-record('EncryptedValue',{
intendedAlg = asn1_NOVALUE, symmAlg = asn1_NOVALUE, encSymmKey = asn1_NOVALUE, keyAlg = asn1_NOVALUE, valueHint = asn1_NOVALUE, encValue}).

-record('CertId',{
issuer, serialNumber}).

-record('EncKeyWithID',{
privateKey, identifier = asn1_NOVALUE}).

-define('id-pkip', {1,3,6,1,5,5,7,5}).
-define('id-smime', {1,2,840,113549,1,9,16}).
-define('id-ct', {1,2,840,113549,1,9,16,1}).
-define('id-regCtrl', {1,3,6,1,5,5,7,5,1}).
-define('id-regCtrl-regToken', {1,3,6,1,5,5,7,5,1,1}).
-define('id-regCtrl-authenticator', {1,3,6,1,5,5,7,5,1,2}).
-define('id-regCtrl-pkiPublicationInfo', {1,3,6,1,5,5,7,5,1,3}).
-define('id-regCtrl-pkiArchiveOptions', {1,3,6,1,5,5,7,5,1,4}).
-define('id-regCtrl-oldCertID', {1,3,6,1,5,5,7,5,1,5}).
-define('id-regCtrl-protocolEncrKey', {1,3,6,1,5,5,7,5,1,6}).
-define('id-regInfo', {1,3,6,1,5,5,7,5,2}).
-define('id-regInfo-utf8Pairs', {1,3,6,1,5,5,7,5,2,1}).
-define('id-regInfo-certReq', {1,3,6,1,5,5,7,5,2,2}).
-define('id-ct-encKeyWithID', {1,2,840,113549,1,9,16,1,21}).
-endif. %% _PKIXCRMF_2005_HRL_
