/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_ntf_2eproto__INCLUDED
#define PROTOBUF_C_ntf_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "sa_ais.pb-c.h"
#include "om.pb-c.h"

typedef struct _SafsNtfClassId SafsNtfClassId;
typedef struct _SafsNtfValue SafsNtfValue;
typedef struct _SafsNtfAdditionalInfo SafsNtfAdditionalInfo;
typedef struct _SafsNtfSpecificProblem SafsNtfSpecificProblem;
typedef struct _SafsNtfCallbacks SafsNtfCallbacks;
typedef struct _SafsNtfThresholdInformation SafsNtfThresholdInformation;
typedef struct _SafsNtfProposedRepairAction SafsNtfProposedRepairAction;
typedef struct _SafsNtfStateChange SafsNtfStateChange;
typedef struct _SafsNtfAttribute SafsNtfAttribute;
typedef struct _SafsNtfAttributeChange SafsNtfAttributeChange;
typedef struct _SafsNtfServiceUser SafsNtfServiceUser;
typedef struct _SafsNtfSecurityAlarmDetector SafsNtfSecurityAlarmDetector;
typedef struct _SafsNtfNotificationHeader SafsNtfNotificationHeader;
typedef struct _SafsNtfObjectCreateDeleteNotification SafsNtfObjectCreateDeleteNotification;
typedef struct _SafsNtfAttributeChangeNotification SafsNtfAttributeChangeNotification;
typedef struct _SafsNtfStateChangeNotification SafsNtfStateChangeNotification;
typedef struct _SafsNtfAlarmNotification SafsNtfAlarmNotification;
typedef struct _SafsNtfSecurityAlarmNotification SafsNtfSecurityAlarmNotification;
typedef struct _SafsNtfNotificationFilterHeader SafsNtfNotificationFilterHeader;
typedef struct _SafsNtfObjectCreateDeleteNotificationFilter SafsNtfObjectCreateDeleteNotificationFilter;
typedef struct _SafsNtfAttributeChangeNotificationFilter SafsNtfAttributeChangeNotificationFilter;
typedef struct _SafsNtfStateChangeNotificationFilter SafsNtfStateChangeNotificationFilter;
typedef struct _SafsNtfAlarmNotificationFilter SafsNtfAlarmNotificationFilter;
typedef struct _SafsNtfSecurityAlarmNotificationFilter SafsNtfSecurityAlarmNotificationFilter;
typedef struct _SafsNtfSearchCriteria SafsNtfSearchCriteria;
typedef struct _SafsNtfNotificationTypeFilters SafsNtfNotificationTypeFilters;
typedef struct _SafsNtfNotification SafsNtfNotification;
typedef struct _SaNtfNotificationCallback SaNtfNotificationCallback;
typedef struct _SaNtfNotificationDiscardedCallback SaNtfNotificationDiscardedCallback;
typedef struct _SafsNtfInitialize SafsNtfInitialize;
typedef struct _SafsNtfFinalize SafsNtfFinalize;
typedef struct _SafsNtfNotificationSend SafsNtfNotificationSend;
typedef struct _SafsNtfNotificationSubscribe SafsNtfNotificationSubscribe;
typedef struct _SafsNtfNotificationUnsubscribe SafsNtfNotificationUnsubscribe;
typedef struct _SafsNtfNotificationReadInitialize SafsNtfNotificationReadInitialize;
typedef struct _SafsNtfNotificationReadNext SafsNtfNotificationReadNext;
typedef struct _SafsNtfNotificationReadFinalize SafsNtfNotificationReadFinalize;
typedef struct _SafsNtfCallbacksInitialize SafsNtfCallbacksInitialize;
typedef struct _SafsNtfMessage SafsNtfMessage;
typedef struct _SaNtfCallbacks SaNtfCallbacks;
typedef struct _SafsNtfInitializeRet SafsNtfInitializeRet;
typedef struct _SafsNtfFinalizeRet SafsNtfFinalizeRet;
typedef struct _SafsNtfNotificationSendRet SafsNtfNotificationSendRet;
typedef struct _SafsNtfNotificationSubscribeRet SafsNtfNotificationSubscribeRet;
typedef struct _SafsNtfNotificationUnsubscribeRet SafsNtfNotificationUnsubscribeRet;
typedef struct _SafsNtfNotificationReadInitializeRet SafsNtfNotificationReadInitializeRet;
typedef struct _SafsNtfNotificationReadNextRet SafsNtfNotificationReadNextRet;
typedef struct _SafsNtfNotificationReadFinalizeRet SafsNtfNotificationReadFinalizeRet;
typedef struct _SafsNtfCallbacksInitializeRet SafsNtfCallbacksInitializeRet;


/* --- enums --- */

typedef enum _SafsNtfNotificationType {
  SAFS_NTF_NOTIFICATION_TYPE__sa_ntf_type_object_create_delete = 4096,
  SAFS_NTF_NOTIFICATION_TYPE__sa_ntf_type_attribute_change = 8192,
  SAFS_NTF_NOTIFICATION_TYPE__sa_ntf_type_state_change = 12288,
  SAFS_NTF_NOTIFICATION_TYPE__sa_ntf_type_alarm = 16384,
  SAFS_NTF_NOTIFICATION_TYPE__sa_ntf_type_security_alarm = 20480
} SafsNtfNotificationType;
typedef enum _SafsNtfEventType {
  SAFS_NTF_EVENT_TYPE__sa_ntf_object_notifications_start = 4096,
  SAFS_NTF_EVENT_TYPE__sa_ntf_object_creation = 4097,
  SAFS_NTF_EVENT_TYPE__sa_ntf_object_deletion = 4098,
  SAFS_NTF_EVENT_TYPE__sa_ntf_attribute_notifications_start = 8192,
  SAFS_NTF_EVENT_TYPE__sa_ntf_attribute_added = 8193,
  SAFS_NTF_EVENT_TYPE__sa_ntf_attribute_removed = 8194,
  SAFS_NTF_EVENT_TYPE__sa_ntf_attribute_changed = 8195,
  SAFS_NTF_EVENT_TYPE__sa_ntf_attribute_reset = 8196,
  SAFS_NTF_EVENT_TYPE__sa_ntf_state_change_notifications_start = 12288,
  SAFS_NTF_EVENT_TYPE__sa_ntf_object_state_change = 12289,
  SAFS_NTF_EVENT_TYPE__sa_ntf_alarm_notifications_start = 16384,
  SAFS_NTF_EVENT_TYPE__sa_ntf_alarm_communication = 16385,
  SAFS_NTF_EVENT_TYPE__sa_ntf_alarm_qos = 16386,
  SAFS_NTF_EVENT_TYPE__sa_ntf_alarm_processing = 16387,
  SAFS_NTF_EVENT_TYPE__sa_ntf_alarm_equipment = 16388,
  SAFS_NTF_EVENT_TYPE__sa_ntf_alarm_environment = 16389,
  SAFS_NTF_EVENT_TYPE__sa_ntf_security_alarm_notifications_start = 20480,
  SAFS_NTF_EVENT_TYPE__sa_ntf_integrity_violation = 20481,
  SAFS_NTF_EVENT_TYPE__sa_ntf_operation_violation = 20482,
  SAFS_NTF_EVENT_TYPE__sa_ntf_physical_violation = 20483,
  SAFS_NTF_EVENT_TYPE__sa_ntf_security_service_violation = 20484,
  SAFS_NTF_EVENT_TYPE__sa_ntf_time_violation = 20485
} SafsNtfEventType;
typedef enum _SafsNtfValueType {
  SAFS_NTF_VALUE_TYPE__sa_ntf_value_uint8 = 0,
  SAFS_NTF_VALUE_TYPE__sa_ntf_value_int8 = 1,
  SAFS_NTF_VALUE_TYPE__sa_ntf_value_uint16 = 2,
  SAFS_NTF_VALUE_TYPE__sa_ntf_value_int16 = 3,
  SAFS_NTF_VALUE_TYPE__sa_ntf_value_uint32 = 4,
  SAFS_NTF_VALUE_TYPE__sa_ntf_value_int32 = 5,
  SAFS_NTF_VALUE_TYPE__sa_ntf_value_float = 6,
  SAFS_NTF_VALUE_TYPE__sa_ntf_value_uint64 = 7,
  SAFS_NTF_VALUE_TYPE__sa_ntf_value_int64 = 8,
  SAFS_NTF_VALUE_TYPE__sa_ntf_value_double = 9,
  SAFS_NTF_VALUE_TYPE__sa_ntf_value_ldap_name = 10,
  SAFS_NTF_VALUE_TYPE__sa_ntf_value_string = 11,
  SAFS_NTF_VALUE_TYPE__sa_ntf_value_ipaddress = 12,
  SAFS_NTF_VALUE_TYPE__sa_ntf_value_binary = 13,
  SAFS_NTF_VALUE_TYPE__sa_ntf_value_array = 14,
  SAFS_NTF_VALUE_TYPE__sa_ntf_value_csstructt = 9999
} SafsNtfValueType;
typedef enum _SafsNtfProbableCause {
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_adapter_error = 0,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_application_subsystem_failure = 1,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_bandwidth_reduced = 2,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_call_establishment_error = 3,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_communications_protocol_error = 4,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_communications_subsystem_failure = 5,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_configuration_or_customization_error = 6,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_congestion = 7,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_corrupt_data = 8,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_cpu_cycles_limit_exceeded = 9,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_dataset_or_modem_error = 10,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_degraded_signal = 11,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_d_t_e = 12,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_enclosure_door_open = 13,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_equipment_malfunction = 14,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_excessive_vibration = 15,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_file_error = 16,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_fire_detected = 17,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_flood_detected = 18,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_framing_error = 19,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_heating_or_ventilation_or_cooling_system_problem = 20,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_humidity_unacceptable = 21,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_input_output_device_error = 22,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_input_device_error = 23,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_l_a_n_error = 24,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_leak_detected = 25,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_local_node_transmission_error = 26,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_loss_of_frame = 27,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_loss_of_signal = 28,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_material_supply_exhausted = 29,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_multiplexer_problem = 30,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_out_of_memory = 31,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_output_device_error = 32,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_performance_degraded = 33,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_power_problem = 34,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_pressure_unacceptable = 35,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_processor_problem = 36,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_pump_failure = 37,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_queue_size_exceeded = 38,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_receive_failure = 39,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_receiver_failure = 40,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_remote_node_transmission_error = 41,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_resource_at_or_nearing_capacity = 42,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_response_time_excessive = 43,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_retransmission_rate_excessive = 44,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_software_error = 45,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_software_program_abnormally_terminated = 46,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_software_program_error = 47,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_storage_capacity_problem = 48,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_temperature_unacceptable = 49,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_threshold_crossed = 50,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_timing_problem = 51,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_toxic_leak_detected = 52,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_transmit_failure = 53,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_transmitter_failure = 54,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_underlying_resource_unavailable = 55,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_version_mismatch = 56,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_authentication_failure = 57,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_breach_of_confidentiality = 58,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_cable_tamper = 59,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_delayed_information = 60,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_denial_of_service = 61,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_duplicate_information = 62,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_information_missing = 63,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_information_modification_detected = 64,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_information_out_of_sequence = 65,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_intrusion_detection = 66,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_key_expired = 67,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_non_repudiation_failure = 68,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_out_of_hours_activity = 69,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_out_of_service = 70,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_procedural_error = 71,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_unauthorized_access_attempt = 72,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_unexpected_information = 73,
  SAFS_NTF_PROBABLE_CAUSE__sa_ntf_unspecified_reason = 74
} SafsNtfProbableCause;
typedef enum _SafsNtfSeverity {
  SAFS_NTF_SEVERITY__sa_ntf_severity_cleared = 0,
  SAFS_NTF_SEVERITY__sa_ntf_severity_indeterminate = 1,
  SAFS_NTF_SEVERITY__sa_ntf_severity_warning = 2,
  SAFS_NTF_SEVERITY__sa_ntf_severity_minor = 3,
  SAFS_NTF_SEVERITY__sa_ntf_severity_major = 4,
  SAFS_NTF_SEVERITY__sa_ntf_severity_critical = 5
} SafsNtfSeverity;
typedef enum _SafsNtfSeverityTrend {
  SAFS_NTF_SEVERITY_TREND__sa_ntf_trend_more_severe = 0,
  SAFS_NTF_SEVERITY_TREND__sa_ntf_trend_no_change = 1,
  SAFS_NTF_SEVERITY_TREND__sa_ntf_trend_less_severe = 2
} SafsNtfSeverityTrend;
typedef enum _SafsNtfSourceIndicator {
  SAFS_NTF_SOURCE_INDICATOR__sa_ntf_object_operation = 1,
  SAFS_NTF_SOURCE_INDICATOR__sa_ntf_management_operation = 2,
  SAFS_NTF_SOURCE_INDICATOR__sa_ntf_unknown_operation = 3
} SafsNtfSourceIndicator;
typedef enum _SafsNtfSearchMode {
  SAFS_NTF_SEARCH_MODE__sa_ntf_search_before_or_at_time = 1,
  SAFS_NTF_SEARCH_MODE__sa_ntf_search_at_time = 2,
  SAFS_NTF_SEARCH_MODE__sa_ntf_search_at_or_after_time = 3,
  SAFS_NTF_SEARCH_MODE__sa_ntf_search_before_time = 4,
  SAFS_NTF_SEARCH_MODE__sa_ntf_search_after_time = 5,
  SAFS_NTF_SEARCH_MODE__sa_ntf_search_notification_id = 6,
  SAFS_NTF_SEARCH_MODE__sa_ntf_search_only_filter = 7
} SafsNtfSearchMode;
typedef enum _SafsNtfSearchDirection {
  SAFS_NTF_SEARCH_DIRECTION__sa_ntf_search_older = 1,
  SAFS_NTF_SEARCH_DIRECTION__sa_ntf_search_younger = 2
} SafsNtfSearchDirection;

/* --- messages --- */

struct  _SafsNtfClassId
{
  ProtobufCMessage base;
  uint32_t vendorid;
  uint32_t majorid;
  uint32_t minorid;
};
#define SAFS_NTF_CLASS_ID__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_class_id__descriptor) \
    , 0, 0, 0 }


struct  _SafsNtfValue
{
  ProtobufCMessage base;
  protobuf_c_boolean has_uint8val;
  uint32_t uint8val;
  protobuf_c_boolean has_int8val;
  int32_t int8val;
  protobuf_c_boolean has_uint16val;
  uint32_t uint16val;
  protobuf_c_boolean has_int16val;
  int32_t int16val;
  protobuf_c_boolean has_uint32val;
  uint32_t uint32val;
  protobuf_c_boolean has_int32val;
  int32_t int32val;
  protobuf_c_boolean has_floatval;
  double floatval;
  protobuf_c_boolean has_uint64val;
  uint64_t uint64val;
  protobuf_c_boolean has_int64val;
  int64_t int64val;
  protobuf_c_boolean has_doubleval;
  double doubleval;
  protobuf_c_boolean has_variable;
  ProtobufCBinaryData variable;
  SafsImmCsStruct *csstruct;
};
#define SAFS_NTF_VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_value__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,{0,NULL}, NULL }


struct  _SafsNtfAdditionalInfo
{
  ProtobufCMessage base;
  uint32_t infoid;
  SafsNtfValueType infotype;
  SafsNtfValue *infovalue;
};
#define SAFS_NTF_ADDITIONAL_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_additional_info__descriptor) \
    , 0, 0, NULL }


struct  _SafsNtfSpecificProblem
{
  ProtobufCMessage base;
  uint32_t problemid;
  SafsNtfClassId *problemclassid;
  SafsNtfValueType problemtype;
  SafsNtfValue *problemvalue;
};
#define SAFS_NTF_SPECIFIC_PROBLEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_specific_problem__descriptor) \
    , 0, NULL, 0, NULL }


struct  _SafsNtfCallbacks
{
  ProtobufCMessage base;
  protobuf_c_boolean santfnotificationcallback;
  protobuf_c_boolean santfnotificationdiscardedcallback;
};
#define SAFS_NTF_CALLBACKS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_callbacks__descriptor) \
    , 0, 0 }


struct  _SafsNtfThresholdInformation
{
  ProtobufCMessage base;
  uint32_t thresholdid;
  SafsNtfValueType thresholdvaluetype;
  SafsNtfValue *thresholdvalue;
  SafsNtfValue *thresholdhysteresis;
  SafsNtfValue *observedvalue;
  int64_t armtime;
};
#define SAFS_NTF_THRESHOLD_INFORMATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_threshold_information__descriptor) \
    , 0, 0, NULL, NULL, NULL, 0 }


struct  _SafsNtfProposedRepairAction
{
  ProtobufCMessage base;
  uint32_t actionid;
  SafsNtfValueType actionvaluetype;
  SafsNtfValue *actionvalue;
};
#define SAFS_NTF_PROPOSED_REPAIR_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_proposed_repair_action__descriptor) \
    , 0, 0, NULL }


struct  _SafsNtfStateChange
{
  ProtobufCMessage base;
  uint32_t stateid;
  protobuf_c_boolean has_oldstate;
  uint32_t oldstate;
  uint32_t newstate;
};
#define SAFS_NTF_STATE_CHANGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_state_change__descriptor) \
    , 0, 0,0, 0 }


struct  _SafsNtfAttribute
{
  ProtobufCMessage base;
  uint32_t attributeid;
  SafsNtfValueType attributetype;
  SafsNtfValue *attributevalue;
};
#define SAFS_NTF_ATTRIBUTE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_attribute__descriptor) \
    , 0, 0, NULL }


struct  _SafsNtfAttributeChange
{
  ProtobufCMessage base;
  uint32_t attributeid;
  SafsNtfValueType attributetype;
  SafsNtfValue *oldattributevalue;
  SafsNtfValue *newattributevalue;
};
#define SAFS_NTF_ATTRIBUTE_CHANGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_attribute_change__descriptor) \
    , 0, 0, NULL, NULL }


struct  _SafsNtfServiceUser
{
  ProtobufCMessage base;
  SafsNtfValueType valuetype;
  SafsNtfValue *value;
};
#define SAFS_NTF_SERVICE_USER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_service_user__descriptor) \
    , 0, NULL }


struct  _SafsNtfSecurityAlarmDetector
{
  ProtobufCMessage base;
  SafsNtfValueType valuetype;
  SafsNtfValue *value;
};
#define SAFS_NTF_SECURITY_ALARM_DETECTOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_security_alarm_detector__descriptor) \
    , 0, NULL }


struct  _SafsNtfNotificationHeader
{
  ProtobufCMessage base;
  SafsNtfEventType eventtype;
  char *notificationobject;
  char *notifyingobject;
  SafsNtfClassId *notificationclassid;
  int64_t eventtime;
  size_t n_correlatednotifications;
  uint64_t *correlatednotifications;
  char *additionaltext;
  size_t n_additionalinfo;
  SafsNtfAdditionalInfo **additionalinfo;
};
#define SAFS_NTF_NOTIFICATION_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_notification_header__descriptor) \
    , 0, NULL, NULL, NULL, 0, 0,NULL, NULL, 0,NULL }


struct  _SafsNtfObjectCreateDeleteNotification
{
  ProtobufCMessage base;
  SafsNtfNotificationHeader *notificationheader;
  SafsNtfSourceIndicator sourceindicator;
  size_t n_objectattributes;
  SafsNtfAttribute **objectattributes;
};
#define SAFS_NTF_OBJECT_CREATE_DELETE_NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_object_create_delete_notification__descriptor) \
    , NULL, 0, 0,NULL }


struct  _SafsNtfAttributeChangeNotification
{
  ProtobufCMessage base;
  SafsNtfNotificationHeader *notificationheader;
  SafsNtfSourceIndicator sourceindicator;
  size_t n_changedattributes;
  SafsNtfAttributeChange **changedattributes;
};
#define SAFS_NTF_ATTRIBUTE_CHANGE_NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_attribute_change_notification__descriptor) \
    , NULL, 0, 0,NULL }


struct  _SafsNtfStateChangeNotification
{
  ProtobufCMessage base;
  SafsNtfNotificationHeader *notificationheader;
  SafsNtfSourceIndicator sourceindicator;
  size_t n_changedstates;
  SafsNtfStateChange **changedstates;
};
#define SAFS_NTF_STATE_CHANGE_NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_state_change_notification__descriptor) \
    , NULL, 0, 0,NULL }


struct  _SafsNtfAlarmNotification
{
  ProtobufCMessage base;
  SafsNtfNotificationHeader *notificationheader;
  SafsNtfProbableCause probablecause;
  size_t n_specificproblems;
  SafsNtfSpecificProblem **specificproblems;
  SafsNtfSeverity perceivedseverity;
  SafsNtfSeverityTrend trend;
  SafsNtfThresholdInformation *thresholdinformation;
  size_t n_monitoredattributes;
  SafsNtfAttribute **monitoredattributes;
  size_t n_proposedrepairactions;
  SafsNtfProposedRepairAction **proposedrepairactions;
};
#define SAFS_NTF_ALARM_NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_alarm_notification__descriptor) \
    , NULL, 0, 0,NULL, 0, 0, NULL, 0,NULL, 0,NULL }


struct  _SafsNtfSecurityAlarmNotification
{
  ProtobufCMessage base;
  SafsNtfNotificationHeader *notificationheader;
  SafsNtfProbableCause probablecause;
  SafsNtfSeverity severity;
  SafsNtfSecurityAlarmDetector *securityalarmdetector;
  SafsNtfServiceUser *serviceuser;
  SafsNtfServiceUser *serviceprovider;
};
#define SAFS_NTF_SECURITY_ALARM_NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_security_alarm_notification__descriptor) \
    , NULL, 0, 0, NULL, NULL, NULL }


struct  _SafsNtfNotificationFilterHeader
{
  ProtobufCMessage base;
  size_t n_eventtypes;
  SafsNtfEventType *eventtypes;
  size_t n_notificationobjects;
  char **notificationobjects;
  size_t n_notifyingobjects;
  char **notifyingobjects;
  size_t n_notificationclassids;
  SafsNtfClassId **notificationclassids;
};
#define SAFS_NTF_NOTIFICATION_FILTER_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_notification_filter_header__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL, 0,NULL }


struct  _SafsNtfObjectCreateDeleteNotificationFilter
{
  ProtobufCMessage base;
  SafsNtfNotificationFilterHeader *notificationfilterheader;
  size_t n_sourceindicators;
  SafsNtfSourceIndicator *sourceindicators;
};
#define SAFS_NTF_OBJECT_CREATE_DELETE_NOTIFICATION_FILTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_object_create_delete_notification_filter__descriptor) \
    , NULL, 0,NULL }


struct  _SafsNtfAttributeChangeNotificationFilter
{
  ProtobufCMessage base;
  SafsNtfNotificationFilterHeader *notificationfilterheader;
  size_t n_sourceindicators;
  SafsNtfSourceIndicator *sourceindicators;
};
#define SAFS_NTF_ATTRIBUTE_CHANGE_NOTIFICATION_FILTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_attribute_change_notification_filter__descriptor) \
    , NULL, 0,NULL }


struct  _SafsNtfStateChangeNotificationFilter
{
  ProtobufCMessage base;
  SafsNtfNotificationFilterHeader *notificationfilterheader;
  size_t n_sourceindicators;
  SafsNtfSourceIndicator *sourceindicators;
  size_t n_changedstates;
  SafsNtfStateChange **changedstates;
};
#define SAFS_NTF_STATE_CHANGE_NOTIFICATION_FILTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_state_change_notification_filter__descriptor) \
    , NULL, 0,NULL, 0,NULL }


struct  _SafsNtfAlarmNotificationFilter
{
  ProtobufCMessage base;
  SafsNtfNotificationFilterHeader *notificationfilterheader;
  size_t n_probablecauses;
  SafsNtfProbableCause *probablecauses;
  size_t n_perceivedseverities;
  SafsNtfSeverity *perceivedseverities;
  size_t n_trends;
  SafsNtfSeverityTrend *trends;
};
#define SAFS_NTF_ALARM_NOTIFICATION_FILTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_alarm_notification_filter__descriptor) \
    , NULL, 0,NULL, 0,NULL, 0,NULL }


struct  _SafsNtfSecurityAlarmNotificationFilter
{
  ProtobufCMessage base;
  SafsNtfNotificationFilterHeader *notificationfilterheader;
  size_t n_probablecauses;
  SafsNtfProbableCause *probablecauses;
  size_t n_severities;
  SafsNtfSeverity *severities;
  size_t n_securityalarmdetectors;
  SafsNtfSecurityAlarmDetector **securityalarmdetectors;
  size_t n_serviceusers;
  SafsNtfServiceUser **serviceusers;
  size_t n_serviceproviders;
  SafsNtfServiceUser **serviceproviders;
};
#define SAFS_NTF_SECURITY_ALARM_NOTIFICATION_FILTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_security_alarm_notification_filter__descriptor) \
    , NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL }


struct  _SafsNtfSearchCriteria
{
  ProtobufCMessage base;
  SafsNtfSearchMode searchmode;
  int64_t eventtime;
  uint64_t notificationid;
};
#define SAFS_NTF_SEARCH_CRITERIA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_search_criteria__descriptor) \
    , 0, 0, 0 }


struct  _SafsNtfNotificationTypeFilters
{
  ProtobufCMessage base;
  SafsNtfObjectCreateDeleteNotificationFilter *objectcreatedeletenotificationfilter;
  SafsNtfAttributeChangeNotificationFilter *attributechangenotificationfilter;
  SafsNtfStateChangeNotificationFilter *statechangenotificationfilter;
  SafsNtfAlarmNotificationFilter *alarmnotificationfilter;
  SafsNtfSecurityAlarmNotificationFilter *securityalarmnotificationfilter;
};
#define SAFS_NTF_NOTIFICATION_TYPE_FILTERS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_notification_type_filters__descriptor) \
    , NULL, NULL, NULL, NULL, NULL }


struct  _SafsNtfNotification
{
  ProtobufCMessage base;
  SafsNtfObjectCreateDeleteNotification *objectcreatedeletenotification;
  SafsNtfAttributeChangeNotification *attributechangenotification;
  SafsNtfStateChangeNotification *statechangenotification;
  SafsNtfAlarmNotification *alarmnotification;
  SafsNtfSecurityAlarmNotification *securityalarmnotification;
};
#define SAFS_NTF_NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_notification__descriptor) \
    , NULL, NULL, NULL, NULL, NULL }


struct  _SaNtfNotificationCallback
{
  ProtobufCMessage base;
  uint32_t subscriptionid;
  SafsNtfNotification *notification;
};
#define SA_NTF_NOTIFICATION_CALLBACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sa_ntf_notification_callback__descriptor) \
    , 0, NULL }


struct  _SaNtfNotificationDiscardedCallback
{
  ProtobufCMessage base;
  uint32_t subscriptionid;
  SafsNtfNotificationType notificationtype;
  size_t n_discardednotificationidentifiers;
  uint64_t *discardednotificationidentifiers;
};
#define SA_NTF_NOTIFICATION_DISCARDED_CALLBACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sa_ntf_notification_discarded_callback__descriptor) \
    , 0, 0, 0,NULL }


struct  _SafsNtfInitialize
{
  ProtobufCMessage base;
  SafsNtfCallbacks *callbacks;
  SafsVersion *version;
};
#define SAFS_NTF_INITIALIZE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_initialize__descriptor) \
    , NULL, NULL }


struct  _SafsNtfFinalize
{
  ProtobufCMessage base;
  uint64_t handle;
};
#define SAFS_NTF_FINALIZE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_finalize__descriptor) \
    , 0 }


struct  _SafsNtfNotificationSend
{
  ProtobufCMessage base;
  uint64_t handle;
  SafsNtfNotification *notification;
};
#define SAFS_NTF_NOTIFICATION_SEND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_notification_send__descriptor) \
    , 0, NULL }


struct  _SafsNtfNotificationSubscribe
{
  ProtobufCMessage base;
  uint64_t handle;
  SafsNtfNotificationTypeFilters *notificationtypefilters;
  uint32_t subscriptionid;
};
#define SAFS_NTF_NOTIFICATION_SUBSCRIBE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_notification_subscribe__descriptor) \
    , 0, NULL, 0 }


struct  _SafsNtfNotificationUnsubscribe
{
  ProtobufCMessage base;
  uint64_t handle;
  uint32_t subscriptionid;
};
#define SAFS_NTF_NOTIFICATION_UNSUBSCRIBE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_notification_unsubscribe__descriptor) \
    , 0, 0 }


struct  _SafsNtfNotificationReadInitialize
{
  ProtobufCMessage base;
  uint64_t handle;
  SafsNtfSearchCriteria *searchcriteria;
  SafsNtfNotificationTypeFilters *notificationtypefilters;
};
#define SAFS_NTF_NOTIFICATION_READ_INITIALIZE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_notification_read_initialize__descriptor) \
    , 0, NULL, NULL }


struct  _SafsNtfNotificationReadNext
{
  ProtobufCMessage base;
  uint64_t readhandle;
  SafsNtfSearchDirection searchdirection;
};
#define SAFS_NTF_NOTIFICATION_READ_NEXT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_notification_read_next__descriptor) \
    , 0, 0 }


struct  _SafsNtfNotificationReadFinalize
{
  ProtobufCMessage base;
  uint64_t readhandle;
};
#define SAFS_NTF_NOTIFICATION_READ_FINALIZE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_notification_read_finalize__descriptor) \
    , 0 }


struct  _SafsNtfCallbacksInitialize
{
  ProtobufCMessage base;
  uint64_t handle;
};
#define SAFS_NTF_CALLBACKS_INITIALIZE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_callbacks_initialize__descriptor) \
    , 0 }


struct  _SafsNtfMessage
{
  ProtobufCMessage base;
  SafsNtfInitialize *initialize;
  SafsNtfFinalize *finalize;
  SafsNtfNotificationSend *notificationsend;
  SafsNtfNotificationSubscribe *notificationsubscribe;
  SafsNtfNotificationUnsubscribe *notificationunsubscribe;
  SafsNtfNotificationReadInitialize *notificationreadinitialize;
  SafsNtfNotificationReadNext *notificationreadnext;
  SafsNtfNotificationReadFinalize *notificationreadfinalize;
  SafsNtfCallbacksInitialize *callbacksinitialize;
};
#define SAFS_NTF_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_message__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }


struct  _SaNtfCallbacks
{
  ProtobufCMessage base;
  SaNtfNotificationCallback *notificationcallback;
  SaNtfNotificationDiscardedCallback *notificationdiscardedcallback;
};
#define SA_NTF_CALLBACKS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sa_ntf_callbacks__descriptor) \
    , NULL, NULL }


struct  _SafsNtfInitializeRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
  uint64_t handle;
  SafsVersion *version;
};
#define SAFS_NTF_INITIALIZE_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_initialize_ret__descriptor) \
    , 0, 0, NULL }


struct  _SafsNtfFinalizeRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
};
#define SAFS_NTF_FINALIZE_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_finalize_ret__descriptor) \
    , 0 }


struct  _SafsNtfNotificationSendRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
  protobuf_c_boolean has_identifier;
  uint64_t identifier;
};
#define SAFS_NTF_NOTIFICATION_SEND_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_notification_send_ret__descriptor) \
    , 0, 0,0 }


struct  _SafsNtfNotificationSubscribeRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
};
#define SAFS_NTF_NOTIFICATION_SUBSCRIBE_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_notification_subscribe_ret__descriptor) \
    , 0 }


struct  _SafsNtfNotificationUnsubscribeRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
};
#define SAFS_NTF_NOTIFICATION_UNSUBSCRIBE_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_notification_unsubscribe_ret__descriptor) \
    , 0 }


struct  _SafsNtfNotificationReadInitializeRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
  protobuf_c_boolean has_readhandle;
  uint64_t readhandle;
};
#define SAFS_NTF_NOTIFICATION_READ_INITIALIZE_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_notification_read_initialize_ret__descriptor) \
    , 0, 0,0 }


struct  _SafsNtfNotificationReadNextRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
  SafsNtfNotification *notification;
};
#define SAFS_NTF_NOTIFICATION_READ_NEXT_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_notification_read_next_ret__descriptor) \
    , 0, NULL }


struct  _SafsNtfNotificationReadFinalizeRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
};
#define SAFS_NTF_NOTIFICATION_READ_FINALIZE_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_notification_read_finalize_ret__descriptor) \
    , 0 }


struct  _SafsNtfCallbacksInitializeRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
};
#define SAFS_NTF_CALLBACKS_INITIALIZE_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_ntf_callbacks_initialize_ret__descriptor) \
    , 0 }


/* SafsNtfClassId methods */
void   safs_ntf_class_id__init
                     (SafsNtfClassId         *message);
size_t safs_ntf_class_id__get_packed_size
                     (const SafsNtfClassId   *message);
size_t safs_ntf_class_id__pack
                     (const SafsNtfClassId   *message,
                      uint8_t             *out);
size_t safs_ntf_class_id__pack_to_buffer
                     (const SafsNtfClassId   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfClassId *
       safs_ntf_class_id__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_class_id__free_unpacked
                     (SafsNtfClassId *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfValue methods */
void   safs_ntf_value__init
                     (SafsNtfValue         *message);
size_t safs_ntf_value__get_packed_size
                     (const SafsNtfValue   *message);
size_t safs_ntf_value__pack
                     (const SafsNtfValue   *message,
                      uint8_t             *out);
size_t safs_ntf_value__pack_to_buffer
                     (const SafsNtfValue   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfValue *
       safs_ntf_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_value__free_unpacked
                     (SafsNtfValue *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfAdditionalInfo methods */
void   safs_ntf_additional_info__init
                     (SafsNtfAdditionalInfo         *message);
size_t safs_ntf_additional_info__get_packed_size
                     (const SafsNtfAdditionalInfo   *message);
size_t safs_ntf_additional_info__pack
                     (const SafsNtfAdditionalInfo   *message,
                      uint8_t             *out);
size_t safs_ntf_additional_info__pack_to_buffer
                     (const SafsNtfAdditionalInfo   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfAdditionalInfo *
       safs_ntf_additional_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_additional_info__free_unpacked
                     (SafsNtfAdditionalInfo *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfSpecificProblem methods */
void   safs_ntf_specific_problem__init
                     (SafsNtfSpecificProblem         *message);
size_t safs_ntf_specific_problem__get_packed_size
                     (const SafsNtfSpecificProblem   *message);
size_t safs_ntf_specific_problem__pack
                     (const SafsNtfSpecificProblem   *message,
                      uint8_t             *out);
size_t safs_ntf_specific_problem__pack_to_buffer
                     (const SafsNtfSpecificProblem   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfSpecificProblem *
       safs_ntf_specific_problem__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_specific_problem__free_unpacked
                     (SafsNtfSpecificProblem *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfCallbacks methods */
void   safs_ntf_callbacks__init
                     (SafsNtfCallbacks         *message);
size_t safs_ntf_callbacks__get_packed_size
                     (const SafsNtfCallbacks   *message);
size_t safs_ntf_callbacks__pack
                     (const SafsNtfCallbacks   *message,
                      uint8_t             *out);
size_t safs_ntf_callbacks__pack_to_buffer
                     (const SafsNtfCallbacks   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfCallbacks *
       safs_ntf_callbacks__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_callbacks__free_unpacked
                     (SafsNtfCallbacks *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfThresholdInformation methods */
void   safs_ntf_threshold_information__init
                     (SafsNtfThresholdInformation         *message);
size_t safs_ntf_threshold_information__get_packed_size
                     (const SafsNtfThresholdInformation   *message);
size_t safs_ntf_threshold_information__pack
                     (const SafsNtfThresholdInformation   *message,
                      uint8_t             *out);
size_t safs_ntf_threshold_information__pack_to_buffer
                     (const SafsNtfThresholdInformation   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfThresholdInformation *
       safs_ntf_threshold_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_threshold_information__free_unpacked
                     (SafsNtfThresholdInformation *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfProposedRepairAction methods */
void   safs_ntf_proposed_repair_action__init
                     (SafsNtfProposedRepairAction         *message);
size_t safs_ntf_proposed_repair_action__get_packed_size
                     (const SafsNtfProposedRepairAction   *message);
size_t safs_ntf_proposed_repair_action__pack
                     (const SafsNtfProposedRepairAction   *message,
                      uint8_t             *out);
size_t safs_ntf_proposed_repair_action__pack_to_buffer
                     (const SafsNtfProposedRepairAction   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfProposedRepairAction *
       safs_ntf_proposed_repair_action__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_proposed_repair_action__free_unpacked
                     (SafsNtfProposedRepairAction *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfStateChange methods */
void   safs_ntf_state_change__init
                     (SafsNtfStateChange         *message);
size_t safs_ntf_state_change__get_packed_size
                     (const SafsNtfStateChange   *message);
size_t safs_ntf_state_change__pack
                     (const SafsNtfStateChange   *message,
                      uint8_t             *out);
size_t safs_ntf_state_change__pack_to_buffer
                     (const SafsNtfStateChange   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfStateChange *
       safs_ntf_state_change__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_state_change__free_unpacked
                     (SafsNtfStateChange *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfAttribute methods */
void   safs_ntf_attribute__init
                     (SafsNtfAttribute         *message);
size_t safs_ntf_attribute__get_packed_size
                     (const SafsNtfAttribute   *message);
size_t safs_ntf_attribute__pack
                     (const SafsNtfAttribute   *message,
                      uint8_t             *out);
size_t safs_ntf_attribute__pack_to_buffer
                     (const SafsNtfAttribute   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfAttribute *
       safs_ntf_attribute__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_attribute__free_unpacked
                     (SafsNtfAttribute *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfAttributeChange methods */
void   safs_ntf_attribute_change__init
                     (SafsNtfAttributeChange         *message);
size_t safs_ntf_attribute_change__get_packed_size
                     (const SafsNtfAttributeChange   *message);
size_t safs_ntf_attribute_change__pack
                     (const SafsNtfAttributeChange   *message,
                      uint8_t             *out);
size_t safs_ntf_attribute_change__pack_to_buffer
                     (const SafsNtfAttributeChange   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfAttributeChange *
       safs_ntf_attribute_change__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_attribute_change__free_unpacked
                     (SafsNtfAttributeChange *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfServiceUser methods */
void   safs_ntf_service_user__init
                     (SafsNtfServiceUser         *message);
size_t safs_ntf_service_user__get_packed_size
                     (const SafsNtfServiceUser   *message);
size_t safs_ntf_service_user__pack
                     (const SafsNtfServiceUser   *message,
                      uint8_t             *out);
size_t safs_ntf_service_user__pack_to_buffer
                     (const SafsNtfServiceUser   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfServiceUser *
       safs_ntf_service_user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_service_user__free_unpacked
                     (SafsNtfServiceUser *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfSecurityAlarmDetector methods */
void   safs_ntf_security_alarm_detector__init
                     (SafsNtfSecurityAlarmDetector         *message);
size_t safs_ntf_security_alarm_detector__get_packed_size
                     (const SafsNtfSecurityAlarmDetector   *message);
size_t safs_ntf_security_alarm_detector__pack
                     (const SafsNtfSecurityAlarmDetector   *message,
                      uint8_t             *out);
size_t safs_ntf_security_alarm_detector__pack_to_buffer
                     (const SafsNtfSecurityAlarmDetector   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfSecurityAlarmDetector *
       safs_ntf_security_alarm_detector__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_security_alarm_detector__free_unpacked
                     (SafsNtfSecurityAlarmDetector *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfNotificationHeader methods */
void   safs_ntf_notification_header__init
                     (SafsNtfNotificationHeader         *message);
size_t safs_ntf_notification_header__get_packed_size
                     (const SafsNtfNotificationHeader   *message);
size_t safs_ntf_notification_header__pack
                     (const SafsNtfNotificationHeader   *message,
                      uint8_t             *out);
size_t safs_ntf_notification_header__pack_to_buffer
                     (const SafsNtfNotificationHeader   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfNotificationHeader *
       safs_ntf_notification_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_notification_header__free_unpacked
                     (SafsNtfNotificationHeader *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfObjectCreateDeleteNotification methods */
void   safs_ntf_object_create_delete_notification__init
                     (SafsNtfObjectCreateDeleteNotification         *message);
size_t safs_ntf_object_create_delete_notification__get_packed_size
                     (const SafsNtfObjectCreateDeleteNotification   *message);
size_t safs_ntf_object_create_delete_notification__pack
                     (const SafsNtfObjectCreateDeleteNotification   *message,
                      uint8_t             *out);
size_t safs_ntf_object_create_delete_notification__pack_to_buffer
                     (const SafsNtfObjectCreateDeleteNotification   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfObjectCreateDeleteNotification *
       safs_ntf_object_create_delete_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_object_create_delete_notification__free_unpacked
                     (SafsNtfObjectCreateDeleteNotification *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfAttributeChangeNotification methods */
void   safs_ntf_attribute_change_notification__init
                     (SafsNtfAttributeChangeNotification         *message);
size_t safs_ntf_attribute_change_notification__get_packed_size
                     (const SafsNtfAttributeChangeNotification   *message);
size_t safs_ntf_attribute_change_notification__pack
                     (const SafsNtfAttributeChangeNotification   *message,
                      uint8_t             *out);
size_t safs_ntf_attribute_change_notification__pack_to_buffer
                     (const SafsNtfAttributeChangeNotification   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfAttributeChangeNotification *
       safs_ntf_attribute_change_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_attribute_change_notification__free_unpacked
                     (SafsNtfAttributeChangeNotification *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfStateChangeNotification methods */
void   safs_ntf_state_change_notification__init
                     (SafsNtfStateChangeNotification         *message);
size_t safs_ntf_state_change_notification__get_packed_size
                     (const SafsNtfStateChangeNotification   *message);
size_t safs_ntf_state_change_notification__pack
                     (const SafsNtfStateChangeNotification   *message,
                      uint8_t             *out);
size_t safs_ntf_state_change_notification__pack_to_buffer
                     (const SafsNtfStateChangeNotification   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfStateChangeNotification *
       safs_ntf_state_change_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_state_change_notification__free_unpacked
                     (SafsNtfStateChangeNotification *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfAlarmNotification methods */
void   safs_ntf_alarm_notification__init
                     (SafsNtfAlarmNotification         *message);
size_t safs_ntf_alarm_notification__get_packed_size
                     (const SafsNtfAlarmNotification   *message);
size_t safs_ntf_alarm_notification__pack
                     (const SafsNtfAlarmNotification   *message,
                      uint8_t             *out);
size_t safs_ntf_alarm_notification__pack_to_buffer
                     (const SafsNtfAlarmNotification   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfAlarmNotification *
       safs_ntf_alarm_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_alarm_notification__free_unpacked
                     (SafsNtfAlarmNotification *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfSecurityAlarmNotification methods */
void   safs_ntf_security_alarm_notification__init
                     (SafsNtfSecurityAlarmNotification         *message);
size_t safs_ntf_security_alarm_notification__get_packed_size
                     (const SafsNtfSecurityAlarmNotification   *message);
size_t safs_ntf_security_alarm_notification__pack
                     (const SafsNtfSecurityAlarmNotification   *message,
                      uint8_t             *out);
size_t safs_ntf_security_alarm_notification__pack_to_buffer
                     (const SafsNtfSecurityAlarmNotification   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfSecurityAlarmNotification *
       safs_ntf_security_alarm_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_security_alarm_notification__free_unpacked
                     (SafsNtfSecurityAlarmNotification *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfNotificationFilterHeader methods */
void   safs_ntf_notification_filter_header__init
                     (SafsNtfNotificationFilterHeader         *message);
size_t safs_ntf_notification_filter_header__get_packed_size
                     (const SafsNtfNotificationFilterHeader   *message);
size_t safs_ntf_notification_filter_header__pack
                     (const SafsNtfNotificationFilterHeader   *message,
                      uint8_t             *out);
size_t safs_ntf_notification_filter_header__pack_to_buffer
                     (const SafsNtfNotificationFilterHeader   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfNotificationFilterHeader *
       safs_ntf_notification_filter_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_notification_filter_header__free_unpacked
                     (SafsNtfNotificationFilterHeader *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfObjectCreateDeleteNotificationFilter methods */
void   safs_ntf_object_create_delete_notification_filter__init
                     (SafsNtfObjectCreateDeleteNotificationFilter         *message);
size_t safs_ntf_object_create_delete_notification_filter__get_packed_size
                     (const SafsNtfObjectCreateDeleteNotificationFilter   *message);
size_t safs_ntf_object_create_delete_notification_filter__pack
                     (const SafsNtfObjectCreateDeleteNotificationFilter   *message,
                      uint8_t             *out);
size_t safs_ntf_object_create_delete_notification_filter__pack_to_buffer
                     (const SafsNtfObjectCreateDeleteNotificationFilter   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfObjectCreateDeleteNotificationFilter *
       safs_ntf_object_create_delete_notification_filter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_object_create_delete_notification_filter__free_unpacked
                     (SafsNtfObjectCreateDeleteNotificationFilter *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfAttributeChangeNotificationFilter methods */
void   safs_ntf_attribute_change_notification_filter__init
                     (SafsNtfAttributeChangeNotificationFilter         *message);
size_t safs_ntf_attribute_change_notification_filter__get_packed_size
                     (const SafsNtfAttributeChangeNotificationFilter   *message);
size_t safs_ntf_attribute_change_notification_filter__pack
                     (const SafsNtfAttributeChangeNotificationFilter   *message,
                      uint8_t             *out);
size_t safs_ntf_attribute_change_notification_filter__pack_to_buffer
                     (const SafsNtfAttributeChangeNotificationFilter   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfAttributeChangeNotificationFilter *
       safs_ntf_attribute_change_notification_filter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_attribute_change_notification_filter__free_unpacked
                     (SafsNtfAttributeChangeNotificationFilter *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfStateChangeNotificationFilter methods */
void   safs_ntf_state_change_notification_filter__init
                     (SafsNtfStateChangeNotificationFilter         *message);
size_t safs_ntf_state_change_notification_filter__get_packed_size
                     (const SafsNtfStateChangeNotificationFilter   *message);
size_t safs_ntf_state_change_notification_filter__pack
                     (const SafsNtfStateChangeNotificationFilter   *message,
                      uint8_t             *out);
size_t safs_ntf_state_change_notification_filter__pack_to_buffer
                     (const SafsNtfStateChangeNotificationFilter   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfStateChangeNotificationFilter *
       safs_ntf_state_change_notification_filter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_state_change_notification_filter__free_unpacked
                     (SafsNtfStateChangeNotificationFilter *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfAlarmNotificationFilter methods */
void   safs_ntf_alarm_notification_filter__init
                     (SafsNtfAlarmNotificationFilter         *message);
size_t safs_ntf_alarm_notification_filter__get_packed_size
                     (const SafsNtfAlarmNotificationFilter   *message);
size_t safs_ntf_alarm_notification_filter__pack
                     (const SafsNtfAlarmNotificationFilter   *message,
                      uint8_t             *out);
size_t safs_ntf_alarm_notification_filter__pack_to_buffer
                     (const SafsNtfAlarmNotificationFilter   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfAlarmNotificationFilter *
       safs_ntf_alarm_notification_filter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_alarm_notification_filter__free_unpacked
                     (SafsNtfAlarmNotificationFilter *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfSecurityAlarmNotificationFilter methods */
void   safs_ntf_security_alarm_notification_filter__init
                     (SafsNtfSecurityAlarmNotificationFilter         *message);
size_t safs_ntf_security_alarm_notification_filter__get_packed_size
                     (const SafsNtfSecurityAlarmNotificationFilter   *message);
size_t safs_ntf_security_alarm_notification_filter__pack
                     (const SafsNtfSecurityAlarmNotificationFilter   *message,
                      uint8_t             *out);
size_t safs_ntf_security_alarm_notification_filter__pack_to_buffer
                     (const SafsNtfSecurityAlarmNotificationFilter   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfSecurityAlarmNotificationFilter *
       safs_ntf_security_alarm_notification_filter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_security_alarm_notification_filter__free_unpacked
                     (SafsNtfSecurityAlarmNotificationFilter *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfSearchCriteria methods */
void   safs_ntf_search_criteria__init
                     (SafsNtfSearchCriteria         *message);
size_t safs_ntf_search_criteria__get_packed_size
                     (const SafsNtfSearchCriteria   *message);
size_t safs_ntf_search_criteria__pack
                     (const SafsNtfSearchCriteria   *message,
                      uint8_t             *out);
size_t safs_ntf_search_criteria__pack_to_buffer
                     (const SafsNtfSearchCriteria   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfSearchCriteria *
       safs_ntf_search_criteria__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_search_criteria__free_unpacked
                     (SafsNtfSearchCriteria *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfNotificationTypeFilters methods */
void   safs_ntf_notification_type_filters__init
                     (SafsNtfNotificationTypeFilters         *message);
size_t safs_ntf_notification_type_filters__get_packed_size
                     (const SafsNtfNotificationTypeFilters   *message);
size_t safs_ntf_notification_type_filters__pack
                     (const SafsNtfNotificationTypeFilters   *message,
                      uint8_t             *out);
size_t safs_ntf_notification_type_filters__pack_to_buffer
                     (const SafsNtfNotificationTypeFilters   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfNotificationTypeFilters *
       safs_ntf_notification_type_filters__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_notification_type_filters__free_unpacked
                     (SafsNtfNotificationTypeFilters *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfNotification methods */
void   safs_ntf_notification__init
                     (SafsNtfNotification         *message);
size_t safs_ntf_notification__get_packed_size
                     (const SafsNtfNotification   *message);
size_t safs_ntf_notification__pack
                     (const SafsNtfNotification   *message,
                      uint8_t             *out);
size_t safs_ntf_notification__pack_to_buffer
                     (const SafsNtfNotification   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfNotification *
       safs_ntf_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_notification__free_unpacked
                     (SafsNtfNotification *message,
                      ProtobufCAllocator *allocator);
/* SaNtfNotificationCallback methods */
void   sa_ntf_notification_callback__init
                     (SaNtfNotificationCallback         *message);
size_t sa_ntf_notification_callback__get_packed_size
                     (const SaNtfNotificationCallback   *message);
size_t sa_ntf_notification_callback__pack
                     (const SaNtfNotificationCallback   *message,
                      uint8_t             *out);
size_t sa_ntf_notification_callback__pack_to_buffer
                     (const SaNtfNotificationCallback   *message,
                      ProtobufCBuffer     *buffer);
SaNtfNotificationCallback *
       sa_ntf_notification_callback__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sa_ntf_notification_callback__free_unpacked
                     (SaNtfNotificationCallback *message,
                      ProtobufCAllocator *allocator);
/* SaNtfNotificationDiscardedCallback methods */
void   sa_ntf_notification_discarded_callback__init
                     (SaNtfNotificationDiscardedCallback         *message);
size_t sa_ntf_notification_discarded_callback__get_packed_size
                     (const SaNtfNotificationDiscardedCallback   *message);
size_t sa_ntf_notification_discarded_callback__pack
                     (const SaNtfNotificationDiscardedCallback   *message,
                      uint8_t             *out);
size_t sa_ntf_notification_discarded_callback__pack_to_buffer
                     (const SaNtfNotificationDiscardedCallback   *message,
                      ProtobufCBuffer     *buffer);
SaNtfNotificationDiscardedCallback *
       sa_ntf_notification_discarded_callback__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sa_ntf_notification_discarded_callback__free_unpacked
                     (SaNtfNotificationDiscardedCallback *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfInitialize methods */
void   safs_ntf_initialize__init
                     (SafsNtfInitialize         *message);
size_t safs_ntf_initialize__get_packed_size
                     (const SafsNtfInitialize   *message);
size_t safs_ntf_initialize__pack
                     (const SafsNtfInitialize   *message,
                      uint8_t             *out);
size_t safs_ntf_initialize__pack_to_buffer
                     (const SafsNtfInitialize   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfInitialize *
       safs_ntf_initialize__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_initialize__free_unpacked
                     (SafsNtfInitialize *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfFinalize methods */
void   safs_ntf_finalize__init
                     (SafsNtfFinalize         *message);
size_t safs_ntf_finalize__get_packed_size
                     (const SafsNtfFinalize   *message);
size_t safs_ntf_finalize__pack
                     (const SafsNtfFinalize   *message,
                      uint8_t             *out);
size_t safs_ntf_finalize__pack_to_buffer
                     (const SafsNtfFinalize   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfFinalize *
       safs_ntf_finalize__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_finalize__free_unpacked
                     (SafsNtfFinalize *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfNotificationSend methods */
void   safs_ntf_notification_send__init
                     (SafsNtfNotificationSend         *message);
size_t safs_ntf_notification_send__get_packed_size
                     (const SafsNtfNotificationSend   *message);
size_t safs_ntf_notification_send__pack
                     (const SafsNtfNotificationSend   *message,
                      uint8_t             *out);
size_t safs_ntf_notification_send__pack_to_buffer
                     (const SafsNtfNotificationSend   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfNotificationSend *
       safs_ntf_notification_send__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_notification_send__free_unpacked
                     (SafsNtfNotificationSend *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfNotificationSubscribe methods */
void   safs_ntf_notification_subscribe__init
                     (SafsNtfNotificationSubscribe         *message);
size_t safs_ntf_notification_subscribe__get_packed_size
                     (const SafsNtfNotificationSubscribe   *message);
size_t safs_ntf_notification_subscribe__pack
                     (const SafsNtfNotificationSubscribe   *message,
                      uint8_t             *out);
size_t safs_ntf_notification_subscribe__pack_to_buffer
                     (const SafsNtfNotificationSubscribe   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfNotificationSubscribe *
       safs_ntf_notification_subscribe__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_notification_subscribe__free_unpacked
                     (SafsNtfNotificationSubscribe *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfNotificationUnsubscribe methods */
void   safs_ntf_notification_unsubscribe__init
                     (SafsNtfNotificationUnsubscribe         *message);
size_t safs_ntf_notification_unsubscribe__get_packed_size
                     (const SafsNtfNotificationUnsubscribe   *message);
size_t safs_ntf_notification_unsubscribe__pack
                     (const SafsNtfNotificationUnsubscribe   *message,
                      uint8_t             *out);
size_t safs_ntf_notification_unsubscribe__pack_to_buffer
                     (const SafsNtfNotificationUnsubscribe   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfNotificationUnsubscribe *
       safs_ntf_notification_unsubscribe__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_notification_unsubscribe__free_unpacked
                     (SafsNtfNotificationUnsubscribe *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfNotificationReadInitialize methods */
void   safs_ntf_notification_read_initialize__init
                     (SafsNtfNotificationReadInitialize         *message);
size_t safs_ntf_notification_read_initialize__get_packed_size
                     (const SafsNtfNotificationReadInitialize   *message);
size_t safs_ntf_notification_read_initialize__pack
                     (const SafsNtfNotificationReadInitialize   *message,
                      uint8_t             *out);
size_t safs_ntf_notification_read_initialize__pack_to_buffer
                     (const SafsNtfNotificationReadInitialize   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfNotificationReadInitialize *
       safs_ntf_notification_read_initialize__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_notification_read_initialize__free_unpacked
                     (SafsNtfNotificationReadInitialize *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfNotificationReadNext methods */
void   safs_ntf_notification_read_next__init
                     (SafsNtfNotificationReadNext         *message);
size_t safs_ntf_notification_read_next__get_packed_size
                     (const SafsNtfNotificationReadNext   *message);
size_t safs_ntf_notification_read_next__pack
                     (const SafsNtfNotificationReadNext   *message,
                      uint8_t             *out);
size_t safs_ntf_notification_read_next__pack_to_buffer
                     (const SafsNtfNotificationReadNext   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfNotificationReadNext *
       safs_ntf_notification_read_next__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_notification_read_next__free_unpacked
                     (SafsNtfNotificationReadNext *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfNotificationReadFinalize methods */
void   safs_ntf_notification_read_finalize__init
                     (SafsNtfNotificationReadFinalize         *message);
size_t safs_ntf_notification_read_finalize__get_packed_size
                     (const SafsNtfNotificationReadFinalize   *message);
size_t safs_ntf_notification_read_finalize__pack
                     (const SafsNtfNotificationReadFinalize   *message,
                      uint8_t             *out);
size_t safs_ntf_notification_read_finalize__pack_to_buffer
                     (const SafsNtfNotificationReadFinalize   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfNotificationReadFinalize *
       safs_ntf_notification_read_finalize__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_notification_read_finalize__free_unpacked
                     (SafsNtfNotificationReadFinalize *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfCallbacksInitialize methods */
void   safs_ntf_callbacks_initialize__init
                     (SafsNtfCallbacksInitialize         *message);
size_t safs_ntf_callbacks_initialize__get_packed_size
                     (const SafsNtfCallbacksInitialize   *message);
size_t safs_ntf_callbacks_initialize__pack
                     (const SafsNtfCallbacksInitialize   *message,
                      uint8_t             *out);
size_t safs_ntf_callbacks_initialize__pack_to_buffer
                     (const SafsNtfCallbacksInitialize   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfCallbacksInitialize *
       safs_ntf_callbacks_initialize__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_callbacks_initialize__free_unpacked
                     (SafsNtfCallbacksInitialize *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfMessage methods */
void   safs_ntf_message__init
                     (SafsNtfMessage         *message);
size_t safs_ntf_message__get_packed_size
                     (const SafsNtfMessage   *message);
size_t safs_ntf_message__pack
                     (const SafsNtfMessage   *message,
                      uint8_t             *out);
size_t safs_ntf_message__pack_to_buffer
                     (const SafsNtfMessage   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfMessage *
       safs_ntf_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_message__free_unpacked
                     (SafsNtfMessage *message,
                      ProtobufCAllocator *allocator);
/* SaNtfCallbacks methods */
void   sa_ntf_callbacks__init
                     (SaNtfCallbacks         *message);
size_t sa_ntf_callbacks__get_packed_size
                     (const SaNtfCallbacks   *message);
size_t sa_ntf_callbacks__pack
                     (const SaNtfCallbacks   *message,
                      uint8_t             *out);
size_t sa_ntf_callbacks__pack_to_buffer
                     (const SaNtfCallbacks   *message,
                      ProtobufCBuffer     *buffer);
SaNtfCallbacks *
       sa_ntf_callbacks__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sa_ntf_callbacks__free_unpacked
                     (SaNtfCallbacks *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfInitializeRet methods */
void   safs_ntf_initialize_ret__init
                     (SafsNtfInitializeRet         *message);
size_t safs_ntf_initialize_ret__get_packed_size
                     (const SafsNtfInitializeRet   *message);
size_t safs_ntf_initialize_ret__pack
                     (const SafsNtfInitializeRet   *message,
                      uint8_t             *out);
size_t safs_ntf_initialize_ret__pack_to_buffer
                     (const SafsNtfInitializeRet   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfInitializeRet *
       safs_ntf_initialize_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_initialize_ret__free_unpacked
                     (SafsNtfInitializeRet *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfFinalizeRet methods */
void   safs_ntf_finalize_ret__init
                     (SafsNtfFinalizeRet         *message);
size_t safs_ntf_finalize_ret__get_packed_size
                     (const SafsNtfFinalizeRet   *message);
size_t safs_ntf_finalize_ret__pack
                     (const SafsNtfFinalizeRet   *message,
                      uint8_t             *out);
size_t safs_ntf_finalize_ret__pack_to_buffer
                     (const SafsNtfFinalizeRet   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfFinalizeRet *
       safs_ntf_finalize_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_finalize_ret__free_unpacked
                     (SafsNtfFinalizeRet *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfNotificationSendRet methods */
void   safs_ntf_notification_send_ret__init
                     (SafsNtfNotificationSendRet         *message);
size_t safs_ntf_notification_send_ret__get_packed_size
                     (const SafsNtfNotificationSendRet   *message);
size_t safs_ntf_notification_send_ret__pack
                     (const SafsNtfNotificationSendRet   *message,
                      uint8_t             *out);
size_t safs_ntf_notification_send_ret__pack_to_buffer
                     (const SafsNtfNotificationSendRet   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfNotificationSendRet *
       safs_ntf_notification_send_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_notification_send_ret__free_unpacked
                     (SafsNtfNotificationSendRet *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfNotificationSubscribeRet methods */
void   safs_ntf_notification_subscribe_ret__init
                     (SafsNtfNotificationSubscribeRet         *message);
size_t safs_ntf_notification_subscribe_ret__get_packed_size
                     (const SafsNtfNotificationSubscribeRet   *message);
size_t safs_ntf_notification_subscribe_ret__pack
                     (const SafsNtfNotificationSubscribeRet   *message,
                      uint8_t             *out);
size_t safs_ntf_notification_subscribe_ret__pack_to_buffer
                     (const SafsNtfNotificationSubscribeRet   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfNotificationSubscribeRet *
       safs_ntf_notification_subscribe_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_notification_subscribe_ret__free_unpacked
                     (SafsNtfNotificationSubscribeRet *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfNotificationUnsubscribeRet methods */
void   safs_ntf_notification_unsubscribe_ret__init
                     (SafsNtfNotificationUnsubscribeRet         *message);
size_t safs_ntf_notification_unsubscribe_ret__get_packed_size
                     (const SafsNtfNotificationUnsubscribeRet   *message);
size_t safs_ntf_notification_unsubscribe_ret__pack
                     (const SafsNtfNotificationUnsubscribeRet   *message,
                      uint8_t             *out);
size_t safs_ntf_notification_unsubscribe_ret__pack_to_buffer
                     (const SafsNtfNotificationUnsubscribeRet   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfNotificationUnsubscribeRet *
       safs_ntf_notification_unsubscribe_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_notification_unsubscribe_ret__free_unpacked
                     (SafsNtfNotificationUnsubscribeRet *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfNotificationReadInitializeRet methods */
void   safs_ntf_notification_read_initialize_ret__init
                     (SafsNtfNotificationReadInitializeRet         *message);
size_t safs_ntf_notification_read_initialize_ret__get_packed_size
                     (const SafsNtfNotificationReadInitializeRet   *message);
size_t safs_ntf_notification_read_initialize_ret__pack
                     (const SafsNtfNotificationReadInitializeRet   *message,
                      uint8_t             *out);
size_t safs_ntf_notification_read_initialize_ret__pack_to_buffer
                     (const SafsNtfNotificationReadInitializeRet   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfNotificationReadInitializeRet *
       safs_ntf_notification_read_initialize_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_notification_read_initialize_ret__free_unpacked
                     (SafsNtfNotificationReadInitializeRet *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfNotificationReadNextRet methods */
void   safs_ntf_notification_read_next_ret__init
                     (SafsNtfNotificationReadNextRet         *message);
size_t safs_ntf_notification_read_next_ret__get_packed_size
                     (const SafsNtfNotificationReadNextRet   *message);
size_t safs_ntf_notification_read_next_ret__pack
                     (const SafsNtfNotificationReadNextRet   *message,
                      uint8_t             *out);
size_t safs_ntf_notification_read_next_ret__pack_to_buffer
                     (const SafsNtfNotificationReadNextRet   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfNotificationReadNextRet *
       safs_ntf_notification_read_next_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_notification_read_next_ret__free_unpacked
                     (SafsNtfNotificationReadNextRet *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfNotificationReadFinalizeRet methods */
void   safs_ntf_notification_read_finalize_ret__init
                     (SafsNtfNotificationReadFinalizeRet         *message);
size_t safs_ntf_notification_read_finalize_ret__get_packed_size
                     (const SafsNtfNotificationReadFinalizeRet   *message);
size_t safs_ntf_notification_read_finalize_ret__pack
                     (const SafsNtfNotificationReadFinalizeRet   *message,
                      uint8_t             *out);
size_t safs_ntf_notification_read_finalize_ret__pack_to_buffer
                     (const SafsNtfNotificationReadFinalizeRet   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfNotificationReadFinalizeRet *
       safs_ntf_notification_read_finalize_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_notification_read_finalize_ret__free_unpacked
                     (SafsNtfNotificationReadFinalizeRet *message,
                      ProtobufCAllocator *allocator);
/* SafsNtfCallbacksInitializeRet methods */
void   safs_ntf_callbacks_initialize_ret__init
                     (SafsNtfCallbacksInitializeRet         *message);
size_t safs_ntf_callbacks_initialize_ret__get_packed_size
                     (const SafsNtfCallbacksInitializeRet   *message);
size_t safs_ntf_callbacks_initialize_ret__pack
                     (const SafsNtfCallbacksInitializeRet   *message,
                      uint8_t             *out);
size_t safs_ntf_callbacks_initialize_ret__pack_to_buffer
                     (const SafsNtfCallbacksInitializeRet   *message,
                      ProtobufCBuffer     *buffer);
SafsNtfCallbacksInitializeRet *
       safs_ntf_callbacks_initialize_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_ntf_callbacks_initialize_ret__free_unpacked
                     (SafsNtfCallbacksInitializeRet *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SafsNtfClassId_Closure)
                 (const SafsNtfClassId *message,
                  void *closure_data);
typedef void (*SafsNtfValue_Closure)
                 (const SafsNtfValue *message,
                  void *closure_data);
typedef void (*SafsNtfAdditionalInfo_Closure)
                 (const SafsNtfAdditionalInfo *message,
                  void *closure_data);
typedef void (*SafsNtfSpecificProblem_Closure)
                 (const SafsNtfSpecificProblem *message,
                  void *closure_data);
typedef void (*SafsNtfCallbacks_Closure)
                 (const SafsNtfCallbacks *message,
                  void *closure_data);
typedef void (*SafsNtfThresholdInformation_Closure)
                 (const SafsNtfThresholdInformation *message,
                  void *closure_data);
typedef void (*SafsNtfProposedRepairAction_Closure)
                 (const SafsNtfProposedRepairAction *message,
                  void *closure_data);
typedef void (*SafsNtfStateChange_Closure)
                 (const SafsNtfStateChange *message,
                  void *closure_data);
typedef void (*SafsNtfAttribute_Closure)
                 (const SafsNtfAttribute *message,
                  void *closure_data);
typedef void (*SafsNtfAttributeChange_Closure)
                 (const SafsNtfAttributeChange *message,
                  void *closure_data);
typedef void (*SafsNtfServiceUser_Closure)
                 (const SafsNtfServiceUser *message,
                  void *closure_data);
typedef void (*SafsNtfSecurityAlarmDetector_Closure)
                 (const SafsNtfSecurityAlarmDetector *message,
                  void *closure_data);
typedef void (*SafsNtfNotificationHeader_Closure)
                 (const SafsNtfNotificationHeader *message,
                  void *closure_data);
typedef void (*SafsNtfObjectCreateDeleteNotification_Closure)
                 (const SafsNtfObjectCreateDeleteNotification *message,
                  void *closure_data);
typedef void (*SafsNtfAttributeChangeNotification_Closure)
                 (const SafsNtfAttributeChangeNotification *message,
                  void *closure_data);
typedef void (*SafsNtfStateChangeNotification_Closure)
                 (const SafsNtfStateChangeNotification *message,
                  void *closure_data);
typedef void (*SafsNtfAlarmNotification_Closure)
                 (const SafsNtfAlarmNotification *message,
                  void *closure_data);
typedef void (*SafsNtfSecurityAlarmNotification_Closure)
                 (const SafsNtfSecurityAlarmNotification *message,
                  void *closure_data);
typedef void (*SafsNtfNotificationFilterHeader_Closure)
                 (const SafsNtfNotificationFilterHeader *message,
                  void *closure_data);
typedef void (*SafsNtfObjectCreateDeleteNotificationFilter_Closure)
                 (const SafsNtfObjectCreateDeleteNotificationFilter *message,
                  void *closure_data);
typedef void (*SafsNtfAttributeChangeNotificationFilter_Closure)
                 (const SafsNtfAttributeChangeNotificationFilter *message,
                  void *closure_data);
typedef void (*SafsNtfStateChangeNotificationFilter_Closure)
                 (const SafsNtfStateChangeNotificationFilter *message,
                  void *closure_data);
typedef void (*SafsNtfAlarmNotificationFilter_Closure)
                 (const SafsNtfAlarmNotificationFilter *message,
                  void *closure_data);
typedef void (*SafsNtfSecurityAlarmNotificationFilter_Closure)
                 (const SafsNtfSecurityAlarmNotificationFilter *message,
                  void *closure_data);
typedef void (*SafsNtfSearchCriteria_Closure)
                 (const SafsNtfSearchCriteria *message,
                  void *closure_data);
typedef void (*SafsNtfNotificationTypeFilters_Closure)
                 (const SafsNtfNotificationTypeFilters *message,
                  void *closure_data);
typedef void (*SafsNtfNotification_Closure)
                 (const SafsNtfNotification *message,
                  void *closure_data);
typedef void (*SaNtfNotificationCallback_Closure)
                 (const SaNtfNotificationCallback *message,
                  void *closure_data);
typedef void (*SaNtfNotificationDiscardedCallback_Closure)
                 (const SaNtfNotificationDiscardedCallback *message,
                  void *closure_data);
typedef void (*SafsNtfInitialize_Closure)
                 (const SafsNtfInitialize *message,
                  void *closure_data);
typedef void (*SafsNtfFinalize_Closure)
                 (const SafsNtfFinalize *message,
                  void *closure_data);
typedef void (*SafsNtfNotificationSend_Closure)
                 (const SafsNtfNotificationSend *message,
                  void *closure_data);
typedef void (*SafsNtfNotificationSubscribe_Closure)
                 (const SafsNtfNotificationSubscribe *message,
                  void *closure_data);
typedef void (*SafsNtfNotificationUnsubscribe_Closure)
                 (const SafsNtfNotificationUnsubscribe *message,
                  void *closure_data);
typedef void (*SafsNtfNotificationReadInitialize_Closure)
                 (const SafsNtfNotificationReadInitialize *message,
                  void *closure_data);
typedef void (*SafsNtfNotificationReadNext_Closure)
                 (const SafsNtfNotificationReadNext *message,
                  void *closure_data);
typedef void (*SafsNtfNotificationReadFinalize_Closure)
                 (const SafsNtfNotificationReadFinalize *message,
                  void *closure_data);
typedef void (*SafsNtfCallbacksInitialize_Closure)
                 (const SafsNtfCallbacksInitialize *message,
                  void *closure_data);
typedef void (*SafsNtfMessage_Closure)
                 (const SafsNtfMessage *message,
                  void *closure_data);
typedef void (*SaNtfCallbacks_Closure)
                 (const SaNtfCallbacks *message,
                  void *closure_data);
typedef void (*SafsNtfInitializeRet_Closure)
                 (const SafsNtfInitializeRet *message,
                  void *closure_data);
typedef void (*SafsNtfFinalizeRet_Closure)
                 (const SafsNtfFinalizeRet *message,
                  void *closure_data);
typedef void (*SafsNtfNotificationSendRet_Closure)
                 (const SafsNtfNotificationSendRet *message,
                  void *closure_data);
typedef void (*SafsNtfNotificationSubscribeRet_Closure)
                 (const SafsNtfNotificationSubscribeRet *message,
                  void *closure_data);
typedef void (*SafsNtfNotificationUnsubscribeRet_Closure)
                 (const SafsNtfNotificationUnsubscribeRet *message,
                  void *closure_data);
typedef void (*SafsNtfNotificationReadInitializeRet_Closure)
                 (const SafsNtfNotificationReadInitializeRet *message,
                  void *closure_data);
typedef void (*SafsNtfNotificationReadNextRet_Closure)
                 (const SafsNtfNotificationReadNextRet *message,
                  void *closure_data);
typedef void (*SafsNtfNotificationReadFinalizeRet_Closure)
                 (const SafsNtfNotificationReadFinalizeRet *message,
                  void *closure_data);
typedef void (*SafsNtfCallbacksInitializeRet_Closure)
                 (const SafsNtfCallbacksInitializeRet *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    safs_ntf_notification_type__descriptor;
extern const ProtobufCEnumDescriptor    safs_ntf_event_type__descriptor;
extern const ProtobufCEnumDescriptor    safs_ntf_value_type__descriptor;
extern const ProtobufCEnumDescriptor    safs_ntf_probable_cause__descriptor;
extern const ProtobufCEnumDescriptor    safs_ntf_severity__descriptor;
extern const ProtobufCEnumDescriptor    safs_ntf_severity_trend__descriptor;
extern const ProtobufCEnumDescriptor    safs_ntf_source_indicator__descriptor;
extern const ProtobufCEnumDescriptor    safs_ntf_search_mode__descriptor;
extern const ProtobufCEnumDescriptor    safs_ntf_search_direction__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_class_id__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_value__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_additional_info__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_specific_problem__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_callbacks__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_threshold_information__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_proposed_repair_action__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_state_change__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_attribute__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_attribute_change__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_service_user__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_security_alarm_detector__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_notification_header__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_object_create_delete_notification__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_attribute_change_notification__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_state_change_notification__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_alarm_notification__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_security_alarm_notification__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_notification_filter_header__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_object_create_delete_notification_filter__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_attribute_change_notification_filter__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_state_change_notification_filter__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_alarm_notification_filter__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_security_alarm_notification_filter__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_search_criteria__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_notification_type_filters__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_notification__descriptor;
extern const ProtobufCMessageDescriptor sa_ntf_notification_callback__descriptor;
extern const ProtobufCMessageDescriptor sa_ntf_notification_discarded_callback__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_initialize__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_finalize__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_notification_send__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_notification_subscribe__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_notification_unsubscribe__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_notification_read_initialize__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_notification_read_next__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_notification_read_finalize__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_callbacks_initialize__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_message__descriptor;
extern const ProtobufCMessageDescriptor sa_ntf_callbacks__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_initialize_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_finalize_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_notification_send_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_notification_subscribe_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_notification_unsubscribe_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_notification_read_initialize_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_notification_read_next_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_notification_read_finalize_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_ntf_callbacks_initialize_ret__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_ntf_2eproto__INCLUDED */
