/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "sa_ais.pb-c.h"
void   safs_any__init
                     (SafsAny         *message)
{
  static SafsAny init_value = SAFS_ANY__INIT;
  *message = init_value;
}
size_t safs_any__get_packed_size
                     (const SafsAny *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_any__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_any__pack
                     (const SafsAny *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_any__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_any__pack_to_buffer
                     (const SafsAny *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_any__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsAny *
       safs_any__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsAny *)
     protobuf_c_message_unpack (&safs_any__descriptor,
                                allocator, len, data);
}
void   safs_any__free_unpacked
                     (SafsAny *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_any__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_version__init
                     (SafsVersion         *message)
{
  static SafsVersion init_value = SAFS_VERSION__INIT;
  *message = init_value;
}
size_t safs_version__get_packed_size
                     (const SafsVersion *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_version__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_version__pack
                     (const SafsVersion *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_version__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_version__pack_to_buffer
                     (const SafsVersion *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_version__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsVersion *
       safs_version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsVersion *)
     protobuf_c_message_unpack (&safs_version__descriptor,
                                allocator, len, data);
}
void   safs_version__free_unpacked
                     (SafsVersion *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_version__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor safs_any__field_descriptors[2] =
{
  {
    "bufferSize",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsAny, buffersize),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bufferAddr",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsAny, bufferaddr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_any__field_indices_by_name[] = {
  1,   /* field[1] = bufferAddr */
  0,   /* field[0] = bufferSize */
};
static const ProtobufCIntRange safs_any__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor safs_any__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsAny",
  "SafsAny",
  "SafsAny",
  "",
  sizeof(SafsAny),
  2,
  safs_any__field_descriptors,
  safs_any__field_indices_by_name,
  1,  safs_any__number_ranges,
  (ProtobufCMessageInit) safs_any__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_version__field_descriptors[3] =
{
  {
    "releaseCode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsVersion, releasecode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "majorVersion",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsVersion, majorversion),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minorVersion",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsVersion, minorversion),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_version__field_indices_by_name[] = {
  1,   /* field[1] = majorVersion */
  2,   /* field[2] = minorVersion */
  0,   /* field[0] = releaseCode */
};
static const ProtobufCIntRange safs_version__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor safs_version__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsVersion",
  "SafsVersion",
  "SafsVersion",
  "",
  sizeof(SafsVersion),
  3,
  safs_version__field_descriptors,
  safs_version__field_indices_by_name,
  1,  safs_version__number_ranges,
  (ProtobufCMessageInit) safs_version__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue safs_dispatch_flags__enum_values_by_number[3] =
{
  { "SA_DISPATCH_ONE", "SAFS_DISPATCH_FLAGS__SA_DISPATCH_ONE", 1 },
  { "SA_DISPATCH_ALL", "SAFS_DISPATCH_FLAGS__SA_DISPATCH_ALL", 2 },
  { "SA_DISPATCH_BLOCKING", "SAFS_DISPATCH_FLAGS__SA_DISPATCH_BLOCKING", 3 },
};
static const ProtobufCIntRange safs_dispatch_flags__value_ranges[] = {
{1, 0},{0, 3}
};
const ProtobufCEnumValueIndex safs_dispatch_flags__enum_values_by_name[3] =
{
  { "SA_DISPATCH_ALL", 1 },
  { "SA_DISPATCH_BLOCKING", 2 },
  { "SA_DISPATCH_ONE", 0 },
};
const ProtobufCEnumDescriptor safs_dispatch_flags__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "safsDispatchFlags",
  "safsDispatchFlags",
  "SafsDispatchFlags",
  "",
  3,
  safs_dispatch_flags__enum_values_by_number,
  3,
  safs_dispatch_flags__enum_values_by_name,
  1,
  safs_dispatch_flags__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue safs_ais_error__enum_values_by_number[40] =
{
  { "sa_ais_ok", "SAFS_AIS_ERROR__SA_AIS_OK", 1 },
  { "sa_ais_err_library", "SAFS_AIS_ERROR__SA_AIS_ERR_LIBRARY", 2 },
  { "sa_ais_err_version", "SAFS_AIS_ERROR__SA_AIS_ERR_VERSION", 3 },
  { "sa_ais_err_init", "SAFS_AIS_ERROR__SA_AIS_ERR_INIT", 4 },
  { "sa_ais_err_timeout", "SAFS_AIS_ERROR__SA_AIS_ERR_TIMEOUT", 5 },
  { "sa_ais_err_try_again", "SAFS_AIS_ERROR__SA_AIS_ERR_TRY_AGAIN", 6 },
  { "sa_ais_err_invalid_param", "SAFS_AIS_ERROR__SA_AIS_ERR_INVALID_PARAM", 7 },
  { "sa_ais_err_no_memory", "SAFS_AIS_ERROR__SA_AIS_ERR_NO_MEMORY", 8 },
  { "sa_ais_err_bad_handle", "SAFS_AIS_ERROR__SA_AIS_ERR_BAD_HANDLE", 9 },
  { "sa_ais_err_busy", "SAFS_AIS_ERROR__SA_AIS_ERR_BUSY", 10 },
  { "sa_ais_err_access", "SAFS_AIS_ERROR__SA_AIS_ERR_ACCESS", 11 },
  { "sa_ais_err_not_exist", "SAFS_AIS_ERROR__SA_AIS_ERR_NOT_EXIST", 12 },
  { "sa_ais_err_name_too_long", "SAFS_AIS_ERROR__SA_AIS_ERR_NAME_TOO_LONG", 13 },
  { "sa_ais_err_exist", "SAFS_AIS_ERROR__SA_AIS_ERR_EXIST", 14 },
  { "sa_ais_err_no_space", "SAFS_AIS_ERROR__SA_AIS_ERR_NO_SPACE", 15 },
  { "sa_ais_err_interrupt", "SAFS_AIS_ERROR__SA_AIS_ERR_INTERRUPT", 16 },
  { "sa_ais_err_name_not_found", "SAFS_AIS_ERROR__SA_AIS_ERR_NAME_NOT_FOUND", 17 },
  { "sa_ais_err_no_resources", "SAFS_AIS_ERROR__SA_AIS_ERR_NO_RESOURCES", 18 },
  { "sa_ais_err_not_supported", "SAFS_AIS_ERROR__SA_AIS_ERR_NOT_SUPPORTED", 19 },
  { "sa_ais_err_bad_operation", "SAFS_AIS_ERROR__SA_AIS_ERR_BAD_OPERATION", 20 },
  { "sa_ais_err_failed_operation", "SAFS_AIS_ERROR__SA_AIS_ERR_FAILED_OPERATION", 21 },
  { "sa_ais_err_message_error", "SAFS_AIS_ERROR__SA_AIS_ERR_MESSAGE_ERROR", 22 },
  { "sa_ais_err_queue_full", "SAFS_AIS_ERROR__SA_AIS_ERR_QUEUE_FULL", 23 },
  { "sa_ais_err_queue_not_available", "SAFS_AIS_ERROR__SA_AIS_ERR_QUEUE_NOT_AVAILABLE", 24 },
  { "sa_ais_err_bad_flags", "SAFS_AIS_ERROR__SA_AIS_ERR_BAD_FLAGS", 25 },
  { "sa_ais_err_too_big", "SAFS_AIS_ERROR__SA_AIS_ERR_TOO_BIG", 26 },
  { "sa_ais_err_no_sections", "SAFS_AIS_ERROR__SA_AIS_ERR_NO_SECTIONS", 27 },
  { "sa_ais_err_no_op", "SAFS_AIS_ERROR__SA_AIS_ERR_NO_OP", 28 },
  { "sa_ais_err_repair_pending", "SAFS_AIS_ERROR__SA_AIS_ERR_REPAIR_PENDING", 29 },
  { "sa_ais_err_no_bindings", "SAFS_AIS_ERROR__SA_AIS_ERR_NO_BINDINGS", 30 },
  { "sa_ais_err_unavailable", "SAFS_AIS_ERROR__SA_AIS_ERR_UNAVAILABLE", 31 },
  { "sa_ais_err_campaign_error_detected", "SAFS_AIS_ERROR__SA_AIS_ERR_CAMPAIGN_ERROR_DETECTED", 32 },
  { "sa_ais_err_campaign_proc_failed", "SAFS_AIS_ERROR__SA_AIS_ERR_CAMPAIGN_PROC_FAILED", 33 },
  { "sa_ais_err_campaign_canceled", "SAFS_AIS_ERROR__SA_AIS_ERR_CAMPAIGN_CANCELED", 34 },
  { "sa_ais_err_campaign_failed", "SAFS_AIS_ERROR__SA_AIS_ERR_CAMPAIGN_FAILED", 35 },
  { "sa_ais_err_campaign_suspended", "SAFS_AIS_ERROR__SA_AIS_ERR_CAMPAIGN_SUSPENDED", 36 },
  { "sa_ais_err_campaign_suspending", "SAFS_AIS_ERROR__SA_AIS_ERR_CAMPAIGN_SUSPENDING", 37 },
  { "sa_ais_err_access_denied", "SAFS_AIS_ERROR__SA_AIS_ERR_ACCESS_DENIED", 38 },
  { "sa_ais_err_not_ready", "SAFS_AIS_ERROR__SA_AIS_ERR_NOT_READY", 39 },
  { "sa_ais_err_deployment", "SAFS_AIS_ERROR__SA_AIS_ERR_DEPLOYMENT", 40 },
};
static const ProtobufCIntRange safs_ais_error__value_ranges[] = {
{1, 0},{0, 40}
};
const ProtobufCEnumValueIndex safs_ais_error__enum_values_by_name[40] =
{
  { "sa_ais_err_access", 10 },
  { "sa_ais_err_access_denied", 37 },
  { "sa_ais_err_bad_flags", 24 },
  { "sa_ais_err_bad_handle", 8 },
  { "sa_ais_err_bad_operation", 19 },
  { "sa_ais_err_busy", 9 },
  { "sa_ais_err_campaign_canceled", 33 },
  { "sa_ais_err_campaign_error_detected", 31 },
  { "sa_ais_err_campaign_failed", 34 },
  { "sa_ais_err_campaign_proc_failed", 32 },
  { "sa_ais_err_campaign_suspended", 35 },
  { "sa_ais_err_campaign_suspending", 36 },
  { "sa_ais_err_deployment", 39 },
  { "sa_ais_err_exist", 13 },
  { "sa_ais_err_failed_operation", 20 },
  { "sa_ais_err_init", 3 },
  { "sa_ais_err_interrupt", 15 },
  { "sa_ais_err_invalid_param", 6 },
  { "sa_ais_err_library", 1 },
  { "sa_ais_err_message_error", 21 },
  { "sa_ais_err_name_not_found", 16 },
  { "sa_ais_err_name_too_long", 12 },
  { "sa_ais_err_no_bindings", 29 },
  { "sa_ais_err_no_memory", 7 },
  { "sa_ais_err_no_op", 27 },
  { "sa_ais_err_no_resources", 17 },
  { "sa_ais_err_no_sections", 26 },
  { "sa_ais_err_no_space", 14 },
  { "sa_ais_err_not_exist", 11 },
  { "sa_ais_err_not_ready", 38 },
  { "sa_ais_err_not_supported", 18 },
  { "sa_ais_err_queue_full", 22 },
  { "sa_ais_err_queue_not_available", 23 },
  { "sa_ais_err_repair_pending", 28 },
  { "sa_ais_err_timeout", 4 },
  { "sa_ais_err_too_big", 25 },
  { "sa_ais_err_try_again", 5 },
  { "sa_ais_err_unavailable", 30 },
  { "sa_ais_err_version", 2 },
  { "sa_ais_ok", 0 },
};
const ProtobufCEnumDescriptor safs_ais_error__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "safsAisError",
  "safsAisError",
  "SafsAisError",
  "",
  40,
  safs_ais_error__enum_values_by_number,
  40,
  safs_ais_error__enum_values_by_name,
  1,
  safs_ais_error__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue safs_services__enum_values_by_number[15] =
{
  { "sa_svc_hpi", "SAFS_SERVICES__SA_SVC_HPI", 1 },
  { "sa_svc_amf", "SAFS_SERVICES__SA_SVC_AMF", 2 },
  { "sa_svc_clm", "SAFS_SERVICES__SA_SVC_CLM", 3 },
  { "sa_svc_ckpt", "SAFS_SERVICES__SA_SVC_CKPT", 4 },
  { "sa_svc_evt", "SAFS_SERVICES__SA_SVC_EVT", 5 },
  { "sa_svc_msg", "SAFS_SERVICES__SA_SVC_MSG", 6 },
  { "sa_svc_lck", "SAFS_SERVICES__SA_SVC_LCK", 7 },
  { "sa_svc_imms", "SAFS_SERVICES__SA_SVC_IMMS", 8 },
  { "sa_scv_log", "SAFS_SERVICES__SA_SCV_LOG", 9 },
  { "sa_svc_ntf", "SAFS_SERVICES__SA_SVC_NTF", 10 },
  { "sa_svc_nam", "SAFS_SERVICES__SA_SVC_NAM", 11 },
  { "sa_svc_tmr", "SAFS_SERVICES__SA_SVC_TMR", 12 },
  { "sa_svc_smf", "SAFS_SERVICES__SA_SVC_SMF", 13 },
  { "sa_svc_sec", "SAFS_SERVICES__SA_SVC_SEC", 14 },
  { "sa_svc_plm", "SAFS_SERVICES__SA_SVC_PLM", 15 },
};
static const ProtobufCIntRange safs_services__value_ranges[] = {
{1, 0},{0, 15}
};
const ProtobufCEnumValueIndex safs_services__enum_values_by_name[15] =
{
  { "sa_scv_log", 8 },
  { "sa_svc_amf", 1 },
  { "sa_svc_ckpt", 3 },
  { "sa_svc_clm", 2 },
  { "sa_svc_evt", 4 },
  { "sa_svc_hpi", 0 },
  { "sa_svc_imms", 7 },
  { "sa_svc_lck", 6 },
  { "sa_svc_msg", 5 },
  { "sa_svc_nam", 10 },
  { "sa_svc_ntf", 9 },
  { "sa_svc_plm", 14 },
  { "sa_svc_sec", 13 },
  { "sa_svc_smf", 12 },
  { "sa_svc_tmr", 11 },
};
const ProtobufCEnumDescriptor safs_services__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "safsServices",
  "safsServices",
  "SafsServices",
  "",
  15,
  safs_services__enum_values_by_number,
  15,
  safs_services__enum_values_by_name,
  1,
  safs_services__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
