/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_safs_5fimm_5fct_5fp_2eproto__INCLUDED
#define PROTOBUF_C_safs_5fimm_5fct_5fp_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "sa_ais.pb-c.h"
#include "om.pb-c.h"

typedef struct _SafsImmCtSchemaVersion SafsImmCtSchemaVersion;
typedef struct _SafsImmCtInstance SafsImmCtInstance;
typedef struct _SafsImmCtInstanceGroup SafsImmCtInstanceGroup;
typedef struct _SafsImmCtMessage SafsImmCtMessage;
typedef struct _SafsImmCtInitialize SafsImmCtInitialize;
typedef struct _SafsImmCtInitialize2 SafsImmCtInitialize2;
typedef struct _SafsImmCtFinalize SafsImmCtFinalize;
typedef struct _SafsImmCtReadSchemaVersion SafsImmCtReadSchemaVersion;
typedef struct _SafsImmCtFailUpgrade SafsImmCtFailUpgrade;
typedef struct _SafsImmCtReadInstances SafsImmCtReadInstances;
typedef struct _SafsImmCtReadInstances2 SafsImmCtReadInstances2;
typedef struct _SafsImmCtWriteInstances SafsImmCtWriteInstances;
typedef struct _SafsImmCtCopyInstances SafsImmCtCopyInstances;
typedef struct _SafsImmCtWaitForClasses SafsImmCtWaitForClasses;
typedef struct _SafsImmCtWriteRtInstances SafsImmCtWriteRtInstances;
typedef struct _SafsImmCtCopyRtInstances SafsImmCtCopyRtInstances;
typedef struct _SafsImmCtInitializeRet SafsImmCtInitializeRet;
typedef struct _SafsImmCtFinalizeRet SafsImmCtFinalizeRet;
typedef struct _SafsImmCtReadSchemaVersionRet SafsImmCtReadSchemaVersionRet;
typedef struct _SafsImmCtFailUpgradeRet SafsImmCtFailUpgradeRet;
typedef struct _SafsImmCtReadInstancesRet SafsImmCtReadInstancesRet;
typedef struct _SafsImmCtWriteInstancesRet SafsImmCtWriteInstancesRet;
typedef struct _SafsImmCtCopyInstancesRet SafsImmCtCopyInstancesRet;
typedef struct _SafsImmCtWaitForClassesRet SafsImmCtWaitForClassesRet;
typedef struct _SafsImmCtWriteRtInstancesRet SafsImmCtWriteRtInstancesRet;
typedef struct _SafsImmCtCopyRtInstancesRet SafsImmCtCopyRtInstancesRet;


/* --- enums --- */


/* --- messages --- */

struct  _SafsImmCtSchemaVersion
{
  ProtobufCMessage base;
  uint32_t version;
  uint32_t release;
  uint32_t correction;
};
#define SAFS_IMM_CT_SCHEMA_VERSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_schema_version__descriptor) \
    , 0, 0, 0 }


struct  _SafsImmCtInstance
{
  ProtobufCMessage base;
  char *parentname;
  size_t n_attrvalues;
  SafsImmAttrValues2 **attrvalues;
};
#define SAFS_IMM_CT_INSTANCE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_instance__descriptor) \
    , NULL, 0,NULL }


struct  _SafsImmCtInstanceGroup
{
  ProtobufCMessage base;
  char *classname;
  size_t n_instances;
  SafsImmCtInstance **instances;
};
#define SAFS_IMM_CT_INSTANCE_GROUP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_instance_group__descriptor) \
    , NULL, 0,NULL }


struct  _SafsImmCtMessage
{
  ProtobufCMessage base;
  SafsImmCtInitialize *initialize;
  SafsImmCtFinalize *finalize;
  SafsImmCtReadSchemaVersion *readschemaversion;
  SafsImmCtFailUpgrade *failupgrade;
  SafsImmCtReadInstances *readinstances;
  SafsImmCtWriteInstances *writeinstances;
  SafsImmCtCopyInstances *copyinstances;
  SafsImmCtWaitForClasses *waitforclasses;
  SafsImmCtWriteRtInstances *writertinstances;
  SafsImmCtCopyRtInstances *copyrtinstances;
  SafsImmCtReadInstances2 *readinstances_2;
  SafsImmCtInitialize2 *initialize_2;
};
#define SAFS_IMM_CT_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_message__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }


struct  _SafsImmCtInitialize
{
  ProtobufCMessage base;
  uint64_t callerpid;
};
#define SAFS_IMM_CT_INITIALIZE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_initialize__descriptor) \
    , 0 }


struct  _SafsImmCtInitialize2
{
  ProtobufCMessage base;
  uint64_t callerpid;
  protobuf_c_boolean delayedstart;
};
#define SAFS_IMM_CT_INITIALIZE_2__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_initialize_2__descriptor) \
    , 0, 0 }


struct  _SafsImmCtFinalize
{
  ProtobufCMessage base;
  uint64_t handle;
};
#define SAFS_IMM_CT_FINALIZE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_finalize__descriptor) \
    , 0 }


struct  _SafsImmCtReadSchemaVersion
{
  ProtobufCMessage base;
  uint64_t handle;
  char *schemaname;
};
#define SAFS_IMM_CT_READ_SCHEMA_VERSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_read_schema_version__descriptor) \
    , 0, NULL }


struct  _SafsImmCtFailUpgrade
{
  ProtobufCMessage base;
  uint64_t handle;
  char *message;
};
#define SAFS_IMM_CT_FAIL_UPGRADE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_fail_upgrade__descriptor) \
    , 0, NULL }


struct  _SafsImmCtReadInstances
{
  ProtobufCMessage base;
  uint64_t handle;
  size_t n_classnames;
  char **classnames;
};
#define SAFS_IMM_CT_READ_INSTANCES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_read_instances__descriptor) \
    , 0, 0,NULL }


struct  _SafsImmCtReadInstances2
{
  ProtobufCMessage base;
  uint64_t handle;
  size_t n_classnames;
  char **classnames;
};
#define SAFS_IMM_CT_READ_INSTANCES_2__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_read_instances_2__descriptor) \
    , 0, 0,NULL }


struct  _SafsImmCtWriteInstances
{
  ProtobufCMessage base;
  uint64_t handle;
  size_t n_instancegroups;
  SafsImmCtInstanceGroup **instancegroups;
};
#define SAFS_IMM_CT_WRITE_INSTANCES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_write_instances__descriptor) \
    , 0, 0,NULL }


struct  _SafsImmCtCopyInstances
{
  ProtobufCMessage base;
  uint64_t handle;
  size_t n_classnames;
  char **classnames;
};
#define SAFS_IMM_CT_COPY_INSTANCES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_copy_instances__descriptor) \
    , 0, 0,NULL }


struct  _SafsImmCtWaitForClasses
{
  ProtobufCMessage base;
  uint64_t handle;
  size_t n_classnames;
  char **classnames;
};
#define SAFS_IMM_CT_WAIT_FOR_CLASSES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_wait_for_classes__descriptor) \
    , 0, 0,NULL }


struct  _SafsImmCtWriteRtInstances
{
  ProtobufCMessage base;
  uint64_t handle;
  char *implementername;
  size_t n_instancegroups;
  SafsImmCtInstanceGroup **instancegroups;
};
#define SAFS_IMM_CT_WRITE_RT_INSTANCES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_write_rt_instances__descriptor) \
    , 0, NULL, 0,NULL }


struct  _SafsImmCtCopyRtInstances
{
  ProtobufCMessage base;
  uint64_t handle;
  char *implementername;
  size_t n_classnames;
  char **classnames;
};
#define SAFS_IMM_CT_COPY_RT_INSTANCES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_copy_rt_instances__descriptor) \
    , 0, NULL, 0,NULL }


struct  _SafsImmCtInitializeRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
  protobuf_c_boolean has_handle;
  uint64_t handle;
};
#define SAFS_IMM_CT_INITIALIZE_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_initialize_ret__descriptor) \
    , 0, 0,0 }


struct  _SafsImmCtFinalizeRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
};
#define SAFS_IMM_CT_FINALIZE_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_finalize_ret__descriptor) \
    , 0 }


struct  _SafsImmCtReadSchemaVersionRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
  SafsImmCtSchemaVersion *oldversion;
  SafsImmCtSchemaVersion *newversion;
};
#define SAFS_IMM_CT_READ_SCHEMA_VERSION_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_read_schema_version_ret__descriptor) \
    , 0, NULL, NULL }


struct  _SafsImmCtFailUpgradeRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
};
#define SAFS_IMM_CT_FAIL_UPGRADE_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_fail_upgrade_ret__descriptor) \
    , 0 }


struct  _SafsImmCtReadInstancesRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
  size_t n_instancegroups;
  SafsImmCtInstanceGroup **instancegroups;
};
#define SAFS_IMM_CT_READ_INSTANCES_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_read_instances_ret__descriptor) \
    , 0, 0,NULL }


struct  _SafsImmCtWriteInstancesRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
};
#define SAFS_IMM_CT_WRITE_INSTANCES_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_write_instances_ret__descriptor) \
    , 0 }


struct  _SafsImmCtCopyInstancesRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
};
#define SAFS_IMM_CT_COPY_INSTANCES_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_copy_instances_ret__descriptor) \
    , 0 }


struct  _SafsImmCtWaitForClassesRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
};
#define SAFS_IMM_CT_WAIT_FOR_CLASSES_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_wait_for_classes_ret__descriptor) \
    , 0 }


struct  _SafsImmCtWriteRtInstancesRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
};
#define SAFS_IMM_CT_WRITE_RT_INSTANCES_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_write_rt_instances_ret__descriptor) \
    , 0 }


struct  _SafsImmCtCopyRtInstancesRet
{
  ProtobufCMessage base;
  SafsAisError returnval;
};
#define SAFS_IMM_CT_COPY_RT_INSTANCES_RET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&safs_imm_ct_copy_rt_instances_ret__descriptor) \
    , 0 }


/* SafsImmCtSchemaVersion methods */
void   safs_imm_ct_schema_version__init
                     (SafsImmCtSchemaVersion         *message);
size_t safs_imm_ct_schema_version__get_packed_size
                     (const SafsImmCtSchemaVersion   *message);
size_t safs_imm_ct_schema_version__pack
                     (const SafsImmCtSchemaVersion   *message,
                      uint8_t             *out);
size_t safs_imm_ct_schema_version__pack_to_buffer
                     (const SafsImmCtSchemaVersion   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtSchemaVersion *
       safs_imm_ct_schema_version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_schema_version__free_unpacked
                     (SafsImmCtSchemaVersion *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtInstance methods */
void   safs_imm_ct_instance__init
                     (SafsImmCtInstance         *message);
size_t safs_imm_ct_instance__get_packed_size
                     (const SafsImmCtInstance   *message);
size_t safs_imm_ct_instance__pack
                     (const SafsImmCtInstance   *message,
                      uint8_t             *out);
size_t safs_imm_ct_instance__pack_to_buffer
                     (const SafsImmCtInstance   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtInstance *
       safs_imm_ct_instance__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_instance__free_unpacked
                     (SafsImmCtInstance *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtInstanceGroup methods */
void   safs_imm_ct_instance_group__init
                     (SafsImmCtInstanceGroup         *message);
size_t safs_imm_ct_instance_group__get_packed_size
                     (const SafsImmCtInstanceGroup   *message);
size_t safs_imm_ct_instance_group__pack
                     (const SafsImmCtInstanceGroup   *message,
                      uint8_t             *out);
size_t safs_imm_ct_instance_group__pack_to_buffer
                     (const SafsImmCtInstanceGroup   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtInstanceGroup *
       safs_imm_ct_instance_group__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_instance_group__free_unpacked
                     (SafsImmCtInstanceGroup *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtMessage methods */
void   safs_imm_ct_message__init
                     (SafsImmCtMessage         *message);
size_t safs_imm_ct_message__get_packed_size
                     (const SafsImmCtMessage   *message);
size_t safs_imm_ct_message__pack
                     (const SafsImmCtMessage   *message,
                      uint8_t             *out);
size_t safs_imm_ct_message__pack_to_buffer
                     (const SafsImmCtMessage   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtMessage *
       safs_imm_ct_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_message__free_unpacked
                     (SafsImmCtMessage *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtInitialize methods */
void   safs_imm_ct_initialize__init
                     (SafsImmCtInitialize         *message);
size_t safs_imm_ct_initialize__get_packed_size
                     (const SafsImmCtInitialize   *message);
size_t safs_imm_ct_initialize__pack
                     (const SafsImmCtInitialize   *message,
                      uint8_t             *out);
size_t safs_imm_ct_initialize__pack_to_buffer
                     (const SafsImmCtInitialize   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtInitialize *
       safs_imm_ct_initialize__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_initialize__free_unpacked
                     (SafsImmCtInitialize *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtInitialize2 methods */
void   safs_imm_ct_initialize_2__init
                     (SafsImmCtInitialize2         *message);
size_t safs_imm_ct_initialize_2__get_packed_size
                     (const SafsImmCtInitialize2   *message);
size_t safs_imm_ct_initialize_2__pack
                     (const SafsImmCtInitialize2   *message,
                      uint8_t             *out);
size_t safs_imm_ct_initialize_2__pack_to_buffer
                     (const SafsImmCtInitialize2   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtInitialize2 *
       safs_imm_ct_initialize_2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_initialize_2__free_unpacked
                     (SafsImmCtInitialize2 *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtFinalize methods */
void   safs_imm_ct_finalize__init
                     (SafsImmCtFinalize         *message);
size_t safs_imm_ct_finalize__get_packed_size
                     (const SafsImmCtFinalize   *message);
size_t safs_imm_ct_finalize__pack
                     (const SafsImmCtFinalize   *message,
                      uint8_t             *out);
size_t safs_imm_ct_finalize__pack_to_buffer
                     (const SafsImmCtFinalize   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtFinalize *
       safs_imm_ct_finalize__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_finalize__free_unpacked
                     (SafsImmCtFinalize *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtReadSchemaVersion methods */
void   safs_imm_ct_read_schema_version__init
                     (SafsImmCtReadSchemaVersion         *message);
size_t safs_imm_ct_read_schema_version__get_packed_size
                     (const SafsImmCtReadSchemaVersion   *message);
size_t safs_imm_ct_read_schema_version__pack
                     (const SafsImmCtReadSchemaVersion   *message,
                      uint8_t             *out);
size_t safs_imm_ct_read_schema_version__pack_to_buffer
                     (const SafsImmCtReadSchemaVersion   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtReadSchemaVersion *
       safs_imm_ct_read_schema_version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_read_schema_version__free_unpacked
                     (SafsImmCtReadSchemaVersion *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtFailUpgrade methods */
void   safs_imm_ct_fail_upgrade__init
                     (SafsImmCtFailUpgrade         *message);
size_t safs_imm_ct_fail_upgrade__get_packed_size
                     (const SafsImmCtFailUpgrade   *message);
size_t safs_imm_ct_fail_upgrade__pack
                     (const SafsImmCtFailUpgrade   *message,
                      uint8_t             *out);
size_t safs_imm_ct_fail_upgrade__pack_to_buffer
                     (const SafsImmCtFailUpgrade   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtFailUpgrade *
       safs_imm_ct_fail_upgrade__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_fail_upgrade__free_unpacked
                     (SafsImmCtFailUpgrade *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtReadInstances methods */
void   safs_imm_ct_read_instances__init
                     (SafsImmCtReadInstances         *message);
size_t safs_imm_ct_read_instances__get_packed_size
                     (const SafsImmCtReadInstances   *message);
size_t safs_imm_ct_read_instances__pack
                     (const SafsImmCtReadInstances   *message,
                      uint8_t             *out);
size_t safs_imm_ct_read_instances__pack_to_buffer
                     (const SafsImmCtReadInstances   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtReadInstances *
       safs_imm_ct_read_instances__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_read_instances__free_unpacked
                     (SafsImmCtReadInstances *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtReadInstances2 methods */
void   safs_imm_ct_read_instances_2__init
                     (SafsImmCtReadInstances2         *message);
size_t safs_imm_ct_read_instances_2__get_packed_size
                     (const SafsImmCtReadInstances2   *message);
size_t safs_imm_ct_read_instances_2__pack
                     (const SafsImmCtReadInstances2   *message,
                      uint8_t             *out);
size_t safs_imm_ct_read_instances_2__pack_to_buffer
                     (const SafsImmCtReadInstances2   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtReadInstances2 *
       safs_imm_ct_read_instances_2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_read_instances_2__free_unpacked
                     (SafsImmCtReadInstances2 *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtWriteInstances methods */
void   safs_imm_ct_write_instances__init
                     (SafsImmCtWriteInstances         *message);
size_t safs_imm_ct_write_instances__get_packed_size
                     (const SafsImmCtWriteInstances   *message);
size_t safs_imm_ct_write_instances__pack
                     (const SafsImmCtWriteInstances   *message,
                      uint8_t             *out);
size_t safs_imm_ct_write_instances__pack_to_buffer
                     (const SafsImmCtWriteInstances   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtWriteInstances *
       safs_imm_ct_write_instances__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_write_instances__free_unpacked
                     (SafsImmCtWriteInstances *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtCopyInstances methods */
void   safs_imm_ct_copy_instances__init
                     (SafsImmCtCopyInstances         *message);
size_t safs_imm_ct_copy_instances__get_packed_size
                     (const SafsImmCtCopyInstances   *message);
size_t safs_imm_ct_copy_instances__pack
                     (const SafsImmCtCopyInstances   *message,
                      uint8_t             *out);
size_t safs_imm_ct_copy_instances__pack_to_buffer
                     (const SafsImmCtCopyInstances   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtCopyInstances *
       safs_imm_ct_copy_instances__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_copy_instances__free_unpacked
                     (SafsImmCtCopyInstances *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtWaitForClasses methods */
void   safs_imm_ct_wait_for_classes__init
                     (SafsImmCtWaitForClasses         *message);
size_t safs_imm_ct_wait_for_classes__get_packed_size
                     (const SafsImmCtWaitForClasses   *message);
size_t safs_imm_ct_wait_for_classes__pack
                     (const SafsImmCtWaitForClasses   *message,
                      uint8_t             *out);
size_t safs_imm_ct_wait_for_classes__pack_to_buffer
                     (const SafsImmCtWaitForClasses   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtWaitForClasses *
       safs_imm_ct_wait_for_classes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_wait_for_classes__free_unpacked
                     (SafsImmCtWaitForClasses *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtWriteRtInstances methods */
void   safs_imm_ct_write_rt_instances__init
                     (SafsImmCtWriteRtInstances         *message);
size_t safs_imm_ct_write_rt_instances__get_packed_size
                     (const SafsImmCtWriteRtInstances   *message);
size_t safs_imm_ct_write_rt_instances__pack
                     (const SafsImmCtWriteRtInstances   *message,
                      uint8_t             *out);
size_t safs_imm_ct_write_rt_instances__pack_to_buffer
                     (const SafsImmCtWriteRtInstances   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtWriteRtInstances *
       safs_imm_ct_write_rt_instances__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_write_rt_instances__free_unpacked
                     (SafsImmCtWriteRtInstances *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtCopyRtInstances methods */
void   safs_imm_ct_copy_rt_instances__init
                     (SafsImmCtCopyRtInstances         *message);
size_t safs_imm_ct_copy_rt_instances__get_packed_size
                     (const SafsImmCtCopyRtInstances   *message);
size_t safs_imm_ct_copy_rt_instances__pack
                     (const SafsImmCtCopyRtInstances   *message,
                      uint8_t             *out);
size_t safs_imm_ct_copy_rt_instances__pack_to_buffer
                     (const SafsImmCtCopyRtInstances   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtCopyRtInstances *
       safs_imm_ct_copy_rt_instances__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_copy_rt_instances__free_unpacked
                     (SafsImmCtCopyRtInstances *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtInitializeRet methods */
void   safs_imm_ct_initialize_ret__init
                     (SafsImmCtInitializeRet         *message);
size_t safs_imm_ct_initialize_ret__get_packed_size
                     (const SafsImmCtInitializeRet   *message);
size_t safs_imm_ct_initialize_ret__pack
                     (const SafsImmCtInitializeRet   *message,
                      uint8_t             *out);
size_t safs_imm_ct_initialize_ret__pack_to_buffer
                     (const SafsImmCtInitializeRet   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtInitializeRet *
       safs_imm_ct_initialize_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_initialize_ret__free_unpacked
                     (SafsImmCtInitializeRet *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtFinalizeRet methods */
void   safs_imm_ct_finalize_ret__init
                     (SafsImmCtFinalizeRet         *message);
size_t safs_imm_ct_finalize_ret__get_packed_size
                     (const SafsImmCtFinalizeRet   *message);
size_t safs_imm_ct_finalize_ret__pack
                     (const SafsImmCtFinalizeRet   *message,
                      uint8_t             *out);
size_t safs_imm_ct_finalize_ret__pack_to_buffer
                     (const SafsImmCtFinalizeRet   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtFinalizeRet *
       safs_imm_ct_finalize_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_finalize_ret__free_unpacked
                     (SafsImmCtFinalizeRet *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtReadSchemaVersionRet methods */
void   safs_imm_ct_read_schema_version_ret__init
                     (SafsImmCtReadSchemaVersionRet         *message);
size_t safs_imm_ct_read_schema_version_ret__get_packed_size
                     (const SafsImmCtReadSchemaVersionRet   *message);
size_t safs_imm_ct_read_schema_version_ret__pack
                     (const SafsImmCtReadSchemaVersionRet   *message,
                      uint8_t             *out);
size_t safs_imm_ct_read_schema_version_ret__pack_to_buffer
                     (const SafsImmCtReadSchemaVersionRet   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtReadSchemaVersionRet *
       safs_imm_ct_read_schema_version_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_read_schema_version_ret__free_unpacked
                     (SafsImmCtReadSchemaVersionRet *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtFailUpgradeRet methods */
void   safs_imm_ct_fail_upgrade_ret__init
                     (SafsImmCtFailUpgradeRet         *message);
size_t safs_imm_ct_fail_upgrade_ret__get_packed_size
                     (const SafsImmCtFailUpgradeRet   *message);
size_t safs_imm_ct_fail_upgrade_ret__pack
                     (const SafsImmCtFailUpgradeRet   *message,
                      uint8_t             *out);
size_t safs_imm_ct_fail_upgrade_ret__pack_to_buffer
                     (const SafsImmCtFailUpgradeRet   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtFailUpgradeRet *
       safs_imm_ct_fail_upgrade_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_fail_upgrade_ret__free_unpacked
                     (SafsImmCtFailUpgradeRet *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtReadInstancesRet methods */
void   safs_imm_ct_read_instances_ret__init
                     (SafsImmCtReadInstancesRet         *message);
size_t safs_imm_ct_read_instances_ret__get_packed_size
                     (const SafsImmCtReadInstancesRet   *message);
size_t safs_imm_ct_read_instances_ret__pack
                     (const SafsImmCtReadInstancesRet   *message,
                      uint8_t             *out);
size_t safs_imm_ct_read_instances_ret__pack_to_buffer
                     (const SafsImmCtReadInstancesRet   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtReadInstancesRet *
       safs_imm_ct_read_instances_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_read_instances_ret__free_unpacked
                     (SafsImmCtReadInstancesRet *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtWriteInstancesRet methods */
void   safs_imm_ct_write_instances_ret__init
                     (SafsImmCtWriteInstancesRet         *message);
size_t safs_imm_ct_write_instances_ret__get_packed_size
                     (const SafsImmCtWriteInstancesRet   *message);
size_t safs_imm_ct_write_instances_ret__pack
                     (const SafsImmCtWriteInstancesRet   *message,
                      uint8_t             *out);
size_t safs_imm_ct_write_instances_ret__pack_to_buffer
                     (const SafsImmCtWriteInstancesRet   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtWriteInstancesRet *
       safs_imm_ct_write_instances_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_write_instances_ret__free_unpacked
                     (SafsImmCtWriteInstancesRet *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtCopyInstancesRet methods */
void   safs_imm_ct_copy_instances_ret__init
                     (SafsImmCtCopyInstancesRet         *message);
size_t safs_imm_ct_copy_instances_ret__get_packed_size
                     (const SafsImmCtCopyInstancesRet   *message);
size_t safs_imm_ct_copy_instances_ret__pack
                     (const SafsImmCtCopyInstancesRet   *message,
                      uint8_t             *out);
size_t safs_imm_ct_copy_instances_ret__pack_to_buffer
                     (const SafsImmCtCopyInstancesRet   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtCopyInstancesRet *
       safs_imm_ct_copy_instances_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_copy_instances_ret__free_unpacked
                     (SafsImmCtCopyInstancesRet *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtWaitForClassesRet methods */
void   safs_imm_ct_wait_for_classes_ret__init
                     (SafsImmCtWaitForClassesRet         *message);
size_t safs_imm_ct_wait_for_classes_ret__get_packed_size
                     (const SafsImmCtWaitForClassesRet   *message);
size_t safs_imm_ct_wait_for_classes_ret__pack
                     (const SafsImmCtWaitForClassesRet   *message,
                      uint8_t             *out);
size_t safs_imm_ct_wait_for_classes_ret__pack_to_buffer
                     (const SafsImmCtWaitForClassesRet   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtWaitForClassesRet *
       safs_imm_ct_wait_for_classes_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_wait_for_classes_ret__free_unpacked
                     (SafsImmCtWaitForClassesRet *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtWriteRtInstancesRet methods */
void   safs_imm_ct_write_rt_instances_ret__init
                     (SafsImmCtWriteRtInstancesRet         *message);
size_t safs_imm_ct_write_rt_instances_ret__get_packed_size
                     (const SafsImmCtWriteRtInstancesRet   *message);
size_t safs_imm_ct_write_rt_instances_ret__pack
                     (const SafsImmCtWriteRtInstancesRet   *message,
                      uint8_t             *out);
size_t safs_imm_ct_write_rt_instances_ret__pack_to_buffer
                     (const SafsImmCtWriteRtInstancesRet   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtWriteRtInstancesRet *
       safs_imm_ct_write_rt_instances_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_write_rt_instances_ret__free_unpacked
                     (SafsImmCtWriteRtInstancesRet *message,
                      ProtobufCAllocator *allocator);
/* SafsImmCtCopyRtInstancesRet methods */
void   safs_imm_ct_copy_rt_instances_ret__init
                     (SafsImmCtCopyRtInstancesRet         *message);
size_t safs_imm_ct_copy_rt_instances_ret__get_packed_size
                     (const SafsImmCtCopyRtInstancesRet   *message);
size_t safs_imm_ct_copy_rt_instances_ret__pack
                     (const SafsImmCtCopyRtInstancesRet   *message,
                      uint8_t             *out);
size_t safs_imm_ct_copy_rt_instances_ret__pack_to_buffer
                     (const SafsImmCtCopyRtInstancesRet   *message,
                      ProtobufCBuffer     *buffer);
SafsImmCtCopyRtInstancesRet *
       safs_imm_ct_copy_rt_instances_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   safs_imm_ct_copy_rt_instances_ret__free_unpacked
                     (SafsImmCtCopyRtInstancesRet *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SafsImmCtSchemaVersion_Closure)
                 (const SafsImmCtSchemaVersion *message,
                  void *closure_data);
typedef void (*SafsImmCtInstance_Closure)
                 (const SafsImmCtInstance *message,
                  void *closure_data);
typedef void (*SafsImmCtInstanceGroup_Closure)
                 (const SafsImmCtInstanceGroup *message,
                  void *closure_data);
typedef void (*SafsImmCtMessage_Closure)
                 (const SafsImmCtMessage *message,
                  void *closure_data);
typedef void (*SafsImmCtInitialize_Closure)
                 (const SafsImmCtInitialize *message,
                  void *closure_data);
typedef void (*SafsImmCtInitialize2_Closure)
                 (const SafsImmCtInitialize2 *message,
                  void *closure_data);
typedef void (*SafsImmCtFinalize_Closure)
                 (const SafsImmCtFinalize *message,
                  void *closure_data);
typedef void (*SafsImmCtReadSchemaVersion_Closure)
                 (const SafsImmCtReadSchemaVersion *message,
                  void *closure_data);
typedef void (*SafsImmCtFailUpgrade_Closure)
                 (const SafsImmCtFailUpgrade *message,
                  void *closure_data);
typedef void (*SafsImmCtReadInstances_Closure)
                 (const SafsImmCtReadInstances *message,
                  void *closure_data);
typedef void (*SafsImmCtReadInstances2_Closure)
                 (const SafsImmCtReadInstances2 *message,
                  void *closure_data);
typedef void (*SafsImmCtWriteInstances_Closure)
                 (const SafsImmCtWriteInstances *message,
                  void *closure_data);
typedef void (*SafsImmCtCopyInstances_Closure)
                 (const SafsImmCtCopyInstances *message,
                  void *closure_data);
typedef void (*SafsImmCtWaitForClasses_Closure)
                 (const SafsImmCtWaitForClasses *message,
                  void *closure_data);
typedef void (*SafsImmCtWriteRtInstances_Closure)
                 (const SafsImmCtWriteRtInstances *message,
                  void *closure_data);
typedef void (*SafsImmCtCopyRtInstances_Closure)
                 (const SafsImmCtCopyRtInstances *message,
                  void *closure_data);
typedef void (*SafsImmCtInitializeRet_Closure)
                 (const SafsImmCtInitializeRet *message,
                  void *closure_data);
typedef void (*SafsImmCtFinalizeRet_Closure)
                 (const SafsImmCtFinalizeRet *message,
                  void *closure_data);
typedef void (*SafsImmCtReadSchemaVersionRet_Closure)
                 (const SafsImmCtReadSchemaVersionRet *message,
                  void *closure_data);
typedef void (*SafsImmCtFailUpgradeRet_Closure)
                 (const SafsImmCtFailUpgradeRet *message,
                  void *closure_data);
typedef void (*SafsImmCtReadInstancesRet_Closure)
                 (const SafsImmCtReadInstancesRet *message,
                  void *closure_data);
typedef void (*SafsImmCtWriteInstancesRet_Closure)
                 (const SafsImmCtWriteInstancesRet *message,
                  void *closure_data);
typedef void (*SafsImmCtCopyInstancesRet_Closure)
                 (const SafsImmCtCopyInstancesRet *message,
                  void *closure_data);
typedef void (*SafsImmCtWaitForClassesRet_Closure)
                 (const SafsImmCtWaitForClassesRet *message,
                  void *closure_data);
typedef void (*SafsImmCtWriteRtInstancesRet_Closure)
                 (const SafsImmCtWriteRtInstancesRet *message,
                  void *closure_data);
typedef void (*SafsImmCtCopyRtInstancesRet_Closure)
                 (const SafsImmCtCopyRtInstancesRet *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor safs_imm_ct_schema_version__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_instance__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_instance_group__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_message__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_initialize__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_initialize_2__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_finalize__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_read_schema_version__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_fail_upgrade__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_read_instances__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_read_instances_2__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_write_instances__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_copy_instances__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_wait_for_classes__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_write_rt_instances__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_copy_rt_instances__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_initialize_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_finalize_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_read_schema_version_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_fail_upgrade_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_read_instances_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_write_instances_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_copy_instances_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_wait_for_classes_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_write_rt_instances_ret__descriptor;
extern const ProtobufCMessageDescriptor safs_imm_ct_copy_rt_instances_ret__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_safs_5fimm_5fct_5fp_2eproto__INCLUDED */
