/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "safs_imm_ct_p.pb-c.h"
void   safs_imm_ct_schema_version__init
                     (SafsImmCtSchemaVersion         *message)
{
  static SafsImmCtSchemaVersion init_value = SAFS_IMM_CT_SCHEMA_VERSION__INIT;
  *message = init_value;
}
size_t safs_imm_ct_schema_version__get_packed_size
                     (const SafsImmCtSchemaVersion *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_schema_version__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_schema_version__pack
                     (const SafsImmCtSchemaVersion *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_schema_version__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_schema_version__pack_to_buffer
                     (const SafsImmCtSchemaVersion *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_schema_version__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtSchemaVersion *
       safs_imm_ct_schema_version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtSchemaVersion *)
     protobuf_c_message_unpack (&safs_imm_ct_schema_version__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_schema_version__free_unpacked
                     (SafsImmCtSchemaVersion *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_schema_version__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_instance__init
                     (SafsImmCtInstance         *message)
{
  static SafsImmCtInstance init_value = SAFS_IMM_CT_INSTANCE__INIT;
  *message = init_value;
}
size_t safs_imm_ct_instance__get_packed_size
                     (const SafsImmCtInstance *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_instance__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_instance__pack
                     (const SafsImmCtInstance *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_instance__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_instance__pack_to_buffer
                     (const SafsImmCtInstance *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_instance__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtInstance *
       safs_imm_ct_instance__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtInstance *)
     protobuf_c_message_unpack (&safs_imm_ct_instance__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_instance__free_unpacked
                     (SafsImmCtInstance *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_instance__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_instance_group__init
                     (SafsImmCtInstanceGroup         *message)
{
  static SafsImmCtInstanceGroup init_value = SAFS_IMM_CT_INSTANCE_GROUP__INIT;
  *message = init_value;
}
size_t safs_imm_ct_instance_group__get_packed_size
                     (const SafsImmCtInstanceGroup *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_instance_group__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_instance_group__pack
                     (const SafsImmCtInstanceGroup *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_instance_group__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_instance_group__pack_to_buffer
                     (const SafsImmCtInstanceGroup *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_instance_group__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtInstanceGroup *
       safs_imm_ct_instance_group__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtInstanceGroup *)
     protobuf_c_message_unpack (&safs_imm_ct_instance_group__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_instance_group__free_unpacked
                     (SafsImmCtInstanceGroup *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_instance_group__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_message__init
                     (SafsImmCtMessage         *message)
{
  static SafsImmCtMessage init_value = SAFS_IMM_CT_MESSAGE__INIT;
  *message = init_value;
}
size_t safs_imm_ct_message__get_packed_size
                     (const SafsImmCtMessage *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_message__pack
                     (const SafsImmCtMessage *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_message__pack_to_buffer
                     (const SafsImmCtMessage *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtMessage *
       safs_imm_ct_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtMessage *)
     protobuf_c_message_unpack (&safs_imm_ct_message__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_message__free_unpacked
                     (SafsImmCtMessage *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_initialize__init
                     (SafsImmCtInitialize         *message)
{
  static SafsImmCtInitialize init_value = SAFS_IMM_CT_INITIALIZE__INIT;
  *message = init_value;
}
size_t safs_imm_ct_initialize__get_packed_size
                     (const SafsImmCtInitialize *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_initialize__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_initialize__pack
                     (const SafsImmCtInitialize *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_initialize__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_initialize__pack_to_buffer
                     (const SafsImmCtInitialize *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_initialize__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtInitialize *
       safs_imm_ct_initialize__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtInitialize *)
     protobuf_c_message_unpack (&safs_imm_ct_initialize__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_initialize__free_unpacked
                     (SafsImmCtInitialize *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_initialize__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_initialize_2__init
                     (SafsImmCtInitialize2         *message)
{
  static SafsImmCtInitialize2 init_value = SAFS_IMM_CT_INITIALIZE_2__INIT;
  *message = init_value;
}
size_t safs_imm_ct_initialize_2__get_packed_size
                     (const SafsImmCtInitialize2 *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_initialize_2__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_initialize_2__pack
                     (const SafsImmCtInitialize2 *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_initialize_2__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_initialize_2__pack_to_buffer
                     (const SafsImmCtInitialize2 *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_initialize_2__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtInitialize2 *
       safs_imm_ct_initialize_2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtInitialize2 *)
     protobuf_c_message_unpack (&safs_imm_ct_initialize_2__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_initialize_2__free_unpacked
                     (SafsImmCtInitialize2 *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_initialize_2__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_finalize__init
                     (SafsImmCtFinalize         *message)
{
  static SafsImmCtFinalize init_value = SAFS_IMM_CT_FINALIZE__INIT;
  *message = init_value;
}
size_t safs_imm_ct_finalize__get_packed_size
                     (const SafsImmCtFinalize *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_finalize__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_finalize__pack
                     (const SafsImmCtFinalize *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_finalize__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_finalize__pack_to_buffer
                     (const SafsImmCtFinalize *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_finalize__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtFinalize *
       safs_imm_ct_finalize__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtFinalize *)
     protobuf_c_message_unpack (&safs_imm_ct_finalize__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_finalize__free_unpacked
                     (SafsImmCtFinalize *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_finalize__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_read_schema_version__init
                     (SafsImmCtReadSchemaVersion         *message)
{
  static SafsImmCtReadSchemaVersion init_value = SAFS_IMM_CT_READ_SCHEMA_VERSION__INIT;
  *message = init_value;
}
size_t safs_imm_ct_read_schema_version__get_packed_size
                     (const SafsImmCtReadSchemaVersion *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_schema_version__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_read_schema_version__pack
                     (const SafsImmCtReadSchemaVersion *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_schema_version__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_read_schema_version__pack_to_buffer
                     (const SafsImmCtReadSchemaVersion *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_schema_version__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtReadSchemaVersion *
       safs_imm_ct_read_schema_version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtReadSchemaVersion *)
     protobuf_c_message_unpack (&safs_imm_ct_read_schema_version__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_read_schema_version__free_unpacked
                     (SafsImmCtReadSchemaVersion *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_schema_version__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_fail_upgrade__init
                     (SafsImmCtFailUpgrade         *message)
{
  static SafsImmCtFailUpgrade init_value = SAFS_IMM_CT_FAIL_UPGRADE__INIT;
  *message = init_value;
}
size_t safs_imm_ct_fail_upgrade__get_packed_size
                     (const SafsImmCtFailUpgrade *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_fail_upgrade__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_fail_upgrade__pack
                     (const SafsImmCtFailUpgrade *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_fail_upgrade__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_fail_upgrade__pack_to_buffer
                     (const SafsImmCtFailUpgrade *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_fail_upgrade__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtFailUpgrade *
       safs_imm_ct_fail_upgrade__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtFailUpgrade *)
     protobuf_c_message_unpack (&safs_imm_ct_fail_upgrade__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_fail_upgrade__free_unpacked
                     (SafsImmCtFailUpgrade *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_fail_upgrade__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_read_instances__init
                     (SafsImmCtReadInstances         *message)
{
  static SafsImmCtReadInstances init_value = SAFS_IMM_CT_READ_INSTANCES__INIT;
  *message = init_value;
}
size_t safs_imm_ct_read_instances__get_packed_size
                     (const SafsImmCtReadInstances *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_instances__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_read_instances__pack
                     (const SafsImmCtReadInstances *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_instances__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_read_instances__pack_to_buffer
                     (const SafsImmCtReadInstances *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_instances__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtReadInstances *
       safs_imm_ct_read_instances__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtReadInstances *)
     protobuf_c_message_unpack (&safs_imm_ct_read_instances__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_read_instances__free_unpacked
                     (SafsImmCtReadInstances *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_instances__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_read_instances_2__init
                     (SafsImmCtReadInstances2         *message)
{
  static SafsImmCtReadInstances2 init_value = SAFS_IMM_CT_READ_INSTANCES_2__INIT;
  *message = init_value;
}
size_t safs_imm_ct_read_instances_2__get_packed_size
                     (const SafsImmCtReadInstances2 *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_instances_2__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_read_instances_2__pack
                     (const SafsImmCtReadInstances2 *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_instances_2__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_read_instances_2__pack_to_buffer
                     (const SafsImmCtReadInstances2 *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_instances_2__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtReadInstances2 *
       safs_imm_ct_read_instances_2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtReadInstances2 *)
     protobuf_c_message_unpack (&safs_imm_ct_read_instances_2__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_read_instances_2__free_unpacked
                     (SafsImmCtReadInstances2 *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_instances_2__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_write_instances__init
                     (SafsImmCtWriteInstances         *message)
{
  static SafsImmCtWriteInstances init_value = SAFS_IMM_CT_WRITE_INSTANCES__INIT;
  *message = init_value;
}
size_t safs_imm_ct_write_instances__get_packed_size
                     (const SafsImmCtWriteInstances *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_write_instances__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_write_instances__pack
                     (const SafsImmCtWriteInstances *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_write_instances__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_write_instances__pack_to_buffer
                     (const SafsImmCtWriteInstances *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_write_instances__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtWriteInstances *
       safs_imm_ct_write_instances__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtWriteInstances *)
     protobuf_c_message_unpack (&safs_imm_ct_write_instances__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_write_instances__free_unpacked
                     (SafsImmCtWriteInstances *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_write_instances__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_copy_instances__init
                     (SafsImmCtCopyInstances         *message)
{
  static SafsImmCtCopyInstances init_value = SAFS_IMM_CT_COPY_INSTANCES__INIT;
  *message = init_value;
}
size_t safs_imm_ct_copy_instances__get_packed_size
                     (const SafsImmCtCopyInstances *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_copy_instances__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_copy_instances__pack
                     (const SafsImmCtCopyInstances *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_copy_instances__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_copy_instances__pack_to_buffer
                     (const SafsImmCtCopyInstances *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_copy_instances__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtCopyInstances *
       safs_imm_ct_copy_instances__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtCopyInstances *)
     protobuf_c_message_unpack (&safs_imm_ct_copy_instances__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_copy_instances__free_unpacked
                     (SafsImmCtCopyInstances *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_copy_instances__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_wait_for_classes__init
                     (SafsImmCtWaitForClasses         *message)
{
  static SafsImmCtWaitForClasses init_value = SAFS_IMM_CT_WAIT_FOR_CLASSES__INIT;
  *message = init_value;
}
size_t safs_imm_ct_wait_for_classes__get_packed_size
                     (const SafsImmCtWaitForClasses *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_wait_for_classes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_wait_for_classes__pack
                     (const SafsImmCtWaitForClasses *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_wait_for_classes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_wait_for_classes__pack_to_buffer
                     (const SafsImmCtWaitForClasses *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_wait_for_classes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtWaitForClasses *
       safs_imm_ct_wait_for_classes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtWaitForClasses *)
     protobuf_c_message_unpack (&safs_imm_ct_wait_for_classes__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_wait_for_classes__free_unpacked
                     (SafsImmCtWaitForClasses *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_wait_for_classes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_write_rt_instances__init
                     (SafsImmCtWriteRtInstances         *message)
{
  static SafsImmCtWriteRtInstances init_value = SAFS_IMM_CT_WRITE_RT_INSTANCES__INIT;
  *message = init_value;
}
size_t safs_imm_ct_write_rt_instances__get_packed_size
                     (const SafsImmCtWriteRtInstances *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_write_rt_instances__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_write_rt_instances__pack
                     (const SafsImmCtWriteRtInstances *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_write_rt_instances__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_write_rt_instances__pack_to_buffer
                     (const SafsImmCtWriteRtInstances *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_write_rt_instances__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtWriteRtInstances *
       safs_imm_ct_write_rt_instances__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtWriteRtInstances *)
     protobuf_c_message_unpack (&safs_imm_ct_write_rt_instances__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_write_rt_instances__free_unpacked
                     (SafsImmCtWriteRtInstances *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_write_rt_instances__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_copy_rt_instances__init
                     (SafsImmCtCopyRtInstances         *message)
{
  static SafsImmCtCopyRtInstances init_value = SAFS_IMM_CT_COPY_RT_INSTANCES__INIT;
  *message = init_value;
}
size_t safs_imm_ct_copy_rt_instances__get_packed_size
                     (const SafsImmCtCopyRtInstances *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_copy_rt_instances__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_copy_rt_instances__pack
                     (const SafsImmCtCopyRtInstances *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_copy_rt_instances__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_copy_rt_instances__pack_to_buffer
                     (const SafsImmCtCopyRtInstances *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_copy_rt_instances__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtCopyRtInstances *
       safs_imm_ct_copy_rt_instances__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtCopyRtInstances *)
     protobuf_c_message_unpack (&safs_imm_ct_copy_rt_instances__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_copy_rt_instances__free_unpacked
                     (SafsImmCtCopyRtInstances *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_copy_rt_instances__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_initialize_ret__init
                     (SafsImmCtInitializeRet         *message)
{
  static SafsImmCtInitializeRet init_value = SAFS_IMM_CT_INITIALIZE_RET__INIT;
  *message = init_value;
}
size_t safs_imm_ct_initialize_ret__get_packed_size
                     (const SafsImmCtInitializeRet *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_initialize_ret__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_initialize_ret__pack
                     (const SafsImmCtInitializeRet *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_initialize_ret__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_initialize_ret__pack_to_buffer
                     (const SafsImmCtInitializeRet *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_initialize_ret__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtInitializeRet *
       safs_imm_ct_initialize_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtInitializeRet *)
     protobuf_c_message_unpack (&safs_imm_ct_initialize_ret__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_initialize_ret__free_unpacked
                     (SafsImmCtInitializeRet *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_initialize_ret__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_finalize_ret__init
                     (SafsImmCtFinalizeRet         *message)
{
  static SafsImmCtFinalizeRet init_value = SAFS_IMM_CT_FINALIZE_RET__INIT;
  *message = init_value;
}
size_t safs_imm_ct_finalize_ret__get_packed_size
                     (const SafsImmCtFinalizeRet *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_finalize_ret__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_finalize_ret__pack
                     (const SafsImmCtFinalizeRet *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_finalize_ret__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_finalize_ret__pack_to_buffer
                     (const SafsImmCtFinalizeRet *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_finalize_ret__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtFinalizeRet *
       safs_imm_ct_finalize_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtFinalizeRet *)
     protobuf_c_message_unpack (&safs_imm_ct_finalize_ret__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_finalize_ret__free_unpacked
                     (SafsImmCtFinalizeRet *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_finalize_ret__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_read_schema_version_ret__init
                     (SafsImmCtReadSchemaVersionRet         *message)
{
  static SafsImmCtReadSchemaVersionRet init_value = SAFS_IMM_CT_READ_SCHEMA_VERSION_RET__INIT;
  *message = init_value;
}
size_t safs_imm_ct_read_schema_version_ret__get_packed_size
                     (const SafsImmCtReadSchemaVersionRet *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_schema_version_ret__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_read_schema_version_ret__pack
                     (const SafsImmCtReadSchemaVersionRet *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_schema_version_ret__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_read_schema_version_ret__pack_to_buffer
                     (const SafsImmCtReadSchemaVersionRet *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_schema_version_ret__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtReadSchemaVersionRet *
       safs_imm_ct_read_schema_version_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtReadSchemaVersionRet *)
     protobuf_c_message_unpack (&safs_imm_ct_read_schema_version_ret__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_read_schema_version_ret__free_unpacked
                     (SafsImmCtReadSchemaVersionRet *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_schema_version_ret__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_fail_upgrade_ret__init
                     (SafsImmCtFailUpgradeRet         *message)
{
  static SafsImmCtFailUpgradeRet init_value = SAFS_IMM_CT_FAIL_UPGRADE_RET__INIT;
  *message = init_value;
}
size_t safs_imm_ct_fail_upgrade_ret__get_packed_size
                     (const SafsImmCtFailUpgradeRet *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_fail_upgrade_ret__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_fail_upgrade_ret__pack
                     (const SafsImmCtFailUpgradeRet *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_fail_upgrade_ret__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_fail_upgrade_ret__pack_to_buffer
                     (const SafsImmCtFailUpgradeRet *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_fail_upgrade_ret__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtFailUpgradeRet *
       safs_imm_ct_fail_upgrade_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtFailUpgradeRet *)
     protobuf_c_message_unpack (&safs_imm_ct_fail_upgrade_ret__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_fail_upgrade_ret__free_unpacked
                     (SafsImmCtFailUpgradeRet *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_fail_upgrade_ret__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_read_instances_ret__init
                     (SafsImmCtReadInstancesRet         *message)
{
  static SafsImmCtReadInstancesRet init_value = SAFS_IMM_CT_READ_INSTANCES_RET__INIT;
  *message = init_value;
}
size_t safs_imm_ct_read_instances_ret__get_packed_size
                     (const SafsImmCtReadInstancesRet *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_instances_ret__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_read_instances_ret__pack
                     (const SafsImmCtReadInstancesRet *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_instances_ret__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_read_instances_ret__pack_to_buffer
                     (const SafsImmCtReadInstancesRet *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_instances_ret__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtReadInstancesRet *
       safs_imm_ct_read_instances_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtReadInstancesRet *)
     protobuf_c_message_unpack (&safs_imm_ct_read_instances_ret__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_read_instances_ret__free_unpacked
                     (SafsImmCtReadInstancesRet *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_read_instances_ret__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_write_instances_ret__init
                     (SafsImmCtWriteInstancesRet         *message)
{
  static SafsImmCtWriteInstancesRet init_value = SAFS_IMM_CT_WRITE_INSTANCES_RET__INIT;
  *message = init_value;
}
size_t safs_imm_ct_write_instances_ret__get_packed_size
                     (const SafsImmCtWriteInstancesRet *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_write_instances_ret__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_write_instances_ret__pack
                     (const SafsImmCtWriteInstancesRet *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_write_instances_ret__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_write_instances_ret__pack_to_buffer
                     (const SafsImmCtWriteInstancesRet *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_write_instances_ret__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtWriteInstancesRet *
       safs_imm_ct_write_instances_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtWriteInstancesRet *)
     protobuf_c_message_unpack (&safs_imm_ct_write_instances_ret__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_write_instances_ret__free_unpacked
                     (SafsImmCtWriteInstancesRet *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_write_instances_ret__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_copy_instances_ret__init
                     (SafsImmCtCopyInstancesRet         *message)
{
  static SafsImmCtCopyInstancesRet init_value = SAFS_IMM_CT_COPY_INSTANCES_RET__INIT;
  *message = init_value;
}
size_t safs_imm_ct_copy_instances_ret__get_packed_size
                     (const SafsImmCtCopyInstancesRet *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_copy_instances_ret__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_copy_instances_ret__pack
                     (const SafsImmCtCopyInstancesRet *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_copy_instances_ret__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_copy_instances_ret__pack_to_buffer
                     (const SafsImmCtCopyInstancesRet *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_copy_instances_ret__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtCopyInstancesRet *
       safs_imm_ct_copy_instances_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtCopyInstancesRet *)
     protobuf_c_message_unpack (&safs_imm_ct_copy_instances_ret__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_copy_instances_ret__free_unpacked
                     (SafsImmCtCopyInstancesRet *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_copy_instances_ret__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_wait_for_classes_ret__init
                     (SafsImmCtWaitForClassesRet         *message)
{
  static SafsImmCtWaitForClassesRet init_value = SAFS_IMM_CT_WAIT_FOR_CLASSES_RET__INIT;
  *message = init_value;
}
size_t safs_imm_ct_wait_for_classes_ret__get_packed_size
                     (const SafsImmCtWaitForClassesRet *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_wait_for_classes_ret__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_wait_for_classes_ret__pack
                     (const SafsImmCtWaitForClassesRet *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_wait_for_classes_ret__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_wait_for_classes_ret__pack_to_buffer
                     (const SafsImmCtWaitForClassesRet *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_wait_for_classes_ret__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtWaitForClassesRet *
       safs_imm_ct_wait_for_classes_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtWaitForClassesRet *)
     protobuf_c_message_unpack (&safs_imm_ct_wait_for_classes_ret__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_wait_for_classes_ret__free_unpacked
                     (SafsImmCtWaitForClassesRet *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_wait_for_classes_ret__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_write_rt_instances_ret__init
                     (SafsImmCtWriteRtInstancesRet         *message)
{
  static SafsImmCtWriteRtInstancesRet init_value = SAFS_IMM_CT_WRITE_RT_INSTANCES_RET__INIT;
  *message = init_value;
}
size_t safs_imm_ct_write_rt_instances_ret__get_packed_size
                     (const SafsImmCtWriteRtInstancesRet *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_write_rt_instances_ret__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_write_rt_instances_ret__pack
                     (const SafsImmCtWriteRtInstancesRet *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_write_rt_instances_ret__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_write_rt_instances_ret__pack_to_buffer
                     (const SafsImmCtWriteRtInstancesRet *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_write_rt_instances_ret__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtWriteRtInstancesRet *
       safs_imm_ct_write_rt_instances_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtWriteRtInstancesRet *)
     protobuf_c_message_unpack (&safs_imm_ct_write_rt_instances_ret__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_write_rt_instances_ret__free_unpacked
                     (SafsImmCtWriteRtInstancesRet *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_write_rt_instances_ret__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   safs_imm_ct_copy_rt_instances_ret__init
                     (SafsImmCtCopyRtInstancesRet         *message)
{
  static SafsImmCtCopyRtInstancesRet init_value = SAFS_IMM_CT_COPY_RT_INSTANCES_RET__INIT;
  *message = init_value;
}
size_t safs_imm_ct_copy_rt_instances_ret__get_packed_size
                     (const SafsImmCtCopyRtInstancesRet *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_copy_rt_instances_ret__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t safs_imm_ct_copy_rt_instances_ret__pack
                     (const SafsImmCtCopyRtInstancesRet *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_copy_rt_instances_ret__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t safs_imm_ct_copy_rt_instances_ret__pack_to_buffer
                     (const SafsImmCtCopyRtInstancesRet *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_copy_rt_instances_ret__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SafsImmCtCopyRtInstancesRet *
       safs_imm_ct_copy_rt_instances_ret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SafsImmCtCopyRtInstancesRet *)
     protobuf_c_message_unpack (&safs_imm_ct_copy_rt_instances_ret__descriptor,
                                allocator, len, data);
}
void   safs_imm_ct_copy_rt_instances_ret__free_unpacked
                     (SafsImmCtCopyRtInstancesRet *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &safs_imm_ct_copy_rt_instances_ret__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor safs_imm_ct_schema_version__field_descriptors[3] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtSchemaVersion, version),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "release",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtSchemaVersion, release),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "correction",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtSchemaVersion, correction),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_schema_version__field_indices_by_name[] = {
  2,   /* field[2] = correction */
  1,   /* field[1] = release */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange safs_imm_ct_schema_version__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor safs_imm_ct_schema_version__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtSchemaVersion",
  "SafsImmCtSchemaVersion",
  "SafsImmCtSchemaVersion",
  "",
  sizeof(SafsImmCtSchemaVersion),
  3,
  safs_imm_ct_schema_version__field_descriptors,
  safs_imm_ct_schema_version__field_indices_by_name,
  1,  safs_imm_ct_schema_version__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_schema_version__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_instance__field_descriptors[2] =
{
  {
    "parentName",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtInstance, parentname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attrValues",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SafsImmCtInstance, n_attrvalues),
    PROTOBUF_C_OFFSETOF(SafsImmCtInstance, attrvalues),
    &safs_imm_attr_values_2__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_instance__field_indices_by_name[] = {
  1,   /* field[1] = attrValues */
  0,   /* field[0] = parentName */
};
static const ProtobufCIntRange safs_imm_ct_instance__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor safs_imm_ct_instance__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtInstance",
  "SafsImmCtInstance",
  "SafsImmCtInstance",
  "",
  sizeof(SafsImmCtInstance),
  2,
  safs_imm_ct_instance__field_descriptors,
  safs_imm_ct_instance__field_indices_by_name,
  1,  safs_imm_ct_instance__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_instance__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_instance_group__field_descriptors[2] =
{
  {
    "className",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtInstanceGroup, classname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instances",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SafsImmCtInstanceGroup, n_instances),
    PROTOBUF_C_OFFSETOF(SafsImmCtInstanceGroup, instances),
    &safs_imm_ct_instance__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_instance_group__field_indices_by_name[] = {
  0,   /* field[0] = className */
  1,   /* field[1] = instances */
};
static const ProtobufCIntRange safs_imm_ct_instance_group__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor safs_imm_ct_instance_group__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtInstanceGroup",
  "SafsImmCtInstanceGroup",
  "SafsImmCtInstanceGroup",
  "",
  sizeof(SafsImmCtInstanceGroup),
  2,
  safs_imm_ct_instance_group__field_descriptors,
  safs_imm_ct_instance_group__field_indices_by_name,
  1,  safs_imm_ct_instance_group__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_instance_group__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_message__field_descriptors[12] =
{
  {
    "initialize",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtMessage, initialize),
    &safs_imm_ct_initialize__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "finalize",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtMessage, finalize),
    &safs_imm_ct_finalize__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "readSchemaVersion",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtMessage, readschemaversion),
    &safs_imm_ct_read_schema_version__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "failUpgrade",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtMessage, failupgrade),
    &safs_imm_ct_fail_upgrade__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "readInstances",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtMessage, readinstances),
    &safs_imm_ct_read_instances__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "writeInstances",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtMessage, writeinstances),
    &safs_imm_ct_write_instances__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "copyInstances",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtMessage, copyinstances),
    &safs_imm_ct_copy_instances__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "waitForClasses",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtMessage, waitforclasses),
    &safs_imm_ct_wait_for_classes__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "writeRtInstances",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtMessage, writertinstances),
    &safs_imm_ct_write_rt_instances__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "copyRtInstances",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtMessage, copyrtinstances),
    &safs_imm_ct_copy_rt_instances__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "readInstances_2",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtMessage, readinstances_2),
    &safs_imm_ct_read_instances_2__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "initialize_2",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtMessage, initialize_2),
    &safs_imm_ct_initialize_2__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_message__field_indices_by_name[] = {
  6,   /* field[6] = copyInstances */
  9,   /* field[9] = copyRtInstances */
  3,   /* field[3] = failUpgrade */
  1,   /* field[1] = finalize */
  0,   /* field[0] = initialize */
  11,   /* field[11] = initialize_2 */
  4,   /* field[4] = readInstances */
  10,   /* field[10] = readInstances_2 */
  2,   /* field[2] = readSchemaVersion */
  7,   /* field[7] = waitForClasses */
  5,   /* field[5] = writeInstances */
  8,   /* field[8] = writeRtInstances */
};
static const ProtobufCIntRange safs_imm_ct_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor safs_imm_ct_message__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtMessage",
  "SafsImmCtMessage",
  "SafsImmCtMessage",
  "",
  sizeof(SafsImmCtMessage),
  12,
  safs_imm_ct_message__field_descriptors,
  safs_imm_ct_message__field_indices_by_name,
  1,  safs_imm_ct_message__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_initialize__field_descriptors[1] =
{
  {
    "callerPid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtInitialize, callerpid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_initialize__field_indices_by_name[] = {
  0,   /* field[0] = callerPid */
};
static const ProtobufCIntRange safs_imm_ct_initialize__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor safs_imm_ct_initialize__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtInitialize",
  "SafsImmCtInitialize",
  "SafsImmCtInitialize",
  "",
  sizeof(SafsImmCtInitialize),
  1,
  safs_imm_ct_initialize__field_descriptors,
  safs_imm_ct_initialize__field_indices_by_name,
  1,  safs_imm_ct_initialize__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_initialize__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_initialize_2__field_descriptors[2] =
{
  {
    "callerPid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtInitialize2, callerpid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delayedStart",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtInitialize2, delayedstart),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_initialize_2__field_indices_by_name[] = {
  0,   /* field[0] = callerPid */
  1,   /* field[1] = delayedStart */
};
static const ProtobufCIntRange safs_imm_ct_initialize_2__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor safs_imm_ct_initialize_2__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtInitialize_2",
  "SafsImmCtInitialize2",
  "SafsImmCtInitialize2",
  "",
  sizeof(SafsImmCtInitialize2),
  2,
  safs_imm_ct_initialize_2__field_descriptors,
  safs_imm_ct_initialize_2__field_indices_by_name,
  2,  safs_imm_ct_initialize_2__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_initialize_2__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_finalize__field_descriptors[1] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtFinalize, handle),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_finalize__field_indices_by_name[] = {
  0,   /* field[0] = handle */
};
static const ProtobufCIntRange safs_imm_ct_finalize__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor safs_imm_ct_finalize__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtFinalize",
  "SafsImmCtFinalize",
  "SafsImmCtFinalize",
  "",
  sizeof(SafsImmCtFinalize),
  1,
  safs_imm_ct_finalize__field_descriptors,
  safs_imm_ct_finalize__field_indices_by_name,
  1,  safs_imm_ct_finalize__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_finalize__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_read_schema_version__field_descriptors[2] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtReadSchemaVersion, handle),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "schemaName",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtReadSchemaVersion, schemaname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_read_schema_version__field_indices_by_name[] = {
  0,   /* field[0] = handle */
  1,   /* field[1] = schemaName */
};
static const ProtobufCIntRange safs_imm_ct_read_schema_version__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor safs_imm_ct_read_schema_version__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtReadSchemaVersion",
  "SafsImmCtReadSchemaVersion",
  "SafsImmCtReadSchemaVersion",
  "",
  sizeof(SafsImmCtReadSchemaVersion),
  2,
  safs_imm_ct_read_schema_version__field_descriptors,
  safs_imm_ct_read_schema_version__field_indices_by_name,
  1,  safs_imm_ct_read_schema_version__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_read_schema_version__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_fail_upgrade__field_descriptors[2] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtFailUpgrade, handle),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtFailUpgrade, message),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_fail_upgrade__field_indices_by_name[] = {
  0,   /* field[0] = handle */
  1,   /* field[1] = message */
};
static const ProtobufCIntRange safs_imm_ct_fail_upgrade__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor safs_imm_ct_fail_upgrade__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtFailUpgrade",
  "SafsImmCtFailUpgrade",
  "SafsImmCtFailUpgrade",
  "",
  sizeof(SafsImmCtFailUpgrade),
  2,
  safs_imm_ct_fail_upgrade__field_descriptors,
  safs_imm_ct_fail_upgrade__field_indices_by_name,
  1,  safs_imm_ct_fail_upgrade__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_fail_upgrade__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_read_instances__field_descriptors[2] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtReadInstances, handle),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "classNames",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(SafsImmCtReadInstances, n_classnames),
    PROTOBUF_C_OFFSETOF(SafsImmCtReadInstances, classnames),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_read_instances__field_indices_by_name[] = {
  1,   /* field[1] = classNames */
  0,   /* field[0] = handle */
};
static const ProtobufCIntRange safs_imm_ct_read_instances__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor safs_imm_ct_read_instances__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtReadInstances",
  "SafsImmCtReadInstances",
  "SafsImmCtReadInstances",
  "",
  sizeof(SafsImmCtReadInstances),
  2,
  safs_imm_ct_read_instances__field_descriptors,
  safs_imm_ct_read_instances__field_indices_by_name,
  1,  safs_imm_ct_read_instances__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_read_instances__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_read_instances_2__field_descriptors[2] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtReadInstances2, handle),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "classNames",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(SafsImmCtReadInstances2, n_classnames),
    PROTOBUF_C_OFFSETOF(SafsImmCtReadInstances2, classnames),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_read_instances_2__field_indices_by_name[] = {
  1,   /* field[1] = classNames */
  0,   /* field[0] = handle */
};
static const ProtobufCIntRange safs_imm_ct_read_instances_2__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor safs_imm_ct_read_instances_2__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtReadInstances_2",
  "SafsImmCtReadInstances2",
  "SafsImmCtReadInstances2",
  "",
  sizeof(SafsImmCtReadInstances2),
  2,
  safs_imm_ct_read_instances_2__field_descriptors,
  safs_imm_ct_read_instances_2__field_indices_by_name,
  1,  safs_imm_ct_read_instances_2__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_read_instances_2__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_write_instances__field_descriptors[2] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtWriteInstances, handle),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instanceGroups",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SafsImmCtWriteInstances, n_instancegroups),
    PROTOBUF_C_OFFSETOF(SafsImmCtWriteInstances, instancegroups),
    &safs_imm_ct_instance_group__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_write_instances__field_indices_by_name[] = {
  0,   /* field[0] = handle */
  1,   /* field[1] = instanceGroups */
};
static const ProtobufCIntRange safs_imm_ct_write_instances__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor safs_imm_ct_write_instances__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtWriteInstances",
  "SafsImmCtWriteInstances",
  "SafsImmCtWriteInstances",
  "",
  sizeof(SafsImmCtWriteInstances),
  2,
  safs_imm_ct_write_instances__field_descriptors,
  safs_imm_ct_write_instances__field_indices_by_name,
  1,  safs_imm_ct_write_instances__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_write_instances__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_copy_instances__field_descriptors[2] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtCopyInstances, handle),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "classNames",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(SafsImmCtCopyInstances, n_classnames),
    PROTOBUF_C_OFFSETOF(SafsImmCtCopyInstances, classnames),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_copy_instances__field_indices_by_name[] = {
  1,   /* field[1] = classNames */
  0,   /* field[0] = handle */
};
static const ProtobufCIntRange safs_imm_ct_copy_instances__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor safs_imm_ct_copy_instances__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtCopyInstances",
  "SafsImmCtCopyInstances",
  "SafsImmCtCopyInstances",
  "",
  sizeof(SafsImmCtCopyInstances),
  2,
  safs_imm_ct_copy_instances__field_descriptors,
  safs_imm_ct_copy_instances__field_indices_by_name,
  1,  safs_imm_ct_copy_instances__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_copy_instances__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_wait_for_classes__field_descriptors[2] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtWaitForClasses, handle),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "classNames",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(SafsImmCtWaitForClasses, n_classnames),
    PROTOBUF_C_OFFSETOF(SafsImmCtWaitForClasses, classnames),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_wait_for_classes__field_indices_by_name[] = {
  1,   /* field[1] = classNames */
  0,   /* field[0] = handle */
};
static const ProtobufCIntRange safs_imm_ct_wait_for_classes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor safs_imm_ct_wait_for_classes__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtWaitForClasses",
  "SafsImmCtWaitForClasses",
  "SafsImmCtWaitForClasses",
  "",
  sizeof(SafsImmCtWaitForClasses),
  2,
  safs_imm_ct_wait_for_classes__field_descriptors,
  safs_imm_ct_wait_for_classes__field_indices_by_name,
  1,  safs_imm_ct_wait_for_classes__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_wait_for_classes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_write_rt_instances__field_descriptors[3] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtWriteRtInstances, handle),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "implementerName",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtWriteRtInstances, implementername),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instanceGroups",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SafsImmCtWriteRtInstances, n_instancegroups),
    PROTOBUF_C_OFFSETOF(SafsImmCtWriteRtInstances, instancegroups),
    &safs_imm_ct_instance_group__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_write_rt_instances__field_indices_by_name[] = {
  0,   /* field[0] = handle */
  1,   /* field[1] = implementerName */
  2,   /* field[2] = instanceGroups */
};
static const ProtobufCIntRange safs_imm_ct_write_rt_instances__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor safs_imm_ct_write_rt_instances__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtWriteRtInstances",
  "SafsImmCtWriteRtInstances",
  "SafsImmCtWriteRtInstances",
  "",
  sizeof(SafsImmCtWriteRtInstances),
  3,
  safs_imm_ct_write_rt_instances__field_descriptors,
  safs_imm_ct_write_rt_instances__field_indices_by_name,
  1,  safs_imm_ct_write_rt_instances__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_write_rt_instances__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_copy_rt_instances__field_descriptors[3] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtCopyRtInstances, handle),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "implementerName",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtCopyRtInstances, implementername),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "classNames",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(SafsImmCtCopyRtInstances, n_classnames),
    PROTOBUF_C_OFFSETOF(SafsImmCtCopyRtInstances, classnames),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_copy_rt_instances__field_indices_by_name[] = {
  2,   /* field[2] = classNames */
  0,   /* field[0] = handle */
  1,   /* field[1] = implementerName */
};
static const ProtobufCIntRange safs_imm_ct_copy_rt_instances__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor safs_imm_ct_copy_rt_instances__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtCopyRtInstances",
  "SafsImmCtCopyRtInstances",
  "SafsImmCtCopyRtInstances",
  "",
  sizeof(SafsImmCtCopyRtInstances),
  3,
  safs_imm_ct_copy_rt_instances__field_descriptors,
  safs_imm_ct_copy_rt_instances__field_indices_by_name,
  1,  safs_imm_ct_copy_rt_instances__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_copy_rt_instances__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_initialize_ret__field_descriptors[2] =
{
  {
    "returnVal",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtInitializeRet, returnval),
    &safs_ais_error__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "handle",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(SafsImmCtInitializeRet, has_handle),
    PROTOBUF_C_OFFSETOF(SafsImmCtInitializeRet, handle),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_initialize_ret__field_indices_by_name[] = {
  1,   /* field[1] = handle */
  0,   /* field[0] = returnVal */
};
static const ProtobufCIntRange safs_imm_ct_initialize_ret__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor safs_imm_ct_initialize_ret__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtInitializeRet",
  "SafsImmCtInitializeRet",
  "SafsImmCtInitializeRet",
  "",
  sizeof(SafsImmCtInitializeRet),
  2,
  safs_imm_ct_initialize_ret__field_descriptors,
  safs_imm_ct_initialize_ret__field_indices_by_name,
  1,  safs_imm_ct_initialize_ret__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_initialize_ret__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_finalize_ret__field_descriptors[1] =
{
  {
    "returnVal",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtFinalizeRet, returnval),
    &safs_ais_error__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_finalize_ret__field_indices_by_name[] = {
  0,   /* field[0] = returnVal */
};
static const ProtobufCIntRange safs_imm_ct_finalize_ret__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor safs_imm_ct_finalize_ret__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtFinalizeRet",
  "SafsImmCtFinalizeRet",
  "SafsImmCtFinalizeRet",
  "",
  sizeof(SafsImmCtFinalizeRet),
  1,
  safs_imm_ct_finalize_ret__field_descriptors,
  safs_imm_ct_finalize_ret__field_indices_by_name,
  1,  safs_imm_ct_finalize_ret__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_finalize_ret__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_read_schema_version_ret__field_descriptors[3] =
{
  {
    "returnVal",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtReadSchemaVersionRet, returnval),
    &safs_ais_error__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "oldVersion",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtReadSchemaVersionRet, oldversion),
    &safs_imm_ct_schema_version__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "newVersion",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtReadSchemaVersionRet, newversion),
    &safs_imm_ct_schema_version__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_read_schema_version_ret__field_indices_by_name[] = {
  2,   /* field[2] = newVersion */
  1,   /* field[1] = oldVersion */
  0,   /* field[0] = returnVal */
};
static const ProtobufCIntRange safs_imm_ct_read_schema_version_ret__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor safs_imm_ct_read_schema_version_ret__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtReadSchemaVersionRet",
  "SafsImmCtReadSchemaVersionRet",
  "SafsImmCtReadSchemaVersionRet",
  "",
  sizeof(SafsImmCtReadSchemaVersionRet),
  3,
  safs_imm_ct_read_schema_version_ret__field_descriptors,
  safs_imm_ct_read_schema_version_ret__field_indices_by_name,
  1,  safs_imm_ct_read_schema_version_ret__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_read_schema_version_ret__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_fail_upgrade_ret__field_descriptors[1] =
{
  {
    "returnVal",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtFailUpgradeRet, returnval),
    &safs_ais_error__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_fail_upgrade_ret__field_indices_by_name[] = {
  0,   /* field[0] = returnVal */
};
static const ProtobufCIntRange safs_imm_ct_fail_upgrade_ret__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor safs_imm_ct_fail_upgrade_ret__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtFailUpgradeRet",
  "SafsImmCtFailUpgradeRet",
  "SafsImmCtFailUpgradeRet",
  "",
  sizeof(SafsImmCtFailUpgradeRet),
  1,
  safs_imm_ct_fail_upgrade_ret__field_descriptors,
  safs_imm_ct_fail_upgrade_ret__field_indices_by_name,
  1,  safs_imm_ct_fail_upgrade_ret__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_fail_upgrade_ret__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_read_instances_ret__field_descriptors[2] =
{
  {
    "returnVal",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtReadInstancesRet, returnval),
    &safs_ais_error__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instanceGroups",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SafsImmCtReadInstancesRet, n_instancegroups),
    PROTOBUF_C_OFFSETOF(SafsImmCtReadInstancesRet, instancegroups),
    &safs_imm_ct_instance_group__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_read_instances_ret__field_indices_by_name[] = {
  1,   /* field[1] = instanceGroups */
  0,   /* field[0] = returnVal */
};
static const ProtobufCIntRange safs_imm_ct_read_instances_ret__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor safs_imm_ct_read_instances_ret__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtReadInstancesRet",
  "SafsImmCtReadInstancesRet",
  "SafsImmCtReadInstancesRet",
  "",
  sizeof(SafsImmCtReadInstancesRet),
  2,
  safs_imm_ct_read_instances_ret__field_descriptors,
  safs_imm_ct_read_instances_ret__field_indices_by_name,
  1,  safs_imm_ct_read_instances_ret__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_read_instances_ret__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_write_instances_ret__field_descriptors[1] =
{
  {
    "returnVal",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtWriteInstancesRet, returnval),
    &safs_ais_error__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_write_instances_ret__field_indices_by_name[] = {
  0,   /* field[0] = returnVal */
};
static const ProtobufCIntRange safs_imm_ct_write_instances_ret__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor safs_imm_ct_write_instances_ret__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtWriteInstancesRet",
  "SafsImmCtWriteInstancesRet",
  "SafsImmCtWriteInstancesRet",
  "",
  sizeof(SafsImmCtWriteInstancesRet),
  1,
  safs_imm_ct_write_instances_ret__field_descriptors,
  safs_imm_ct_write_instances_ret__field_indices_by_name,
  1,  safs_imm_ct_write_instances_ret__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_write_instances_ret__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_copy_instances_ret__field_descriptors[1] =
{
  {
    "returnVal",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtCopyInstancesRet, returnval),
    &safs_ais_error__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_copy_instances_ret__field_indices_by_name[] = {
  0,   /* field[0] = returnVal */
};
static const ProtobufCIntRange safs_imm_ct_copy_instances_ret__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor safs_imm_ct_copy_instances_ret__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtCopyInstancesRet",
  "SafsImmCtCopyInstancesRet",
  "SafsImmCtCopyInstancesRet",
  "",
  sizeof(SafsImmCtCopyInstancesRet),
  1,
  safs_imm_ct_copy_instances_ret__field_descriptors,
  safs_imm_ct_copy_instances_ret__field_indices_by_name,
  1,  safs_imm_ct_copy_instances_ret__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_copy_instances_ret__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_wait_for_classes_ret__field_descriptors[1] =
{
  {
    "returnVal",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtWaitForClassesRet, returnval),
    &safs_ais_error__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_wait_for_classes_ret__field_indices_by_name[] = {
  0,   /* field[0] = returnVal */
};
static const ProtobufCIntRange safs_imm_ct_wait_for_classes_ret__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor safs_imm_ct_wait_for_classes_ret__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtWaitForClassesRet",
  "SafsImmCtWaitForClassesRet",
  "SafsImmCtWaitForClassesRet",
  "",
  sizeof(SafsImmCtWaitForClassesRet),
  1,
  safs_imm_ct_wait_for_classes_ret__field_descriptors,
  safs_imm_ct_wait_for_classes_ret__field_indices_by_name,
  1,  safs_imm_ct_wait_for_classes_ret__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_wait_for_classes_ret__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_write_rt_instances_ret__field_descriptors[1] =
{
  {
    "returnVal",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtWriteRtInstancesRet, returnval),
    &safs_ais_error__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_write_rt_instances_ret__field_indices_by_name[] = {
  0,   /* field[0] = returnVal */
};
static const ProtobufCIntRange safs_imm_ct_write_rt_instances_ret__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor safs_imm_ct_write_rt_instances_ret__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtWriteRtInstancesRet",
  "SafsImmCtWriteRtInstancesRet",
  "SafsImmCtWriteRtInstancesRet",
  "",
  sizeof(SafsImmCtWriteRtInstancesRet),
  1,
  safs_imm_ct_write_rt_instances_ret__field_descriptors,
  safs_imm_ct_write_rt_instances_ret__field_indices_by_name,
  1,  safs_imm_ct_write_rt_instances_ret__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_write_rt_instances_ret__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor safs_imm_ct_copy_rt_instances_ret__field_descriptors[1] =
{
  {
    "returnVal",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SafsImmCtCopyRtInstancesRet, returnval),
    &safs_ais_error__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned safs_imm_ct_copy_rt_instances_ret__field_indices_by_name[] = {
  0,   /* field[0] = returnVal */
};
static const ProtobufCIntRange safs_imm_ct_copy_rt_instances_ret__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor safs_imm_ct_copy_rt_instances_ret__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "safsImmCtCopyRtInstancesRet",
  "SafsImmCtCopyRtInstancesRet",
  "SafsImmCtCopyRtInstancesRet",
  "",
  sizeof(SafsImmCtCopyRtInstancesRet),
  1,
  safs_imm_ct_copy_rt_instances_ret__field_descriptors,
  safs_imm_ct_copy_rt_instances_ret__field_indices_by_name,
  1,  safs_imm_ct_copy_rt_instances_ret__number_ranges,
  (ProtobufCMessageInit) safs_imm_ct_copy_rt_instances_ret__init,
  NULL,NULL,NULL    /* reserved[123] */
};
