@startuml

title VRCS 5G Use Case Anatomy\n

skinparam usecase {
    BackgroundColor lightgreen
    BorderColor     black
    ArrowColor      darkgreen
}

database nodeup as "Node UP Delivery\nCL=3" #lightblue

/'
 ' List of use cases. Remove the #lightyellow param when a use case
 ' is ready for production. Use light* colors for background.
 '
 ' Note: if all in dependencies for a use case are complete (green),
 ' but the use case itself is not ready for production (lightyellow), then there
 ' must be a TODO describing what is missing. A use case with any non-green
 ' "in" dependencies is always not ready for production.
 '/
(3PP SWU\nDeliver\n--TODO--\n- Version handling\n  - URL + Git hash/tag) as 3ppswudelivery #lightyellow
(AS: VRCS\nBuild & Deliver\nCSX 101 79/2\n--TODO--\n- Jenkins job\n- Version handling) as asvrcsbuild #lightgrey
(BRCS-EE CNX\nBuild & Deliver\nCNX 901 3327/3\n--TODO--\n- Jenkins job\n- Version handling) as brcseecnxbuild #lightgrey
(BRCS-EE CRX\nBuild & Deliver\nCRX 901 295\n--TODO--\n- Jenkins job\n- Version handling) as brcseecrxbuild #lightgrey
(BRCS-MW CRX\nBuild & Deliver\nCRX 901 297\n--TODO--\n- Jenkins job\n- Version handling\n- Document mapping) as brcsmwcrxbuild  #lightgrey
(COM Build & Deliver\nCXC 173 3991/4\n--TODO--\n- Version handling\n- Jenkins job) as combuild #lightgrey
(COM Source\nDownload\n--TODO--\n- Version handling) as comdownload     #lightgrey
(EE CAX\nDeliver)                                    as eecaxdelivery   #lightblue
(EE Submit)                                          as eesubmit        #lightblue
(MW Submit)                                          as mwsubmit
(Move to\nproduction repo)                           as productionrepo  #lightgrey
(Node UP Build\n--TODO--\n- Inform Node CI of new\nproduct numbers) as nodeupbuild #lightgrey
(OTP CXC\nBuild & Deliver\nOTP4_CXC1733859/4\nOTP14_CXC1733859/14\n--TODO--\n- Jenkins job\n- Version handling) as otpcxcbuild #lightgrey
(OTP Source\nDownload\n--TODO--\n- Version handling) as otpdownload     #lightyellow
(OTP Test CXC\nBuild & Deliver\n--TODO--\n- Jenkins job\n- Version handling) as otptestcxcbuild #lightgrey
(OTP Tool Build\nLXA...\n--TODO--\n- Version handling) as otptoolbuild  #lightgrey
(OTP Tool\nDeliver)                                  as otptooldelivery #lightgrey
(RCS-MW CAX\nBuild & Deliver\nCAX 103 4072\n--TODO--\n- Archive in ClearCase\n- Emit Eiffel events\n- R-state handling) as mwcaxdelivery #lightgrey
(RCS-MW CNX\nBuild & Deliver\nCNX 901 3431\n--TODO--\n- Jenkins job\n- Version handling\n- Document mapping) as rcsmwcnxbuild  #lightgrey
(SS: RCP\nBuild & Deliver\nCSX 101 79\n--TODO--\n- Jenkins job\n- Version handling\n- Document mapping) as ssrcpbuild #lightgrey
(Set CL=1)                                           as setcl1
(Update the radiator)                                as updateradiator  #lightgrey
(Use R-states)                                       as userstates      #lightgrey
(VRCS ALL\nBuild & Deliver\nCXS 101 654\n--TODO--\n- Jenkins job\n- Version handling) as vrcsallbuild #lightgrey
(VRCS SBC\n--TODO--\n- Remove all ClearCase\ndependencies) as vrcssbc   #lightyellow
(VRCS UP\nBuild & Deliver\nCXS 101 657/2\n--TODO--\n- R-state handling\n- Nexus upload\n- Baseline is VRCS-MW\nCXP CL=1) as vrcsupbuild #lightyellow
(VRCS UP\n Set CL=1\n--TODO--\n- Jenkins job)        as vrcsupsetcl1  #lightgrey
(VRCS-DUMMY\nBuild & Deliver\nCXP 902 9207/4\n--TODO--\n- Version handling\n- Jenkins job) as dummybuild #lightgrey
(VRCS-EE SDK\nBuild & Deliver\n--TODO--\n- Versioning) as vrcseesdkbuild #lightblue
(VRCS-EE\nBuild & Deliver\nCXA 114 48/2\n--TODO--\n- Upload to ARM\n- Eiffel messaging) as vrcseecxabuild #lightblue
(VRCS-EE\nBuild & Deliver\nCXC 173 9272/2\n--TODO--\n- Upload to ARM\n- Eiffel messaging) as vrcseecxcbuild #lightblue
(VRCS-EE\nBuild & Deliver\nCXP 902 9177/2\n--TODO--\n- Upload to ARM\n- Eiffel messaging\n- Move to Git by EE) as vrcseecxpbuild #lightblue
(VRCS-MW Deliver\nCXP 902 9176/4\n--TODO--\n- COM configuration?\n- OTP configuration?) as mwdelivery #lightyellow
(VRCS-MW\nBuild & Package\nCXP 902 9176/4\n--TODO--\n- Baseline handling\n- COM handling\n- OTP handling) as mwbuild #lightyellow
(VRCS-MW SDC\n--TODO--\n- Remove all ClearCase\ndependencies) as vrcssdc #lightyellow
(VRCSI\nBuild & Deliver\nCXS 101 659\n--TODO--\n- Version handling\n- Jenkins job) as vrcsibuild #lightgrey

skinparam mwsdc {
   BorderColor red
}

/'
 ' Use case dependencies
 ' Use green, b0b000, and blue for arrow colors, not "light*"
 '/
3ppswudelivery  -up-> mwbuild         #grey
brcseecnxbuild  -up-> brcseecrxbuild  #grey
brcseecrxbuild  -up-> ssrcpbuild      #grey
brcsmwcrxbuild  -up-> ssrcpbuild      #grey
combuild        -up-> mwbuild         #grey
comdownload     -up-> combuild        #grey
dummybuild      -up-> vrcsallbuild    #grey
dummybuild      -up-> vrcsupbuild     #grey
eecaxdelivery   -up-> brcseecnxbuild  #grey
eesubmit        -up-> vrcseecxabuild  #blue
eesubmit        -up-> vrcseecxcbuild  #blue
eesubmit        -up-> vrcseesdkbuild  #blue
mwbuild         -up-> mwcaxdelivery   #grey
mwbuild         -up-> mwdelivery      #green
mwbuild         -up-> vrcsibuild      #grey
mwcaxdelivery   -up-> rcsmwcnxbuild   #grey
mwdelivery      -up-  userstates      #grey
mwdelivery      -up-> vrcsallbuild    #grey
mwdelivery      -up-> vrcsupbuild     #green
mwsubmit        -up-> dummybuild      #b0b000
mwsubmit        -up-> mwbuild
nodeup          .up.> vrcssbc         #blue : JCAT\ntests
otpcxcbuild     -up-> mwbuild         #grey
otpdownload     -up-> mwbuild         #grey : OTP runtime
otpdownload     -up-> otpcxcbuild     #grey
otpdownload     -up-> otptestcxcbuild #grey
otpdownload     -up-> otptoolbuild    #b0b000 : OTP toolchain
otptestcxcbuild -up-> vrcsupbuild     #grey
otptoolbuild    -up-> otptooldelivery #b0b000
otptooldelivery -up-> mwbuild         #grey
productionrepo  -up-  nodeupbuild     #grey
rcsmwcnxbuild   -up-> brcsmwcrxbuild  #grey
userstates      -up-  nodeupbuild     #grey
vrcsallbuild    -up-> asvrcsbuild     #grey
vrcseecxabuild  -up-> vrcsibuild      #grey
vrcseecxcbuild  -up-> vrcseecxpbuild  #blue
vrcseecxpbuild  -up-  userstates      #grey
vrcseecxpbuild  -up-> eecaxdelivery   #blue
vrcseecxpbuild  -up-> vrcsallbuild    #blue
vrcseecxpbuild  -up-> vrcsupbuild     #grey
vrcseesdkbuild  -up-> mwbuild         #grey
vrcsibuild      -up-> asvrcsbuild     #grey
vrcssbc         -up-> setcl1
vrcssdc         -up-> mwsubmit
vrcsupbuild     -up-> vrcssbc
vrcssbc         -up-> vrcsupsetcl1    #grey
vrcsupsetcl1    -up-> asvrcsbuild     #grey : Trigger CL=1

/'
 ' Legend
 '/
skinparam legendBackgroundColor white
legend
__Legend__

<back:lightgreen>Green</back> is ready for production
<back:lightyellow>Yellow</back> is incomplete
<back:lightgrey>Grey</back> is not started
<back:lightblue>Blue</back> is out of scope
- Bullet lists list unfinished tasks
end legend
@enduml
