#!/bin/bash
# script to change COM CLI idle timoeut

tmo=$1

fileLibCom=`readlink -f $RCS_ROOT/home/*/releases/*/comte*/libcom_cli_agent.cfg`

ERL_CALL=`readlink -f ${OTP_ROOT}/lib/erl_interface-*/bin/erl_call`
ERL_CALL_CMD="${ERL_CALL} -sname ${SNAME} -c ${RCS_COOKIE} " 

usage="Usage: com_cli_timeout Time(s), 0 = infinity"

function is_int() { return $(test "$@" -eq "$@" > /dev/null 2>&1); } 

if [ $# -eq 0 ]; then
    val=`grep connection $fileLibCom | sed "s'connectionTimeOut''g" | tr -d "<>/ " `
    echo "Current timeout= $val"
elif [ $# -ne 1 ]; then
    echo $usage
elif [ -f $fileLibCom ]; then
    if $(is_int "${tmo}"); then
	sed -i "s'.*connectionTimeOut.*'<connectionTimeOut>$tmo</connectionTimeOut>'" $fileLibCom
	echo "COM CLI idle timeout changed to $tmo seconds"
	echo "Restarting COM"
	a=`${ERL_CALL_CMD} -a 'comte stop_com []' `
	sleep 1
	a=`${ERL_CALL_CMD} -a 'comte start_com []' `
    else
	echo "Not a valid timeout value: $tmo"
    fi
	
else
    echo "cannot find libcom_cli_agent.cfg file"
fi
