#!/bin/bash
# script to print COM version

start_com_script=`readlink -f $RCS_ROOT/home/*/releases/*/comte*/start_com`

LD_PATH=`grep COM_LD_LIBRARY_PATH= $start_com_script  | awk -F= '{ print $2 }'| tr -d '"'`
COM_BIN=`grep COM_BIN= $start_com_script  | awk -F= '{ print $2 }' | tr -d '"'` 

export LD_LIBRARY_PATH="${LD_PATH}:$LD_LIBRARY_PATH"
${COM_BIN} --version
