#!/bin/bash
# script to change COM log_level
lvl=$1

fileCom=`readlink -f $RCS_ROOT/home/*/releases/*/comte*/start_com`
fileComte=`readlink -f $RCS_ROOT/home/*/releases/*/comte*/libComtE.cfg`

ERL_CALL=`readlink -f ${OTP_ROOT}/lib/erl_interface-*/bin/erl_call`
ERL_CALL_CMD="${ERL_CALL} -sname ${SNAME} -c ${RCS_COOKIE} " 

usage="Usage: log_level Level (0..8)"

function is_int() { return $(test "$@" -eq "$@" > /dev/null 2>&1); } 

if [ $# -eq 0 ]; then
    echo $usage
    val=`grep COM_LOGGING_LEVEL= $fileCom`
    echo "Current value: $val"
elif [ $# -ne 1 ]; then
    echo $usage  
elif [ -x $file ]; then
    if $(is_int "${lvl}"); then
	if [ $lvl -ge 0 -a $lvl -le 8 ]
	then
	    sed -i "s/.*MAF_LOGGING_LEVEL=.*/MAF_LOGGING_LEVEL=$lvl/" $fileCom
	    sed -i "s/.*COM_LOGGING_LEVEL=.*/COM_LOGGING_LEVEL=$lvl/" $fileCom
	    sed -i "s'.*<comte_logging_level>.*'<comte_logging_level>$lvl</comte_logging_level>'" $fileComte
	    echo "COM logging level changed to $lvl"
	    echo "Restarting COM"
	    a=`${ERL_CALL_CMD} -a 'comte stop_com []' `
	    sleep 1
	    a=`${ERL_CALL_CMD} -a 'comte start_com []' `
	    
	else
	    echo "level must be in range 0 to 8"
	fi
    else
	echo "level must be an integer in range 0 to 8"
    fi
else
    echo "cannot find start_com file"
fi
