/*
 *
 * Copyright (c) Ericsson AB  2014 All rights reserved.
 *
 * The information in this document is the property of Ericsson. Except
 * as specifically authorized in writing by Ericsson,the receiver of this
 * document shall keep the information contained herein confidential
 * and shall protect the same in whole or in part from disclosure and
 * dissemination to third parties. Disclosure and disseminations to the
 * receiver's employees shall only be made on a strict need to know basis.
 */

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef ERICSSONDISCOVERYMIB_H
#define ERICSSONDISCOVERYMIB_H

/*
 * function declarations 
 */
void            init_ericssonDiscoveryMIB(void);
Netsnmp_Node_Handler handle_eriDiscoveryStatus;

#endif                          /* ERICSSONDISCOVERYMIB_H */
