%%% Generated file; do not edit; to generate: see CAX*/Makefile
%%% Source: csrc/cello_tzii.sig
-define(CELLO_TZII_SIG_BASE, (16#10CEA)).
-define(CELLO_TZII_SERVER_DOWN_IND, (?CELLO_TZII_SIG_BASE + 0)).
-define(CELLO_TZII_SERVER_UP_IND, (?CELLO_TZII_SIG_BASE + 1)).
-define(CELLO_TZII_INITIATE_SERVICE_CFM, (?CELLO_TZII_SIG_BASE + 2)).
-define(CELLO_TZII_INITIATE_SERVICE_SUS, (?CELLO_TZII_SIG_BASE + 3)).
-define(CELLO_TZII_INITIATE_SERVICE_REJ, (?CELLO_TZII_SIG_BASE + 4)).
-define(CELLO_TZII_SERVER_UNPUBLISH_IND, (?CELLO_TZII_SIG_BASE + 5)).
-define(CELLO_TZII_TERMINATE_SERVICE_CFM, (?CELLO_TZII_SIG_BASE + 6)).
-define(CELLO_TZII_SUBSCRIBE_DAYLIGHT_SAVING_TIME_CFM, (?CELLO_TZII_SIG_BASE + 9)).
-define(CELLO_TZII_SUBSCRIBE_DAYLIGHT_SAVING_TIME_REJ, (?CELLO_TZII_SIG_BASE + 10)).
-define(CELLO_TZII_SUBSCRIBE_DAYLIGHT_SAVING_TIME_IND, (?CELLO_TZII_SIG_BASE + 7)).
-define(CELLO_TZII_SUBSCRIBE_LEAP_SECONDS_CFM, (?CELLO_TZII_SIG_BASE + 11)).
-define(CELLO_TZII_SUBSCRIBE_LEAP_SECONDS_REJ, (?CELLO_TZII_SIG_BASE + 12)).
-define(CELLO_TZII_SUBSCRIBE_LEAP_SECONDS_IND, (?CELLO_TZII_SIG_BASE + 8)).
