#!/bin/sh
## -----------------------------------------------------------------------------
## %CCaseFile:	sys_ip6tables %
## @version /main/R5A/1
## %CCaseDate:	2016-01-27 %
## %CCaseDocNo:  %
##
## Author:      etxlg
## Description: 
##  Wrapper script that enables passing of return code from binary run via 
##  APPM/pgh (via file in /tmp) back to the caller.
## 
## -----------------------------------------------------------------------------
##
## ----------------------------------------------------------
## %CCaseTemplateFile:   %
## %CCaseTemplateId: %
##
##
## %CCaseCopyrightBegin%
## Copyright (c) Ericsson AB 2014-2016 All rights reserved.
## 
## The information in this document is the property of Ericsson.
## 
## Except as specifically authorized in writing by Ericsson, the 
## receiver of this document shall keep the information contained 
## herein confidential and shall protect the same in whole or in 
## part from disclosure and dissemination to third parties.
## 
## Disclosure and disseminations to the receivers employees shall 
## only be made on a strict need to know basis.
## %CCaseCopyrightEnd%
##
## ----------------------------------------------------------
## #1.    REVISION LOG
## ----------------------------------------------------------
## Rev        Date         Name        What
## --------   --------     --------    ------------------------
## R	      2016-01-27   etxlg       Created

tmpresf=$1
shift
/usr/sbin/ip6tables $@
echo $? > $tmpresf
