#!/bin/sh
#
# Copyright (c) 2013-2014 Ericsson AB.
# All rights reserved.
#
# The information in this document is the property of Ericsson.
# Except as specifically authorized in writing by Ericsson, the
# receiver of this document shall keep the information contained
# herein confidential and shall protect the same in whole or in
# part from disclosure and dissemination to third parties.
# Disclosure and dissemination to the receiver's employees shall
# only be made on a strict need to know basis.
#

# The script is designed to work in a limited linux environment where the support of certain utilities
# like for instance ps and pgrep varies.
# This is a bourne shell script and is free from any non compatible syntax (e.g bash specific features)

#
# Function:     comea spi-revision
# Availability: control nodes
#
# 0  - if everything is ok.
# ERROR - if something fails.
#
# The format of spi revision is "Major.Minor.Patch".
#

ERROR=1
NAME=`basename $0`
SPI_REVISION="1.6.0"

# Method for Logging Errors to the Syslog.
error() {
    echo $NAME error: $1 >&2
    logger "[ERROR ${NAME}] $1"
}

# Checks arguments of comea-spi-revision.
# If it succeeds then it will print current spi revision and returns 0.
# Otherwise logs the error message to SYSLOG and returns 1.
if [ $# -eq 1 ] && [ "$1" = "spi-revision" ]; then
        echo $SPI_REVISION
        exit 0
else
        error "unknown command"
        exit $ERROR
fi

# End of file
